# AQA "Formulae and statistical tables" (7356/7357/7366/7367), pages 4-11,
# transcribed into plain ASCII calculator notation. Tables live in tables.py.

SHEETS = [
    ('Binomial expansion', [
        '(a+b)^n = a^n + nC1 a^(n-1) b + nC2 a^(n-2) b^2',
        '  + ... + nCr a^(n-r) b^r + ... + b^n',
        '  for n a positive integer',
        'where nCr = n! / (r! (n-r)!)',
        '(1+x)^n = 1 + nx + n(n-1)/(1*2) x^2 + ...',
        '  + n(n-1)...(n-r+1)/(1*2*...*r) x^r + ...',
        '  for |x| < 1, n real',
    ]),
    ('Arithmetic series', [
        'Sn = (1/2) n (a + l)',
        '   = (1/2) n (2a + (n-1) d)',
    ]),
    ('Geometric series', [
        'Sn = a(1 - r^n) / (1 - r)',
        'S_inf = a / (1 - r)   for |r| < 1',
    ]),
    ('Small angles', [
        'For small theta, measured in radians:',
        '  sin theta ~= theta',
        '  cos theta ~= 1 - theta^2 / 2',
        '  tan theta ~= theta',
    ]),
    ('Trig identities', [
        'sin(A+B) = sin A cos B + cos A sin B',
        'sin(A-B) = sin A cos B - cos A sin B',
        'cos(A+B) = cos A cos B - sin A sin B',
        'cos(A-B) = cos A cos B + sin A sin B',
        'tan(A+B) = (tan A + tan B)/(1 - tan A tan B)',
        'tan(A-B) = (tan A - tan B)/(1 + tan A tan B)',
        '  for A +/- B != (k + 1/2) pi',
        'sin A + sin B = 2 sin((A+B)/2) cos((A-B)/2)',
        'sin A - sin B = 2 cos((A+B)/2) sin((A-B)/2)',
        'cos A + cos B = 2 cos((A+B)/2) cos((A-B)/2)',
        'cos A - cos B = -2 sin((A+B)/2) sin((A-B)/2)',
    ]),
    ('Differentiation', [
        "f(x)          f'(x)",
        'tan x         sec^2 x',
        'cosec x       -cosec x cot x',
        'sec x         sec x tan x',
        'cot x         -cosec^2 x',
        'asin x        1 / sqrt(1 - x^2)',
        'acos x        -1 / sqrt(1 - x^2)',
        'atan x        1 / (1 + x^2)',
        'tanh x        sech^2 x',
        'arsinh x      1 / sqrt(1 + x^2)',
        'arcosh x      1 / sqrt(x^2 - 1)',
        'artanh x      1 / (1 - x^2)',
    ]),
    ('Diff from first princ.', [
        "f'(x) = lim_{h->0} (f(x+h) - f(x)) / h",
    ]),
    ('Integration 1', [
        'int u (dv/dx) dx = uv - int v (du/dx) dx',
        '',
        'f(x)          int f(x) dx',
        'tan x         ln|sec x| + c',
        'cot x         ln|sin x| + c',
        'cosec x       -ln|cosec x + cot x| + c',
        '  = ln|tan(x/2)| + c',
        'sec x         ln|sec x + tan x| + c',
        '  = ln|tan(x/2 + pi/4)| + c',
        'tanh x        ln cosh x + c',
    ]),
    ('Integration 2', [
        'f(x)                int f(x) dx',
        '1/sqrt(a^2 - x^2)   asin(x/a) + c',
        '  for |x| < a',
        '1/(a^2 + x^2)       (1/a) atan(x/a) + c',
        '1/sqrt(x^2 - a^2)   arcosh(x/a) + c',
        '  or ln(x + sqrt(x^2 - a^2)) + c   for x > a',
        '1/sqrt(x^2 + a^2)   arsinh(x/a) + c',
        '  or ln(x + sqrt(x^2 + a^2)) + c',
        '1/(a^2 - x^2)       (1/(2a)) ln|(a+x)/(a-x)| + c',
        '  = (1/a) artanh(x/a) + c   for |x| < a',
        '1/(x^2 - a^2)       (1/(2a)) ln|(x-a)/(x+a)| + c',
    ]),
    ('Newton-Raphson', [
        'Numerical solution of equations.',
        'The Newton-Raphson iteration for f(x) = 0:',
        "  x_(n+1) = x_n - f(x_n) / f'(x_n)",
    ]),
    ('Numerical integration', [
        'The trapezium rule:',
        '  int_a^b y dx ~= (1/2) h ((y0 + yn)',
        '    + 2(y1 + y2 + ... + y_(n-1)))',
        '  where h = (b - a) / n',
    ]),
    ('Complex numbers', [
        '(r(cos theta + i sin theta))^n',
        '  = r^n (cos n theta + i sin n theta)',
        'The roots of z^n = 1 are given by',
        '  z = cos(2 pi k/n) + i sin(2 pi k/n)',
        '    = e^(2 pi i k / n)',
        '  for k = 0, 1, 2, ..., n - 1',
    ]),
    ('Matrix transformations', [
        'Anticlockwise rotation through theta about O:',
        '  [cos theta  -sin theta; sin theta  cos theta]',
        'Reflection in the line y = (tan theta) x:',
        '  [cos 2theta  sin 2theta;',
        '   sin 2theta  -cos 2theta]',
        'Rotations in three dimensions through theta',
        '  about an axis, with c = cos theta,',
        '  s = sin theta:',
        '  x-axis:  [1  0  0; 0  c  -s; 0  s  c]',
        '  y-axis:  [c  0  s; 0  1  0; -s  0  c]',
        '  z-axis:  [c  -s  0; s  c  0; 0  0  1]',
    ]),
    ('Summations', [
        'sum_{r=1}^{n} r = n(n+1)/2',
        'sum_{r=1}^{n} r^2 = n(n+1)(2n+1)/6',
        'sum_{r=1}^{n} r^3 = n^2 (n+1)^2 / 4',
    ]),
    ('Maclaurin series', [
        "f(x) = f(0) + x f'(0) + (x^2/2!) f''(0) + ...",
        '  + (x^r/r!) f^(r)(0) + ...',
        'e^x = exp(x) = 1 + x + x^2/2! + ...',
        '  + x^r/r! + ...   for all x',
        'ln(1+x) = x - x^2/2 + x^3/3 - ...',
        '  + (-1)^(r+1) x^r/r + ...   for -1 < x <= 1',
        'sin x = x - x^3/3! + x^5/5! - ...',
        '  + (-1)^r x^(2r+1)/(2r+1)! + ...   for all x',
        'cos x = 1 - x^2/2! + x^4/4! - ...',
        '  + (-1)^r x^(2r)/(2r)! + ...   for all x',
    ]),
    ('Vectors', [
        'The resolved part of a in the direction of b',
        '  is a.b / |b|',
        'Vector product:',
        '  a x b = |a| |b| sin theta n-hat',
        '    = [i  j  k; a1  a2  a3; b1  b2  b3]',
        '    = (a2 b3 - a3 b2) i - (a1 b3 - a3 b1) j',
        '      + (a1 b2 - a2 b1) k',
        'If A has position vector a = a1 i + a2 j + a3 k',
        '  and b = b1 i + b2 j + b3 k, the line through',
        '  A with direction vector b has equation',
        '  (x-a1)/b1 = (y-a2)/b2 = (z-a3)/b3 = lambda',
        '    (Cartesian form)',
        '  or (r - a) x b = 0  (vector product form)',
        'The plane through A parallel to b and c has',
        '  vector equation r = a + s b + t c',
    ]),
    ('Area of a sector', [
        'A = (1/2) int r^2 d theta',
        '  (polar coordinates)',
    ]),
    ('Hyperbolic functions', [
        'cosh^2 x - sinh^2 x = 1',
        'sinh 2x = 2 sinh x cosh x',
        'cosh 2x = cosh^2 x + sinh^2 x',
        'arcosh x = ln(x + sqrt(x^2 - 1))   for x >= 1',
        'arsinh x = ln(x + sqrt(x^2 + 1))',
        'artanh x = (1/2) ln((1+x)/(1-x))',
        '  for |x| < 1',
    ]),
    ('Conics', [
        'Ellipse    x^2/a^2 + y^2/b^2 = 1',
        '  x = a cos theta,  y = b sin theta',
        '  asymptotes: none',
        'Parabola   y^2 = 4ax',
        '  x = a t^2,  y = 2at',
        '  asymptotes: none',
        'Hyperbola  x^2/a^2 - y^2/b^2 = 1',
        '  x = a sec theta,  y = b tan theta',
        '  asymptotes: x/a = +/- y/b',
    ]),
    ('Further num. integ.', [
        'The mid-ordinate rule:',
        '  int_a^b y dx ~= h(y_(1/2) + y_(3/2) + ...',
        '    + y_(n-1/2))',
        '  where h = (b - a) / n',
        "Simpson's rule:",
        '  int_a^b y dx ~= (1/3) h ((y0 + yn)',
        '    + 4(y1 + y3 + ... + y_(n-1))',
        '    + 2(y2 + y4 + ... + y_(n-2)))',
        '  where h = (b - a) / n and n is even',
    ]),
    ('Numerical solution ODE', [
        'For dy/dx = f(x) and small h:',
        "  Euler's method:",
        '    y_(n+1) = y_n + h f(x_n)',
        '    x_(n+1) = x_n + h',
        'For dy/dx = f(x, y):',
        "  Euler's method:",
        '    y_(r+1) = y_r + h f(x_r, y_r)',
        '    x_(r+1) = x_r + h',
        '  Improved Euler method:',
        '    y_(r+1) = y_(r-1) + 2h f(x_r, y_r)',
        '    x_(r+1) = x_r + h',
    ]),
    ('Arc length', [
        's = int sqrt(1 + (dy/dx)^2) dx',
        '  (Cartesian coordinates)',
        's = int sqrt((dx/dt)^2 + (dy/dt)^2) dt',
        '  (parametric form)',
    ]),
    ('Surface area of revol.', [
        'Sx = 2 pi int y sqrt(1 + (dy/dx)^2) dx',
        '  (Cartesian coordinates)',
        'Sx = 2 pi int y sqrt((dx/dt)^2 + (dy/dt)^2) dt',
        '  (parametric form)',
    ]),
    ('Constant acceleration', [
        's = ut + (1/2) a t^2',
        's = vt - (1/2) a t^2',
        'v = u + at',
        's = (1/2)(u + v) t',
        'v^2 = u^2 + 2as',
        'Vector forms (s, u, v, a are vectors):',
        '  s = ut + (1/2) a t^2',
        '  s = vt - (1/2) a t^2',
        '  v = u + at',
        '  s = (1/2)(u + v) t',
    ]),
    ('Centres of mass', [
        'For uniform bodies:',
        'Triangular lamina:',
        '  2/3 along median from vertex',
        'Solid hemisphere, radius r:',
        '  3r/8 from centre',
        'Hemispherical shell, radius r:',
        '  r/2 from centre',
        'Circular arc, radius r, angle at centre',
        '  2 alpha:  r sin(alpha) / alpha  from centre',
        'Sector of circle, radius r, angle at centre',
        '  2 alpha:  2 r sin(alpha) / (3 alpha)',
        '    from centre',
        'Solid cone or pyramid of height h:',
        '  h/4 above the base, on the line from the',
        '  centre of the base to the vertex',
        'Conical shell of height h:',
        '  h/3 above the base, on the line from the',
        '  centre of the base to the vertex',
    ]),
    ('Probability', [
        'u = union, n = intersection',
        'P(A u B) = P(A) + P(B) - P(A n B)',
        'P(A n B) = P(A) x P(B | A)',
    ]),
    ('Standard deviation', [
        'sd = sqrt( sum (x - xbar)^2 / n )',
        '   = sqrt( sum x^2 / n - xbar^2 )',
        'With frequencies f:',
        '  sd = sqrt( sum f(x - xbar)^2 / sum f )',
        '     = sqrt( sum f x^2 / sum f - xbar^2 )',
    ]),
    ('Discrete distributions', [
        'Binomial B(n, p)',
        '  P(X = x) = nCx p^x (1-p)^(n-x)',
        '    for x = 0, 1, 2, ..., n',
        '  mean = np',
        '  variance = np(1-p)',
        'Poisson Po(lambda)',
        '  P(X = x) = e^(-lambda) lambda^x / x!',
        '    for x = 0, 1, 2, ...',
        '  mean = lambda',
        '  variance = lambda',
    ]),
    ('Sampling distributions', [
        'For a random sample X1, X2, ..., Xn of n',
        '  independent observations from a',
        '  distribution having mean mu and variance',
        '  sigma^2:',
        'Xbar is an unbiased estimator of mu, with',
        '  Var(Xbar) = sigma^2 / n',
        'S^2 is an unbiased estimator of sigma^2,',
        '  where S^2 = sum (Xi - Xbar)^2 / (n - 1)',
        'For a random sample of n observations from',
        '  N(mu, sigma^2):',
        '  (Xbar - mu) / (sigma / sqrt(n)) ~ N(0, 1)',
        '  (Xbar - mu) / (S / sqrt(n)) ~ t_(n-1)',
    ]),
    ('Contingency tables', [
        'Distribution-free (non-parametric) tests.',
        'For a contingency table,',
        '  sum (O - E)^2 / E',
        '  is approximately distributed as chi^2',
    ]),
    ('Not in the booklet', [
        'Standard results the booklet leaves out:',
        'a x^2 + b x + c = 0 has roots',
        '  x = (-b +/- sqrt(b^2 - 4ac)) / (2a)',
        '  discriminant b^2 - 4ac',
        'R form, with R = sqrt(a^2 + b^2),',
        '  tan alpha = b/a, R > 0, 0 < alpha < pi/2:',
        '  a cos theta + b sin theta',
        '    = R cos(theta - alpha)',
        '  a sin theta + b cos theta',
        '    = R sin(theta + alpha)',
    ]),
]
