# Generated by mkindex.py from fnum.py: tool labels and input specs.
T = (
    ('U', 'Errors', (
        ('Absolute/rel error', 'approx,exact'),
        ('Error in a+b, a-b', 'a,ea,b,eb'),
        ('Error in ab, a/b', 'a,ea,b,eb'),
        ('Error in f(x)', 'f(x),x,dx'),
        ('Chop vs round d.p.', 'x,d'),
        ('Chop vs round s.f.', 'x,k'),
        ('k s.f. arithmetic', 'f(x),x,k'),
        ('Two forms compared', 'f(x),g(x),x,k'),
    )),
    ('E', 'Solving equations', (
        ('Bisection', 'f(x),a,b,tol?'),
        ('False position', 'f(x),a,b,tol?'),
        ('Secant method', 'f(x),x0,x1,tol?'),
        ('Newton-Raphson', 'f(x),x0,tol?'),
        ('Fixed point x=g(x)', 'g(x),x0,tol?'),
        ('Relaxation', 'g(x),x0,lambda,tol?'),
        ('Staircase/cobweb', 'g(x),x0,n?'),
        ('Order from iterates', 'x*'),
        ('Compare methods', 'f(x),a,b,tol?'),
        ('Justify root to d dp', 'f(x),x,d'),
    )),
    ('D', 'Numerical differentiation', (
        ('Forward and central', 'f(x),x,h'),
        ('Derivative h table', 'f(x),x,h?,k?'),
        ('Error vs h plot', 'f(x),x'),
    )),
    ('N', 'Numerical integration', (
        ('Midpoint rule', 'f(x),a,b,n'),
        ('Trapezium rule', 'f(x),a,b,n'),
        ("Simpson's rule", 'f(x),a,b,n'),
        ('Integration table', 'f(x),a,b,n?'),
    )),
    ('A', 'Approximating functions', (
        ('Forward diff table', 'x0,h,y*'),
        ('Newton fwd estimate', 'x0,h,x,y*'),
        ('Lagrange polynomial', 'xy*'),
    )),
    ('I', 'Improved estimates', (
        ('Richardson', 'p,est*'),
        ('Aitken delta squared', 'x*'),
        ('Limit from ratio r', 'r,est*'),
    )),
)
