# Generated by mkindex.py from falgo.py: tool labels and input specs.
T = (
    ('A', 'Sorting and packing', (
        ('Bubble sort', 'data*'),
        ('Shuttle sort', 'data*'),
        ('Quick sort', 'data*'),
        ('First fit', 'C,sizes*'),
        ('First fit decreasing', 'C,sizes*'),
        ('Order n^k scaling', 'k,n1,t1,n2'),
        ('Order n log n scaling', 'n1,t1,n2'),
    )),
    ('G', 'Graphs', (
        ('Graph from edges', 'n,from to*'),
        ('Digraph from arcs', 'n,from to*'),
        ('Graph from adjacency', 'n,rows*'),
    )),
    ('N', 'Networks', (
        ('Dijkstra', 'start,end or 0,from to w*'),
        ('Dijkstra directed', 'start,end or 0,from to w*'),
        ('Prim', 'start,from to w*'),
        ('Prim from matrix', 'n,start,rows*'),
        ('Kruskal', 'from to w*'),
        ('Shortest path as LP', 'start,end,from to w*'),
    )),
    ('F', 'Network flows', (
        ('Max flow min cut', 'source,sink,from to cap*'),
        ('Cut capacity', 'source,sink,S digits,from to cap*'),
        ('Max flow as LP', 'source,sink,from to cap*'),
    )),
    ('C', 'Critical path', (
        ('Activity on arc', 'from to dur*'),
        ('Precedence table', 'dur k preds*'),
        ('Resource histogram', 'from to dur res*'),
        ('Schedule k workers', 'k,from to dur*'),
    )),
    ('L', 'LP graphical', (
        ('LP 2-D maximise', 'p,q,a b rel c*'),
        ('LP 2-D minimise', 'p,q,a b rel c*'),
        ('LP 3-D vertices', 'p,q,r,a b c rel d*'),
    )),
    ('S', 'Simplex', (
        ('Simplex max <=', 'n,obj rows a b*'),
        ('Sensitivity ranging', 'n,obj rows a b*'),
        ('Two-stage maximise', 'n,obj rows a rel b*'),
        ('Two-stage minimise', 'n,obj rows a rel b*'),
        ('Big-M maximise', 'n,obj rows a rel b*'),
        ('Big-M minimise', 'n,obj rows a rel b*'),
        ('Negative variables', 'n,lows obj rows a rel b*'),
    )),
)
