# PC-only: writes ix_<module>.py, the tool labels and input specs of each tool
# module, so a section's grid shows without loading the (large) module itself.
# Run after changing any tool list; tests_nat.py checks the files are current.
import casui

MODS = []
for c, t, m in casui.MATHS:
    if m not in MODS:
        MODS.append(m)
for name, code, secs in casui.FURTHER:
    for c, t, m in secs:
        if m not in MODS:
            MODS.append(m)

def source(mod):
    out = ['# Generated by mkindex.py from ' + mod + '.py: tool labels and input specs.',
           'T = (']
    for code, title, tools in __import__(mod).SECTIONS:
        out.append('    (%r, %r, (' % (code, title))
        for label, spec, fn in tools:
            out.append('        (%r, %r),' % (label, spec))
        out.append('    )),')
    out.append(')')
    return '\n'.join(out) + '\n'

def files():
    return [('ix_' + m + '.py', source(m)) for m in MODS]

if __name__ == '__main__':
    for path, src in files():
        open(path, 'w').write(src)
        print('wrote', path)
