# PC-only: precompiles the notes (notes_*.py) and the formula booklet
# (formulae.py) into tn_*.py for the calculator. Every line is typeset by
# tex.py here, broken to the screen width and drawn into a display list
# (strings and pixel runs) that notesui.lines reads, so opening a topic on
# the calculator parses and measures nothing.
#   python3 mknotes.py          write tn_*.py
# tests_notes.py checks the files are current.
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__)) or '.'
sys.path.insert(0, HERE)

import tex
import casrender
import casui
import font

LINE = 376      # right edge of a result line
BOOK = 'tn_fb'  # the booklet


def module_name(notes_mod):
    return 'tn' + notes_mod[5:]       # notes_mp1 -> tn_mp1


def _gap(s):
    # index of a run of three or more spaces after the text starts, or -1
    t = s.lstrip(' ')
    j = t.find('   ')
    return -1 if j <= 0 else len(s) - len(t) + j


def n2(v):
    assert 0 <= v < 8100, v
    return chr(32 + v // 90) + chr(32 + v % 90)


def n1(v):
    assert 0 <= v < 95, v
    return chr(32 + v)


def runs_of(ops):
    # pixel ops -> the pixels they set, in order (for tests)
    pts = []
    keep = casrender.set_pixel
    casrender.set_pixel = lambda x, y, c=None: pts.append((x, y))
    try:
        casrender.play(ops or [], 0, 0, (0, 0, 0))
    finally:
        casrender.set_pixel = keep
    return pts


def encode(blk):
    # a casui block -> one display line (notesui.lines reads it): kind,
    # height, then \x01 x y size length text for a string, \x02 and an op
    # (casrender.record) for pixels: 0 hline x0 x1 y, 1 vline x y0 y1,
    # 2 line x0 y0 x1 y1, 3 glyph code size x base, 4 pixels n x y ...
    kind, strs, runs, h, ops = blk
    assert not runs
    out = kind + n1(h)
    for x, y, text, size in strs:
        while text:
            out += '\x01' + n2(x) + n1(y) + size[0] + n1(len(text[:90])) + text[:90]
            x += font.strw(text[:90], size)
            text = text[90:]
    for o in ops or []:
        k = o[0]
        out += '\x02' + str(k)
        if k == 3:
            out += o[1] + o[2][0] + n2(o[3]) + n2(o[4])
        elif k == 4:
            out += n1(len(o[1])) + ''.join([n2(v) for v in o[1]])
        else:
            out += ''.join([n2(v) for v in o[1:]])
    return out


def page(lines, booklet):
    # one page: display lines (notesui.lines reads them)
    out = []
    table = booklet and [ln for ln in lines if ln.startswith('f(x)') and _gap(ln) > 0]
    col = 0
    if table:
        for ln in lines:
            j = _gap(ln)
            if j > 0 and not ln.startswith(' '):
                w = casrender.measure(tex.row(ln[:j]))[0]
                col = max(col, w + 14)
    for ln in lines:
        lead = len(ln) - len(ln.lstrip(' '))
        if booklet:
            kind = 'a'
            x = 8 + 6 * lead
        else:
            kind = 'w' if lead else 'a'
            x = 16 if lead else 8
        text = ln.strip()
        j = _gap(ln)
        if table and j > 0 and not lead:
            left = tex.row(ln[:j])
            right = tex.row(ln[j:].strip())
            w = casrender.measure(left)[0]
            box = casrender.flat(('row', [left, ('sp', col - w), right]))
        else:
            box = tex.row(text)
        for r, dx in tex.lines(box, LINE - x):
            if casrender.measure(r)[0] > LINE - x - dx:
                r = casrender.shrink(r)
            out.append(encode(casui.block(kind, r, x + dx)))
    return '\n'.join(out)


def sources():
    # {module: source} for every tn_*.py
    import casui
    import formulae
    out = {}
    for name, mods in casui.NOTE_PAPERS:
        for m in mods:
            notes = __import__(m).NOTES
            body = ['# Generated by mknotes.py from %s.py: display lists, read by notesui.lines.' % m,
                    'N = (']
            for topic, lines in notes:
                body.append('    %r,' % page(lines, False))
            body.append(')')
            out[module_name(m)] = '\n'.join(body) + '\n'
    body = ['# Generated by mknotes.py from formulae.py: booklet display lists, read by notesui.lines.',
            'T = (']
    for title, lines in formulae.SHEETS:
        body.append('    %r,' % title)
    body.append(')')
    body.append('N = (')
    for title, lines in formulae.SHEETS:
        body.append('    %r,' % page(lines, True))
    body.append(')')
    out[BOOK] = '\n'.join(body) + '\n'
    return out


if __name__ == '__main__':
    src = sources()
    for m in sorted(src):
        open(os.path.join(HERE, m + '.py'), 'w').write(src[m])
    print('wrote ' + ', '.join(sorted(src)))
