# Notes: MEI H645 Core Pure Y420, part 3 (series, calculus, polar,
# hyperbolic functions, differential equations).
NOTES = [
    ('Series', [
        'sum r = n(n + 1)/2',
        'sum r^2 = n(n + 1)(2n + 1)/6',
        'sum r^3 = n^2(n + 1)^2/4',
        '  (sums from r = 1 to n)',
        'sum of 1, r = 1 to n: n',
        'r = k to n: S(n) - S(k - 1)',
        'Split: sum(a f + b g)',
        '  = a sum f + b sum g',
        'Method of differences:',
        '  write term as f(r) - f(r + 1)',
        '  (partial fractions), list',
        '  first and last terms, cancel',
        '  sum = f(1) - f(n + 1)',
        'Gaps of 2 (f(r) - f(r + 2)):',
        '  two terms survive each end',
        'Converges: sum to n has a limit',
        '  as n -> infinity',
    ]),
    ('Maclaurin series', [
        'f(x) = f(0) + f\'(0)x',
        "  + f''(0)x^2/2! + ...",
        "  + f^(r)(0)x^r/r! + ...",
        'e^x, sin x, cos x: all x',
        'ln(1 + x): -1 < x <= 1',
        '(1 + x)^n: |x| < 1 (n not a',
        '  positive integer)',
        'Standard series: formula book',
        'Substitute: e^(2x), ln(1 - x^2),',
        '  validity changes, e.g.',
        '  ln(1 + 2x): -1/2 < x <= 1/2',
        'Products: multiply series, keep',
        '  the powers needed',
        'No series for ln x or 1/x:',
        '  f(0) must exist',
        'Approximation: good for small x',
    ]),
    ('Inverse trig calculus', [
        'd/dx arcsin x = 1/sqrt(1 - x^2)',
        'd/dx arccos x = -1/sqrt(1 - x^2)',
        'd/dx arctan x = 1/(1 + x^2)',
        'int 1/sqrt(a^2 - x^2) dx',
        '  = arcsin(x/a) + c, |x| < a',
        'int 1/(a^2 + x^2) dx',
        '  = (1/a) arctan(x/a) + c',
        'Spot: a^2 + x^2 or sqrt(a^2 - x^2)',
        '  in the denominator',
        'Complete the square:',
        '  1/(x^2 + 4x + 13)',
        '  = 1/((x + 2)^2 + 9)',
        'Or substitute x = a sin u,',
        '  x = a tan u',
    ]),
    ('Partial fractions', [
        'Quadratic factor:',
        '  (...)/((x + a)(x^2 + b))',
        '  = A/(x + a) + (Bx + C)/(x^2 + b)',
        'Repeated: A/(x + a) + B/(x + a)^2',
        'int (Bx + C)/(x^2 + b^2) dx',
        '  = (B/2) ln(x^2 + b^2)',
        '  + (C/b) arctan(x/b) + c',
        'Improper: divide first',
    ]),
    ('Improper integrals', [
        'Infinite limit:',
        '  int from a to inf of f',
        '  = lim (t -> inf) int a to t of f',
        'Integrand undefined at an end a:',
        '  replace a by t, let t -> a',
        'Converges if the limit is finite',
        'Useful limits as x -> inf:',
        '  x^n e^(-x) -> 0',
        '  ln x / x^n -> 0 (n > 0)',
        '  x^n ln x -> 0 as x -> 0+ (n > 0)',
        'Write the limit explicitly',
    ]),
    ('Volumes, mean value', [
        'About the x-axis:',
        '  V = pi int y^2 dx, x = a to b',
        'About the y-axis:',
        '  V = pi int x^2 dy, y = c to d',
        'Between two curves (x-axis):',
        '  pi int (y1^2 - y2^2) dx',
        'Parametric: pi int y^2 (dx/dt) dt',
        'Cone, sphere: check with formulae',
        'Mean value of f on [a, b]:',
        '  (1/(b - a)) int a to b of f(x) dx',
        'Rotating gives volume in cubic',
        '  units; keep pi exact',
    ]),
    ('Polar coordinates', [
        'x = r cos theta, y = r sin theta',
        'r^2 = x^2 + y^2',
        'tan theta = y/x (check quadrant)',
        'r >= 0: no points where r < 0',
        'Area = (1/2) int r^2 d theta',
        '  cos^2, sin^2: use double angles',
        'r = a: circle, centre O',
        'r = 2a cos theta: circle through O',
        'r = a theta: spiral',
        'r = a(1 + cos theta): cardioid',
        'r = a cos(n theta): rose, n petals',
        '  if n odd, 2n if n even',
        'Tangent at the pole: where r = 0',
        'Sketch: table of r for theta,',
        '  check symmetry (theta -> -theta)',
        'Max r: dr/d theta = 0 or bounds',
    ]),
    ('Hyperbolic functions', [
        'sinh x = (e^x - e^(-x))/2',
        'cosh x = (e^x + e^(-x))/2',
        'tanh x = sinh x/cosh x',
        'cosh^2 x - sinh^2 x = 1',
        'sinh 2x = 2 sinh x cosh x',
        'cosh 2x = cosh^2 x + sinh^2 x',
        'cosh x >= 1, even; sinh odd',
        'tanh: -1 < tanh x < 1,',
        '  asymptotes y = +-1',
        'd/dx sinh x = cosh x',
        'd/dx cosh x = sinh x',
        'd/dx tanh x = sech^2 x',
        'int sinh x dx = cosh x + c',
        'int cosh x dx = sinh x + c',
        'Proofs: write in e^x',
    ]),
    ('Inverse hyperbolic', [
        'arsinh x = ln(x + sqrt(x^2 + 1))',
        '  all real x',
        'arcosh x = ln(x + sqrt(x^2 - 1))',
        '  x >= 1, arcosh x >= 0',
        'artanh x = (1/2)ln((1 + x)/(1 - x))',
        '  |x| < 1',
        'Derive: y = arsinh x, x = sinh y,',
        '  quadratic in e^y, take root > 0',
        'int 1/sqrt(x^2 + a^2) dx',
        '  = arsinh(x/a) + c',
        'int 1/sqrt(x^2 - a^2) dx',
        '  = arcosh(x/a) + c, x > a',
        'Log forms give exact answers',
        'Solve sinh x = k: x = arsinh k;',
        '  cosh x = k > 1: x = +-arcosh k',
    ]),
    ('First order DEs', [
        'Separable: int 1/g(y) dy',
        '  = int f(x) dx',
        'Integrating factor:',
        '1 write dy/dx + P(x)y = Q(x)',
        '  (divide so dy/dx has coeff 1)',
        '2 I = e^(int P dx), no + c',
        '3 d/dx (I y) = I Q',
        '4 I y = int I Q dx + c',
        '5 divide by I (the c too)',
        'e^(ln f) = f: simplify I',
        'General solution: has c',
        'Particular: use the condition',
        'Check: substitute back',
    ]),
    ('Second order DEs', [
        'ay\'\' + by\' + cy = 0',
        'Auxiliary: am^2 + bm + c = 0',
        'Real roots m1 != m2:',
        '  y = A e^(m1 x) + B e^(m2 x)',
        'Repeated root m:',
        '  y = (A + Bx) e^(mx)',
        'Complex roots p +- qi:',
        '  y = e^(px)(A cos qx + B sin qx)',
        'Roots +-qi:',
        '  y = A cos qx + B sin qx',
        'ay\'\' + by\' + cy = f(x):',
        '  y = CF + PI',
        'Find A, B from conditions on',
        '  the full solution (CF + PI)',
        'Two conditions for two',
        '  constants',
    ]),
    ('Particular integrals', [
        'f(x) = k: try lambda',
        'Polynomial: same degree, all',
        '  powers, e.g. ax^2 + bx + c',
        'k e^(px): try lambda e^(px)',
        'k cos wx and/or k sin wx: try',
        '  lambda cos wx + mu sin wx',
        'Trial already in the CF:',
        '  times by x (x^2 if p is a',
        '  repeated root)',
        'Substitute the trial, compare',
        '  coefficients',
        "Same trials for y' + ky = f(x)",
    ]),
    ('SHM, damping', [
        "x'' = -w^2 x: SHM",
        '  x = A cos wt + B sin wt',
        '  = R cos(wt - phi)',
        '  amplitude R = sqrt(A^2 + B^2)',
        '  period 2pi/w',
        "x'' + kx' + w^2 x = 0, k > 0:",
        '  k^2 > 4w^2: overdamped,',
        '  no oscillation',
        '  k^2 = 4w^2: critically damped',
        '  k^2 < 4w^2: underdamped,',
        '  oscillations decay',
        'Forced: add a PI; long-term',
        '  CF -> 0 if damped, PI remains',
        'a = dv/dt = v dv/dx = d2x/dt2',
        'F = ma gives the DE',
    ]),
    ('Coupled DEs, modelling', [
        "x' = ax + by, y' = cx + dy:",
        "1 differentiate the first:",
        "  x'' = ax' + by'",
        "2 substitute y' then",
        "  y = (x' - ax)/b",
        "3 solve the 2nd order DE in x",
        "4 y from y = (x' - ax)/b",
        '  (do not integrate y separately)',
        'Predator-prey: interpret signs,',
        '  long-term behaviour, a time',
        '  when a population reaches 0',
        '  (model fails)',
        'Modelling: define variables and',
        '  units; rate of change words',
        '  -> derivatives; check limits',
    ]),
]
