# Notes: MEI H645 Core Pure Y420, part 2 (matrices, vectors in 3-D).
NOTES = [
    ('Matrices', [
        'm \\times n: m rows, n columns',
        'AB exists if columns of A =',
        '  rows of B; AB is (rows A) \\times',
        '  (columns B)',
        'AB != BA in general',
        '(AB)C = A(BC) (associative)',
        'O zero matrix, I identity:',
        '  AI = IA = A',
        'det [a b; c d] = ad - bc',
        'Inverse [a b; c d]:',
        '  (1/(ad - bc)) [d -b; -c a]',
        'Singular: det = 0, no inverse',
        '(AB)^-1 = B^-1 A^-1',
        'det(AB) = det A det B',
        'AX = B: X = A^-1 B (left multiply)',
        'XA = B: X = B A^-1',
    ]),
    ('3x3 det and inverse', [
        'det, expanding the top row:',
        '  a(ei - fh) - b(di - fg)',
        '  + c(dh - eg)',
        '  for [a b c; d e f; g h i]',
        'Signs: + - + / - + - / + - +',
        'Inverse (no calculator):',
        '1 matrix of minors',
        '2 apply signs: cofactors',
        '3 transpose: adjugate',
        '4 divide by det',
        'Check: M M^-1 = I',
        'det of a 3x3 with a parameter k:',
        '  singular where det = 0',
    ]),
    ('Matrix transforms', [
        'Columns: images of i, j (and k)',
        'Rotation theta anticlockwise:',
        '  [cos -sin; sin cos]',
        'Reflect in y = x tan t:',
        '  [cos 2t  sin 2t; sin 2t  -cos 2t]',
        'Enlargement sf k: [k 0; 0 k]',
        'Stretch x-direction sf k: [k 0; 0 1]',
        'Shear, x-axis fixed: [1 k; 0 1]',
        '  (x, y) -> (x + ky, y)',
        'Do A then B: matrix BA',
        '|det|: area (3-D: volume) factor',
        'det < 0: orientation reversed',
        '3-D reflect in z = 0: z -> -z,',
        '  [1 0 0; 0 1 0; 0 0 -1]; x = 0, y = 0',
        '  alike',
        '3-D rotate theta (anticlockwise',
        '  looking down the axis to O):',
        'about z: [cos -sin 0; sin cos 0; 0 0 1]',
        'about x: [1 0 0; 0 cos -sin; 0 sin cos]',
        'about y: [cos 0 sin; 0 1 0; -sin 0 cos]',
        '90 deg: cos = 0, sin = 1',
        'Find M: images of the unit vectors',
    ]),
    ('Invariant points, lines', [
        'Invariant point: Mx = x',
        'Line of invariant points: every',
        '  point on it maps to itself',
        'Invariant line: every point on it',
        '  maps to a point on the same line',
        '  (not necessarily itself)',
        'Find y = mx + c invariant:',
        '  image of (x, mx + c) = (X, Y),',
        '  need Y = mX + c for all x;',
        '  compare coefficients for m, c',
        'Through the origin y = mx: M (1, m)',
        '  is a multiple of (1, m)',
        'Lines of invariant points always',
        '  pass through the origin',
    ]),
    ('3 equations, 3 planes', [
        'Mx = b: x = M^-1 b if det M != 0',
        '  (planes meet at one point)',
        'det M = 0: no unique solution',
        '  consistent: infinitely many,',
        '  inconsistent: none',
        'det = 0, check by eliminating:',
        '  sheaf: all three share a line',
        '  prism: each pair meets, lines',
        '  parallel, no common point',
        '  two or three parallel planes',
        '  (normals multiples): no solution',
        '  same plane: infinitely many',
        'Parallel planes: normals are',
        '  multiples, constants differ',
    ]),
    ('Products of vectors', [
        'a.b = a1b1 + a2b2 + a3b3',
        'a.b = |a||b| cos theta',
        'Perpendicular: a.b = 0',
        'a * b = (a2b3 - a3b2,',
        '  a3b1 - a1b3, a1b2 - a2b1)',
        '|a * b| = |a||b| sin theta',
        'a * b = |a||b| sin theta nhat',
        'a * b is perpendicular to a and b',
        'b * a = -(a * b)',
        'a * b = 0: a, b parallel',
        'Triangle ABC area: (1/2)|AB * AC|',
        'Parallelogram area: |a * b|',
    ]),
    ('Lines in 3-D', [
        'r = a + t d (point a, direction d)',
        'Cartesian: (x - a1)/d1',
        '  = (y - a2)/d2 = (z - a3)/d3',
        '  d_i = 0: that coordinate = a_i',
        'Angle between lines: directions',
        '  cos theta = |d1.d2|/(|d1||d2|)',
        'Intersect: equate components,',
        '  solve two, check the third',
        'Parallel: directions multiples',
        'Skew: not parallel, do not meet',
        'Foot of perpendicular from P:',
        '  (a + t d - p).d = 0, solve t',
    ]),
    ('Planes', [
        'Vector: (r - a).n = 0, r.n = a.n',
        'Cartesian: n1 x + n2 y + n3 z = d',
        '  normal n = (n1, n2, n3)',
        'Through 3 points: n = AB * AC',
        'r = a + s b + t c: n = b * c',
        'Angle between planes: between',
        '  normals, cos = |n1.n2|/(|n1||n2|)',
        'Line and plane angle:',
        '  sin theta = |d.n|/(|d||n|)',
        'Line meets plane: put a + t d',
        '  into r.n = d, solve for t',
        'Line parallel to plane: d.n = 0',
        'Line of two planes: direction',
        '  n1 * n2, find one common point',
    ]),
    ('Distances', [
        'Point (x0, y0, z0) to plane',
        '  n1 x + n2 y + n3 z = d:',
        '  |n1x0 + n2y0 + n3z0 - d|/|n|',
        'Point P to line r = a + t d:',
        '  |(p - a) * d|/|d|',
        '  or foot of perpendicular,',
        '  (a + t d - p).d = 0',
        'Skew lines a1 + s d1, a2 + t d2:',
        '  n = d1 * d2',
        '  |(a2 - a1).n|/|n|',
        'Parallel lines: point on one to',
        '  the other line',
        'Shortest distance: perpendicular',
        '  to both lines',
    ]),
]
