# Notes: AQA 7357 Mechanics.
NOTES = [
    ('Units, modelling', [
        'SI: length m, time s, mass kg',
        'Velocity m s^-1, acceleration m s^-2',
        'Force, weight: N = kg m s^-2',
        'Moment: N m',
        'km/h to m/s: divide by 3.6',
        'g = 9.8 m s^-2 unless told;',
        '  g varies with location',
        'Particle: size ignored, no rotation',
        'Light: mass ignored',
        'Inextensible: same speed both ends',
        'Smooth: no friction',
        'Rigid: does not bend',
        'Uniform: mass evenly spread,',
        '  weight acts at the centre',
        'Ignore air resistance: often the',
        '  first refinement to drop',
    ]),
    ('Kinematics graphs', [
        'Displacement, velocity,',
        '  acceleration: vectors (signed)',
        'Distance, speed: scalars',
        's-t graph: gradient = velocity',
        'v-t graph: gradient = acceleration',
        '  area = displacement',
        '  area below the axis: moving',
        '  backwards (negative)',
        'Distance = total area (sizes)',
        'Average speed = distance / time',
        'Average velocity =',
        '  displacement / time',
    ]),
    ('SUVAT', [
        'Constant acceleration only',
        'v = u + at',
        's = ut + (1/2)at^2',
        's = vt - (1/2)at^2',
        's = (u + v)t/2',
        'v^2 = u^2 + 2as',
        'Pick a positive direction; under',
        '  gravity a = -9.8 if up is +',
        'List s u v a t, choose the',
        '  equation without the unknown',
        '  you do not need',
        'Quadratic in t: two times',
        '  (passing the point up and down)',
        'Vectors: v = u + at,',
        '  r = r0 + ut + (1/2)at^2',
    ]),
    ('Variable acceleration', [
        'v = dr/dt, a = dv/dt = d2r/dt2',
        'r = int v dt, v = int a dt',
        '+ c from the initial conditions',
        'Max / min velocity: a = 0',
        'At rest: v = 0',
        'Distance: split where v changes',
        '  sign; add the sizes',
        'Vectors: differentiate or',
        '  integrate each component',
        'Speed = |v|',
        'Direction of motion: of v',
        'SUVAT not allowed if a varies',
    ]),
    ('Projectiles', [
        'Speed U at angle theta above',
        '  the horizontal:',
        'Horizontal: a = 0',
        '  x = U cos(theta) t',
        'Vertical: a = -g (up positive)',
        '  y = U sin(theta) t - (1/2)g t^2',
        '  v_y = U sin(theta) - g t',
        'Max height: v_y = 0',
        'Flight time (level ground): y = 0',
        '  T = 2U sin(theta)/g',
        'Range: x at time T',
        '  R = U^2 sin(2theta)/g, max at 45',
        'Speed: sqrt(v_x^2 + v_y^2)',
        'Direction: tan a = v_y/v_x',
        'Assume: particle, no air',
        '  resistance, no spin, g constant',
    ]),
    ("Newton's laws", [
        '1: no resultant force -> rest or',
        '  constant velocity',
        '2: F = ma, F the resultant force',
        '3: A on B equal and opposite to',
        '  B on A',
        'Weight W = mg, acts down',
        'Normal reaction R: perpendicular',
        '  to the surface',
        'Resolve: component F cos theta',
        '  along a direction at theta',
        'Slope at alpha: weight gives',
        '  mg sin alpha down the slope,',
        '  mg cos alpha into the slope',
        'Equilibrium: resolve two',
        '  perpendicular ways, each sum 0',
        'Vector forces: add components,',
        '  sum F = ma as vectors',
        'Draw a force diagram first',
    ]),
    ('Connected particles', [
        'Light inextensible string: same',
        '  tension throughout, same size',
        '  of acceleration',
        'Smooth pulley: tension the same',
        '  on both sides',
        'F = ma for each particle, in its',
        '  own direction of motion',
        'Whole system: internal forces',
        '  (tension) cancel',
        'Car and trailer: tow bar tension',
        '  (or thrust if compressed)',
        'Lift: R - mg = ma',
        'String breaks / mass lands:',
        '  new phase, new acceleration;',
        '  velocity carries over',
        'Force on the pulley: resultant of',
        '  the two tensions',
    ]),
    ('Friction', [
        'F <= mu R',
        'Limiting (about to slip) or',
        '  moving: F = mu R',
        'Acts against motion, or against',
        '  the way it would move',
        'R from resolving perpendicular',
        '  to the surface (not always mg)',
        'Pull P at angle theta above the',
        '  horizontal: R = mg - P sin theta',
        'Rough: has friction, mu > 0',
        'Static: F only as large as needed',
        'Check direction: if F needed',
        '  > mu R, it moves',
    ]),
    ('Moments', [
        'Moment = force x perpendicular',
        '  distance from the pivot (N m)',
        'Equilibrium of a rigid body:',
        '  resultant force = 0 and',
        '  clockwise = anticlockwise',
        '  moments about any point',
        'Take moments about the point',
        '  with the most unknown forces',
        'Uniform rod: weight at the middle',
        'Light rod: no weight',
        'About to tilt about a support:',
        '  reaction at the other support 0',
        'Force at angle: use its',
        '  perpendicular component',
        'Non-uniform: centre of mass',
        '  at an unknown distance x',
    ]),
]
