# Notes: MEI H645 Statistics Major Y422, part 1 (random variables and
# distributions).
NOTES = [
    ('Discrete RVs', [
        'sum of P(X = x) = 1',
        'E(X) = mu = sum x P(X = x)',
        'E(X^2) = sum x^2 P(X = x)',
        'Var(X) = E(X^2) - mu^2',
        'sd = sqrt(Var(X))',
        'E(g(X)) = sum g(x) P(X = x)',
        'E(a + bX) = a + bE(X)',
        'Var(a + bX) = b^2 Var(X)',
        'E(X +- Y) = E(X) +- E(Y)',
        'Var(X +- Y) = Var(X) + Var(Y)',
        '  X, Y independent',
        'E(X^2) != (E(X))^2 in general',
        'Unknown k: use sum of p = 1',
    ]),
    ('Discrete uniform', [
        'X takes 1, 2, ..., n equally:',
        '  P(X = r) = 1/n',
        '  E(X) = (n + 1)/2',
        '  Var(X) = (n^2 - 1)/12',
        'On a, a+1, ..., b (n = b - a + 1):',
        '  E(X) = (a + b)/2',
        '  Var(X) = (n^2 - 1)/12',
        'Other evenly spaced values:',
        '  write as a + bY, Y on 1..n',
        'Model: all outcomes equally',
        '  likely (fair dice, random digit)',
    ]),
    ('Binomial', [
        'X ~ B(n, p):',
        '  fixed n independent trials',
        '  success or failure each',
        '  constant p',
        'P(X = r) = nCr p^r (1-p)^(n-r)',
        'E(X) = np, Var(X) = np(1 - p)',
        'Use the cumulative function:',
        '  P(X >= r) = 1 - P(X <= r - 1)',
        'Not binomial: p changes, trials',
        '  linked, no fixed number',
    ]),
    ('Poisson', [
        'X ~ Po(lambda): events occur',
        '  randomly, independently,',
        '  singly, at a constant mean rate',
        'P(X = r) = e^(-lambda)lambda^r/r!',
        '  r = 0, 1, 2, ...',
        'E(X) = Var(X) = lambda',
        'Data: mean close to variance',
        '  suggests Poisson',
        'Scale lambda with interval length',
        'X ~ Po(a), Y ~ Po(b), independent:',
        '  X + Y ~ Po(a + b)',
        'B(n, p) ~ Po(np): n large,',
        '  p small',
        'P(X >= 1) = 1 - e^(-lambda)',
    ]),
    ('Geometric', [
        'X ~ Geo(p): number of trials up',
        '  to and including the 1st success',
        '  independent trials, constant p',
        'P(X = r) = (1 - p)^(r - 1) p',
        '  r = 1, 2, 3, ...',
        'P(X > r) = (1 - p)^r',
        '  (first r trials all fail)',
        'P(X <= r) = 1 - (1 - p)^r',
        'E(X) = 1/p',
        'Var(X) = (1 - p)/p^2',
        'Least r with P(X <= r) >= k:',
        '  logs, flip when dividing by',
        '  ln(1 - p) < 0',
    ]),
    ('Continuous RVs', [
        'pdf f(x) >= 0, int f(x) dx = 1',
        'P(a < X < b) = int from a to b f',
        'P(X = a) = 0',
        'E(X) = int x f(x) dx',
        'E(X^2) = int x^2 f(x) dx',
        'Var(X) = E(X^2) - mu^2',
        'E(g(X)) = int g(x) f(x) dx',
        'Mode: max of f (f\' = 0 or an end)',
        'Piecewise: integrate each part',
        '  over its own range, add',
        'Unknown k: total area = 1',
        'Model: sketch f, check shape',
        '  against the context',
    ]),
    ('Cumulative distribution', [
        'F(x) = P(X <= x)',
        '  = int from lower end to x of f(t) dt',
        'f(x) = F\'(x)',
        'F = 0 below the range, 1 above',
        'F continuous; piecewise: add the',
        '  area of earlier parts',
        'Median m: F(m) = 1/2',
        'Quartiles: F(q) = 1/4, 3/4',
        'Percentile: F(x) = p',
        'P(a < X <= b) = F(b) - F(a)',
        'Give F for every x (all pieces)',
    ]),
    ('Uniform U(a, b)', [
        'Rectangular distribution:',
        '  f(x) = 1/(b - a), a <= x <= b',
        'E(X) = (a + b)/2',
        'Var(X) = (b - a)^2/12',
        'F(x) = (x - a)/(b - a)',
        'P(c < X < d) = (d - c)/(b - a)',
        'Rounding errors: e.g. to the',
        '  nearest integer, U(-0.5, 0.5)',
    ]),
    ('Normal', [
        'X ~ N(mu, sigma^2)',
        'Z = (X - mu)/sigma ~ N(0, 1)',
        'aX + b ~ N(a mu + b, a^2 sigma^2)',
        'X, Y independent Normal:',
        '  X +- Y ~ N(mu1 +- mu2,',
        '  sigma1^2 + sigma2^2)',
        '  aX + bY: mean a mu1 + b mu2,',
        '  var a^2 s1^2 + b^2 s2^2',
        'X1 + ... + Xn (independent):',
        '  N(n mu, n sigma^2)',
        'nX (one value times n):',
        '  N(n mu, n^2 sigma^2)',
        'Parameters from a sample:',
        '  use xbar and s',
        'P(X > Y) = P(X - Y > 0)',
    ]),
    ('Normal model', [
        'Suitable: continuous, symmetric,',
        '  unimodal, bell-shaped',
        '  ~95% within mu +- 2 sigma',
        '  ~99.7% within mu +- 3 sigma',
        'Normal probability plot: points',
        '  close to a straight line ->',
        '  Normal is reasonable',
        '  curved / S-shape -> not Normal',
        'Not suitable: skewed, bounded',
        '  close to the mean, discrete',
        '  with few values',
        'Compare expected and observed',
        '  frequencies (or chi-squared)',
    ]),
]
