# Notes: AQA 7357 Pure, part 1 (proof, algebra, functions, coordinates).
NOTES = [
    ('Proof', [
        'Deduction: known facts -> logical steps',
        'Exhaustion: split into finite cases,',
        '  check every case',
        'Disproof: one counter-example',
        'Contradiction: assume the opposite,',
        '  reach something impossible',
        'Even 2n, odd 2n+1, consecutive n, n+1',
        'Rational: p/q, p q integers, q != 0',
        'sqrt 2 irrational:',
        '1 assume sqrt 2 = a/b, lowest terms',
        '2 a^2 = 2b^2, so a^2 even, a even',
        '3 a = 2k: 4k^2 = 2b^2, b^2 = 2k^2',
        '4 b even too: contradicts lowest terms',
        'Infinitely many primes:',
        '1 assume finite: p_1, p_2, ..., p_n',
        '2 N = p_1 p_2 ... p_n + 1',
        '3 N leaves remainder 1 on division',
        '  by every p_i',
        '4 so N is prime or has a prime factor',
        '  not in the list: contradiction',
        'End with a conclusion in words',
    ]),
    ('Indices and surds', [
        'a^m a^n = a^(m+n)',
        'a^m / a^n = a^(m-n)',
        '(a^m)^n = a^(mn)',
        'a^0 = 1 (a != 0)',
        'a^(-n) = 1/a^n',
        'a^(1/n) = nth root of a',
        'a^(m/n) = (nth root of a)^m',
        'sqrt(ab) = sqrt a sqrt b (a, b >= 0)',
        'sqrt(a/b) = sqrt a / sqrt b (b > 0)',
        'sqrt a + sqrt b != sqrt(a+b)',
        '(a + sqrt b)(a - sqrt b) = a^2 - b',
        'Rationalise 1/sqrt a: times sqrt a/sqrt a',
        'Rationalise 1/(a + sqrt b):',
        '  times (a - sqrt b)/(a - sqrt b)',
    ]),
    ('Quadratics', [
        'ax^2 + bx + c, discriminant b^2 - 4ac:',
        '  > 0  two distinct real roots',
        '  = 0  one repeated root',
        '  < 0  no real roots',
        '  >= 0 real roots',
        'x = (-b \\pm sqrt(b^2 - 4ac))/(2a)',
        'Completed square:',
        '  a(x + p)^2 + q, vertex (-p, q)',
        '  x^2 + bx = (x + b/2)^2 - b^2/4',
        'Turning point: min if a > 0, max a < 0',
        'Quadratic in a function: let',
        '  u = x^2, e^x, sin x, x^(1/3) etc',
        '  solve for u, reject invalid u',
        '  (e^x > 0, |sin x| <= 1), then x',
        'Linear + quadratic simultaneous:',
        '  substitute the linear one',
        '  discriminant 0: line is a tangent',
    ]),
    ('Inequalities', [
        'Times or divide by a negative: flip',
        'Never times by an unknown-sign term;',
        '  times by a square, or collect on',
        '  one side and factorise',
        'Quadratic: roots a < b, then sketch',
        '  (x-a)(x-b) < 0:  a < x < b',
        '  (x-a)(x-b) > 0:  x < a or x > b',
        'Fractions: times by (denom)^2',
        'and = both hold (intersection)',
        'or = either holds (union)',
        'Set notation:',
        '  {x : a < x < b}',
        '  {x : x < a} \\cup {x : x > b}',
        'Regions: < > dashed line,',
        '  <= >= solid line',
        'y > f(x) is the region above',
        '  the curve y = f(x)',
    ]),
    ('Polynomials', [
        'Factor theorem:',
        '  f(a) = 0 <=> (x - a) is a factor',
        '  f(b/a) = 0 <=> (ax - b) is a factor',
        'Remainder on dividing by (x - a): f(a)',
        'Cubic: try factors of the constant,',
        '  then divide or compare coefficients',
        'Division by linear (x - a) only',
        'Rational expressions: factorise fully,',
        '  then cancel common factors',
        'Sketch: sign of leading term,',
        '  roots, y-intercept',
        'Single root: crosses the axis',
        'Double root: touches (turning point)',
        'Triple root: crosses, flat (inflection)',
        'Degree n: at most n roots,',
        '  at most n - 1 turning points',
    ]),
    ('Graphs', [
        'y = k/x: asymptotes x = 0, y = 0',
        '  k > 0: quadrants 1 and 3',
        'y = k/x^2: asymptotes x = 0, y = 0',
        '  k > 0: both branches above x-axis',
        'y = |ax + b|: V shape, vertex at',
        '  x = -b/a, part below axis reflected',
        'Solve |f(x)| = g(x):',
        '  f(x) = g(x) or -f(x) = g(x),',
        '  check each answer in the original',
        '|f(x)| = |g(x)|: f = g or f = -g',
        'y = a^x (a > 0): through (0, 1),',
        '  asymptote y = 0',
        'Roots of f(x) = g(x) are the',
        '  x-coords where the graphs meet',
        'y proportional to x: y = kx',
        'y inversely proportional to x: y = k/x',
        'y prop. to x^n: y = kx^n, find k',
        '  from one known pair',
    ]),
    ('Graph transforms', [
        'y = f(x) + a: translate by (0, a)',
        'y = f(x + a): translate by (-a, 0)',
        'y = af(x): stretch, y-direction, sf a',
        'y = f(ax): stretch, x-direction, sf 1/a',
        'y = -f(x): reflect in the x-axis',
        'y = f(-x): reflect in the y-axis',
        'Changes inside f( ) act on x:',
        '  opposite of what they look like',
        'y = af(x) + b: stretch, then translate',
        'y = f(ax + b) = f(a(x + b/a)):',
        '  translate (-b, 0), then stretch 1/a',
        '  or stretch 1/a, then (-b/a, 0)',
        'y = |f(x)|: reflect parts below',
        '  the x-axis up',
        'y = f(|x|): keep x >= 0 part,',
        '  reflect it in the y-axis',
        'Track asymptotes and key points',
    ]),
    ('Functions', [
        'Function: each x gives exactly one y',
        'One-one: each y from only one x',
        'Domain: allowed inputs',
        'Range: resulting outputs',
        'fg(x) = f(g(x)): do g first',
        '  domain: x in domain of g with',
        '  g(x) in domain of f',
        'Inverse f^-1 exists only if f is',
        '  one-one (restrict the domain)',
        'Find f^-1: y = f(x), make x subject,',
        '  swap x and y',
        'Domain of f^-1 = range of f',
        'Range of f^-1 = domain of f',
        'f^-1 graph: reflect f in y = x',
        'ff^-1(x) = f^-1 f(x) = x',
        'f(x) = f^-1(x) solutions lie on y = x',
        '  (when f is increasing)',
        'Models: state domain, limitations',
    ]),
    ('Partial fractions', [
        '(px + q)/((ax + b)(cx + d))',
        '  = A/(ax + b) + B/(cx + d)',
        'Repeated factor:',
        '  ... /((ax + b)(cx + d)^2)',
        '  = A/(ax + b) + B/(cx + d)',
        '    + C/(cx + d)^2',
        'Improper (deg top >= deg bottom):',
        '  divide first',
        'Constants: substitute x = roots,',
        '  then compare coefficients',
        'Check: recombine or try x = 0',
        'Used for: integration, binomial',
        '  expansions, series sums',
    ]),
    ('Lines', [
        'm = (y2 - y1)/(x2 - x1)',
        'y - y1 = m(x - x1)',
        'ax + by + c = 0 (integers a, b, c)',
        'Parallel: m1 = m2',
        'Perpendicular: m1 m2 = -1',
        'Midpoint ((x1+x2)/2, (y1+y2)/2)',
        'Distance:',
        '  sqrt((x2 - x1)^2 + (y2 - y1)^2)',
        'Intersection: solve simultaneously',
        'Line models: gradient = rate,',
        '  intercept = start value',
    ]),
    ('Circles', [
        '(x - a)^2 + (y - b)^2 = r^2',
        '  centre (a, b), radius r',
        'x^2 + y^2 + 2gx + 2fy + c = 0:',
        '  centre (-g, -f)',
        '  r = sqrt(g^2 + f^2 - c)',
        '  (or complete the square)',
        'Angle in a semicircle = 90 deg',
        'Perpendicular from centre to a chord',
        '  bisects the chord',
        'Tangent is perpendicular to the',
        '  radius at that point',
        'Tangent at P: gradient -1/m(CP)',
        'Line and circle: substitute,',
        '  discriminant > 0 two points,',
        '  = 0 tangent, < 0 no meeting',
        'Circle through 3 points: centre is',
        '  where perp bisectors meet',
        'Right angle at C: AB is a diameter',
    ]),
    ('Parametric', [
        'x = f(t), y = g(t), t the parameter',
        'Cartesian: eliminate t',
        '  rearrange one and substitute, or',
        '  use sin^2 t + cos^2 t = 1 etc',
        'x = a cos t, y = a sin t: circle',
        '  x^2 + y^2 = a^2',
        'Domain of t restricts x and y:',
        '  give the domain of the cartesian',
        'dy/dx = (dy/dt)/(dx/dt)',
        'Area = int y dx = int y (dx/dt) dt,',
        '  limits in t',
        'Meets an axis: x = 0 or y = 0, find t',
        'Modelling: t often time, t >= 0',
    ]),
]
