# Notes: MEI H645 Statistics Major Y422, part 2 (bivariate data, tests,
# inference).
NOTES = [
    ('Bivariate data', [
        'Independent (explanatory) x,',
        '  dependent (response) y',
        'Controlled x: set by the',
        '  experimenter, not random',
        'Random on random: both vary',
        'Scatter: look for outliers by',
        '  eye, separate groups, non-linear',
        '  patterns',
        'Sxx = sum x^2 - (sum x)^2/n',
        'Syy = sum y^2 - (sum y)^2/n',
        'Sxy = sum xy - (sum x)(sum y)/n',
        'Correlation is not causation',
    ]),
    ('PMCC', [
        'r = Sxy/sqrt(Sxx Syy)',
        '-1 <= r <= 1; measures linear',
        '  association only',
        'Test needs a random sample from',
        '  a bivariate Normal population:',
        '  scatter roughly elliptical',
        'Effect size (Cohen): |r| about',
        '  0.1 small, 0.3 medium,',
        '  0.5 large',
        'r^2: proportion of variation in',
        '  y explained by the line',
        'Unchanged by coding (scaling,',
        '  shifting) x or y; a negative',
        '  scale factor flips the sign',
    ]),
    ('Spearman', [
        'Rank each variable (same order)',
        'd = difference in ranks',
        'rs = 1 - 6 sum d^2/(n(n^2 - 1))',
        '  (no ties)',
        'Ties: average ranks, then the',
        '  pmcc of the ranks',
        'Measures association (monotonic),',
        '  not just linear',
        'Use when: data are ranks, not',
        '  bivariate Normal, or non-linear',
        '  but monotonic',
        'Hypotheses in words:',
        '  H0: no association between ...',
        '  H1: positive association ...',
    ]),
    ('Correlation tests', [
        'pmcc: H0: rho = 0',
        '  H1: rho > 0, < 0 or != 0',
        '  rho: population pmcc',
        'Spearman: H0 no association,',
        '  H1 (positive / negative)',
        '  association in the population',
        'Critical value from tables for',
        '  n, level, tails',
        '|r| >= cv (sign as H1): reject H0',
        'Conclude in context: evidence of',
        '  positive correlation between',
        '  ... and ...',
        'Choose pmcc if bivariate Normal',
        '  (elliptical scatter), else',
        '  Spearman',
    ]),
    ('Regression', [
        'y on x: y - ybar = b(x - xbar)',
        '  b = Sxy/Sxx',
        '  minimises sum of squared',
        '  vertical residuals',
        'x on y: x - xbar = b2(y - ybar)',
        '  b2 = Sxy/Syy',
        'Both lines pass (xbar, ybar);',
        '  same line iff |r| = 1',
        'Residual = observed y - predicted y',
        'x controlled: use y on x only',
        'Both random: y on x to estimate y,',
        '  x on y to estimate x',
        'Interpolation fair; extrapolation',
        '  unreliable',
        'Residuals: big ones = poor fit',
        '  or outliers; pattern = wrong model',
    ]),
    ('Chi-sq association', [
        'H0: no association between A and',
        '  B; H1: some association',
        'E = row total * column total / grand total',
        'X^2 = sum (O - E)^2/E',
        'df = (rows - 1)(columns - 1)',
        'All E >= 5: else merge rows or',
        '  columns (then recount df)',
        'X^2 > critical value: reject H0',
        'Interpret: largest contributions',
        '  (O - E)^2/E; say where O is',
        '  more / less than E, in context',
        'Use frequencies, never',
        '  percentages',
    ]),
    ('Goodness of fit', [
        'H0: the model fits (e.g.',
        '  X ~ Po(lambda)); H1: it does not',
        'E = total * model probability',
        'Merge cells with E < 5',
        'df = cells - 1 - parameters',
        '  estimated from the data',
        '  Poisson lambda from xbar: -1',
        '  binomial p from data: -1',
        '  uniform, given values: none',
        'Last cell: "r or more" so the',
        '  probabilities sum to 1',
        'Small X^2: good fit; a very small',
        '  value can look too good',
    ]),
    ('Estimation, CLT', [
        'xbar: unbiased estimate of mu',
        's^2 = Sxx/(n - 1): unbiased',
        '  estimate of sigma^2',
        '  Sxx = sum x^2 - n xbar^2',
        'Xbar is a random variable:',
        '  mean mu, variance sigma^2/n',
        'Standard error of the mean:',
        '  sigma/sqrt(n) (or s/sqrt(n))',
        'Parent Normal: Xbar Normal',
        '  for any n',
        'CLT: n large (about 30+), any',
        '  parent with finite variance:',
        '  Xbar approximately Normal',
        'Random sample: unbiased, lets',
        '  probability theory apply',
    ]),
    ('Confidence intervals', [
        'xbar +- z sigma/sqrt(n)',
        '  90%: 1.645, 95%: 1.96,',
        '  99%: 2.576',
        'sigma unknown, n large: use s',
        'Small n, Normal parent, sigma',
        '  unknown: t with n - 1 df',
        'Meaning: in repeated samples,',
        '  95% of such intervals would',
        '  contain mu',
        'Width = 2z sigma/sqrt(n):',
        '  quadruple n to halve it',
        '  higher confidence: wider',
        'Paired data: differences d,',
        '  dbar +- z s_d/sqrt(n)',
        'mu0 outside a 95% CI: reject',
        '  H0: mu = mu0 at 5% (2-tail)',
    ]),
    ('Test for a mean', [
        'H0: mu = mu0; H1: <, > or !=',
        'z = (xbar - mu0)/(sigma/sqrt(n))',
        '  (s for sigma if n large)',
        'Critical z (1-tail / 2-tail):',
        '  10%: 1.282 / 1.645',
        '  5%: 1.645 / 1.960',
        '  1%: 2.326 / 2.576',
        'Or p-value <= level: reject',
        'Assume: random sample; Normal',
        '  parent or n large (CLT)',
        'Paired: test the differences,',
        '  H0: mu_d = 0',
        'Samples paired when each value',
        '  in one matches one in the other',
        '  (same subject, before / after)',
    ]),
    ('Wilcoxon signed rank', [
        'Single sample, H0: median = m0',
        'Assume: random sample, symmetric',
        '  population (no Normality)',
        '1 d = x - m0; drop d = 0, cut n',
        '2 rank |d|, ties: average rank',
        '3 W+ = sum of ranks of d > 0,',
        '  W- = sum of ranks of d < 0',
        '  check W+ + W- = n(n + 1)/2',
        '4 T = W+ or W- as H1 says:',
        '  H1 median > m0: T = W-',
        '  H1 median < m0: T = W+',
        '  2-tail: T = smaller of the two',
        '5 T <= critical value: reject H0',
        'Paired: d = x - y,',
        '  H0: median difference = 0',
        'Use when Normality is doubtful',
    ]),
    ('Test essentials', [
        'Hypotheses about the population',
        '  parameter: mu, p, rho, median;',
        '  define it in context',
        'H0 has =, H1 sets the tail',
        'Decide tails and level before',
        '  seeing the data',
        'Significance level: P(reject H0',
        '  when H0 is true)',
        'p-value <= level: reject H0',
        'Wording: "sufficient evidence at',
        '  the 5% level to suggest ..."',
        '  never "proves" or "H0 is true"',
        'State assumptions; comment on',
        '  sample (random? size?)',
    ]),
    ('Sampling, simulation', [
        'Why sample: population too big,',
        '  testing destroys items, cost,',
        '  time',
        'Random sample: every member',
        '  equally likely, independent;',
        '  avoids bias, allows inference',
        'Bigger sample: smaller standard',
        '  error, narrower CI, more likely',
        '  to detect a real effect',
        'Simulation: random numbers model',
        '  the distribution; repeat many',
        '  times; relative frequency',
        '  estimates probability',
        'More runs: better estimate',
        'Spreadsheets: RAND(), sums,',
        '  frequency tables',
    ]),
]
