# Notes: AQA 7357 Pure, part 3 (calculus, numerical methods, vectors).
NOTES = [
    ('Derivative basics', [
        'dy/dx: gradient of the tangent,',
        '  rate of change of y with x',
        "f'(x) = lim_(h->0) (f(x+h) - f(x))/h",
        'First principles x^n: expand',
        '  (x + h)^n, cancel, divide by h,',
        '  then h -> 0',
        'First principles sin x, cos x:',
        '  sin h/h -> 1, (cos h - 1)/h -> 0',
        'd/dx x^n = n x^(n-1), n rational',
        'd/dx (constant) = 0',
        'Write roots and 1/x^n as powers',
        '  before differentiating',
        "f''(x): rate of change of gradient",
        "Increasing f'(x) > 0 (or >= 0)",
        "Decreasing f'(x) < 0 (or <= 0)",
        'Sketch gradient function: zeros',
        '  of f\' at turning points of f',
    ]),
    ('Standard derivatives', [
        'Angles in radians for all of these',
        'e^(kx) -> k e^(kx)',
        'a^x -> a^x ln a',
        'ln x -> 1/x, ln(kx) -> 1/x',
        'sin kx -> k cos kx',
        'cos kx -> -k sin kx',
        'tan kx -> k sec^2 kx',
        'sec x -> sec x tan x',
        'cosec x -> -cosec x cot x',
        'cot x -> -cosec^2 x',
        'e^(f(x)) -> f\'(x) e^(f(x))',
        "ln f(x) -> f'(x)/f(x)",
        '(f(x))^n -> n f\'(x) (f(x))^(n-1)',
        'sin(f(x)) -> f\'(x) cos(f(x))',
        'y = arcsin x: x = sin y, find',
        '  dx/dy, then dy/dx = 1/(dx/dy)',
    ]),
    ('Product, chain rule', [
        'Chain: dy/dx = (dy/du)(du/dx)',
        "Product: (uv)' = u'v + uv'",
        "Quotient: (u/v)' = (u'v - uv')/v^2",
        'dx/dy = 1/(dy/dx)',
        'x = f(y): find dx/dy, then flip',
        'Connected rates of change:',
        '  dV/dt = (dV/dr)(dr/dt)',
        '  write each rate, units per time',
        '  increasing: positive rate',
        'Inverse function: y = f^-1(x)',
        '  means x = f(y), dy/dx = 1/(dx/dy)',
        'Simplify: factorise common factors',
        '  (e^x, powers of a bracket)',
    ]),
    ('Stationary points', [
        "Tangent at x = a: y - f(a) = f'(a)(x - a)",
        "Normal: gradient -1/f'(a)",
        "Stationary: f'(x) = 0",
        "f''(x) > 0: minimum",
        "f''(x) < 0: maximum",
        "f''(x) = 0: test fails, check the",
        "  sign of f' either side",
        "Point of inflection: f'' changes sign",
        '  (not just f\'\' = 0)',
        "Stationary inflection: f' = 0 too,",
        "  f' same sign either side",
        "Convex: f''(x) > 0 (curves up)",
        "Concave: f''(x) < 0",
        'Optimisation: write the quantity',
        '  in one variable, differentiate,',
        '  = 0, justify max or min',
        'Check end points of a domain too',
    ]),
    ('Implicit, parametric', [
        'Implicit: differentiate each term',
        '  in x; a y term gets a factor dy/dx',
        'd/dx (y^n) = n y^(n-1) dy/dx',
        'd/dx (xy) = y + x dy/dx',
        'd/dx f(y) = f\'(y) dy/dx',
        'Collect dy/dx terms, factorise',
        'Stationary: dy/dx = 0, i.e.',
        '  numerator = 0, then use the curve',
        'Vertical tangent: denominator 0',
        'Parametric:',
        '  dy/dx = (dy/dt)/(dx/dt)',
        '  tangent at t: find x, y, gradient',
        '  stationary: dy/dt = 0',
        'AQA: first derivatives only here',
    ]),
    ('Integration', [
        'int x^n dx = x^(n+1)/(n+1) + c',
        '  n != -1',
        'int 1/x dx = ln|x| + c',
        'int e^(kx) dx = (1/k)e^(kx) + c',
        'int sin kx dx = -(1/k)cos kx + c',
        'int cos kx dx = (1/k)sin kx + c',
        'int sec^2 kx dx = (1/k)tan kx + c',
        "int f'(x)/f(x) dx = ln|f(x)| + c",
        "int f'(x)e^(f(x)) dx = e^(f(x)) + c",
        "int f'(x)(f(x))^n dx",
        '  = (f(x))^(n+1)/(n + 1) + c',
        'int (ax + b)^n dx',
        '  = (ax + b)^(n+1)/(a(n + 1)) + c',
        'int 1/(ax + b) dx = (1/a)ln|ax + b| + c',
        '+ c on every indefinite integral',
        'Radians for trig',
        'sin^2 x = (1 - cos 2x)/2,',
        '  cos^2 x = (1 + cos 2x)/2',
        'tan^2 x = sec^2 x - 1',
        'More standard integrals: booklet',
    ]),
    ('Definite integrals', [
        "Fundamental theorem:",
        "  int_a^b f'(x) dx",
        '  = f(b) - f(a)',
        'Area between curve and x-axis:',
        '  int_a^b y dx',
        'Below the axis: integral negative',
        '  split at the roots, add the sizes',
        'Between two curves:',
        '  int (top - bottom) dx',
        '  limits at the intersections',
        'Area with the y-axis: int x dy',
        'Limit of a sum:',
        '  sum of y dx as dx -> 0 = int y dx',
        'ln limits: ln b - ln a = ln(b/a)',
        'Exact answers: keep ln, e, pi',
    ]),
    ('Integration methods', [
        'Substitution:',
        '1 choose u (often inside a bracket',
        '  or root), find du/dx',
        '2 replace dx by du/(du/dx)',
        '3 change the limits to u',
        '4 integrate in u; indefinite:',
        '  substitute back to x',
        'By parts: int u v\' = uv - int u\'v',
        'Choose u to get simpler when',
        '  differentiated:',
        '  ln x first, then powers of x,',
        '  then trig / e^x',
        'int ln x dx: u = ln x, v\' = 1',
        '  = x ln x - x + c',
        'x^2 e^x: parts twice',
        'e^x sin x: parts twice, the',
        '  integral reappears: solve for it',
        'Partial fractions (linear factors):',
        '  int A/(ax + b) dx = (A/a)ln|ax + b|',
    ]),
    ('Differential equations', [
        'Separable: dy/dx = f(x)g(y)',
        '  int 1/g(y) dy = int f(x) dx',
        '  one + c, on one side',
        'Particular solution: put in the',
        '  given values to find c',
        'General solution: still has c',
        'Rate proportional to P:',
        '  dP/dt = kP (k > 0 grows)',
        'Decreasing at a rate: minus sign',
        'Inversely proportional: k/P',
        'Solve for y: ln|y| = ... gives',
        '  y = A e^(...), A = +-e^c',
        'Interpret: long-term value,',
        '  t -> infinity, units, limits of',
        '  the model, when it breaks down',
        'Kinematics: v = dx/dt, a = dv/dt',
    ]),
    ('Roots: sign change', [
        'f continuous on [a, b] and',
        '  f(a), f(b) of opposite sign:',
        '  a root lies between a and b',
        'Fails when:',
        '  f not continuous (asymptote,',
        '  e.g. 1/x changes sign at 0)',
        '  repeated root / touching axis',
        '  even number of roots in interval',
        '  interval too wide',
        'Show a root is 1.23 to 2 d.p.:',
        '  sign change over [1.225, 1.235]',
        'Write: f(a) < 0, f(b) > 0,',
        '  sign change and f continuous,',
        '  so root in (a, b)',
    ]),
    ('Iteration, N-R', [
        'Iteration x_(n+1) = g(x_n):',
        '  rearrange f(x) = 0 to x = g(x)',
        "  converges if |g'(x)| < 1 near root",
        '  diverges if |g\'(x)| > 1',
        "  staircase if g'(x) > 0,",
        "  cobweb if g'(x) < 0",
        'Newton-Raphson:',
        "  x_(n+1) = x_n - f(x_n)/f'(x_n)",
        "  fails if f'(x_n) = 0 or near 0",
        '  (stationary point nearby)',
        '  start far away: wrong root or',
        '  divergence',
        '  tangent meets the x-axis at',
        '  the next estimate',
        'State answers to the accuracy',
        '  asked; check with a sign change',
    ]),
    ('Trapezium rule', [
        'h = (b - a)/n, n strips,',
        '  n + 1 ordinates',
        'Area ~ (h/2)(y_0 + 2(y_1 + ... + y_(n-1)) + y_n)',
        "Overestimate if convex (f'' > 0)",
        "Underestimate if concave (f'' < 0)",
        'More strips: better estimate',
        'Bounds: rectangles of height the',
        '  least / greatest value on each',
        '  strip; true area lies between',
        'Radians for trig functions',
    ]),
    ('Vectors', [
        'a = xi + yj + zk = (x, y, z)',
        '|a| = sqrt(x^2 + y^2 + z^2)',
        'Unit vector: a/|a|',
        'AB = b - a (position vectors)',
        'Distance AB = |b - a|',
        'Midpoint: (a + b)/2',
        'P divides AB in ratio m:n:',
        '  p = (na + mb)/(m + n)',
        'Parallel: a = kb',
        'Collinear A, B, C: AB = k BC',
        '  (shared point B)',
        '2D direction: tan theta = y/x,',
        '  check the quadrant',
        'Magnitude r, direction theta:',
        '  (r cos theta, r sin theta)',
        'Resultant: add components',
        'Parallelogram ABCD: AB = DC',
    ]),
]
