# Notes: AQA 7357 Statistics.
NOTES = [
    ('Sampling', [
        'Population: everything of interest',
        'Sample: a subset of the population',
        'Census: the whole population',
        'Sampling frame: list of the',
        '  population to choose from',
        'Simple random: every sample of size',
        '  n equally likely; number the',
        '  frame, random numbers',
        'Systematic: every kth from a',
        '  random start, k = N/n',
        'Stratified: random within groups,',
        '  in proportion to group sizes',
        'Quota: fill set numbers per group,',
        '  not random (cheap, may be biased)',
        'Opportunity: whoever is available;',
        '  quick, likely unrepresentative',
        'Cluster: random whole groups',
        'Different samples give different',
        '  conclusions; bigger samples are',
        '  more reliable',
    ]),
    ('Averages and spread', [
        'Mean xbar = sum x/n',
        '  grouped: sum fx/sum f, midpoints',
        'Median: middle value; grouped:',
        '  interpolate in the median class',
        'Mode / modal class',
        'Range, IQR = Q3 - Q1',
        'Sxx = sum x^2 - (sum x)^2/n',
        'Variance = Sxx/n',
        '  = sum x^2/n - xbar^2',
        'sd = sqrt(variance)',
        'Divisor n; AQA also accepts n - 1',
        'Coding y = (x - a)/b:',
        '  ybar = (xbar - a)/b',
        '  sd of y = (sd of x)/|b|',
        'Adding a constant: sd unchanged',
        'Outliers affect mean, sd, range;',
        '  median and IQR are resistant',
    ]),
    ('Diagrams and outliers', [
        'Histogram: area = frequency',
        '  frequency density =',
        '  frequency / class width',
        'Box plot: min, Q1, median, Q3, max',
        'Cumulative frequency: plot at',
        '  upper class boundaries',
        'Outlier rules (use the one given):',
        '  < Q1 - 1.5 IQR or > Q3 + 1.5 IQR',
        '  more than 2 sd (or 3) from mean',
        'Skew: positive if tail to the',
        '  right (mean > median)',
        'Cleaning data: remove errors,',
        '  impossible values; deal with',
        '  missing data; justify removing',
        '  outliers (error or genuine?)',
        'Compare: an average and a spread,',
        '  in context',
    ]),
    ('Correlation', [
        'Scatter: positive, negative, none',
        'r near +1 or -1: points close to a',
        '  straight line; r near 0: no',
        '  linear correlation',
        'Correlation does not imply',
        '  causation',
        'Explanatory (independent) variable',
        '  on the x-axis',
        'Distinct groups in the scatter:',
        '  analyse each separately',
        'Interpolation: fairly reliable',
        'Extrapolation: unreliable',
        'AQA: r is given, not calculated',
    ]),
    ('Probability', [
        "P(A') = 1 - P(A)",
        'P(A \\cup B) = P(A) + P(B) - P(A \\cap B)',
        'Mutually exclusive:',
        '  P(A \\cap B) = 0',
        '  P(A \\cup B) = P(A) + P(B)',
        'Independent:',
        '  P(A \\cap B) = P(A) P(B)',
        '  P(A|B) = P(A)',
        'Conditional:',
        '  P(A|B) = P(A \\cap B)/P(B)',
        'Tree: multiply along branches,',
        '  add the end results',
        '  second branches are conditional',
        'Venn / two-way table: count, then',
        '  divide by the right total',
        'Without replacement: denominators',
        '  drop by 1',
        'Exhaustive: probabilities sum to 1',
        'Modelling: state assumptions',
        '  (independence, equally likely),',
        '  say how real data may differ',
    ]),
    ('Binomial', [
        'X ~ B(n, p) when:',
        '  fixed number of trials n',
        '  two outcomes (success / failure)',
        '  trials independent',
        '  constant probability p',
        'P(X = r) = nCr p^r (1-p)^(n-r)',
        'P(X <= r): binomial cdf',
        'P(X < r) = P(X <= r - 1)',
        'P(X >= r) = 1 - P(X <= r - 1)',
        'P(X > r) = 1 - P(X <= r)',
        'P(a <= X <= b)',
        '  = P(X <= b) - P(X <= a - 1)',
        'Mean np, variance np(1 - p)',
        'Any discrete distribution:',
        '  sum of P(X = x) = 1 (find k)',
        'Critique: are trials independent?',
        '  is p really constant?',
    ]),
    ('Normal distribution', [
        'X ~ N(mu, sigma^2): continuous,',
        '  symmetric, bell-shaped',
        '  mean = median = mode',
        'Points of inflection at',
        '  mu - sigma and mu + sigma',
        '68% within 1 sd, 95% within 2,',
        '  99.7% within 3',
        'Z = (X - mu)/sigma ~ N(0, 1)',
        'P(X = a) = 0, so < and <= same',
        'Mean of n from N(mu, sigma^2):',
        '  Xbar ~ N(mu, sigma^2/n)',
        'Unknown mu or sigma: inverse',
        '  normal for z, then',
        '  (x - mu)/sigma = z; two unknowns:',
        '  simultaneous equations',
        'Use: continuous data, symmetric,',
        '  roughly bell-shaped histogram',
        'Check: mu +- 3 sigma within the',
        '  possible values',
    ]),
    ('Normal approx to B', [
        'B(n, p) ~ N(np, np(1 - p)) when',
        '  n large, p near 0.5',
        '  (np > 5 and n(1 - p) > 5)',
        'Continuity correction:',
        '  P(X <= 6) -> P(Y < 6.5)',
        '  P(X < 6) -> P(Y < 5.5)',
        '  P(X >= 6) -> P(Y > 5.5)',
        '  P(X = 6) -> P(5.5 < Y < 6.5)',
    ]),
    ('Choosing a model', [
        'Binomial: counts of successes in',
        '  n independent trials, constant p',
        'Normal: continuous, symmetric,',
        '  most data within mu +- 3 sigma',
        'Not Normal: skewed, bounded,',
        '  or discrete with few values',
        'Not binomial: p changes,',
        '  dependent trials, no fixed n',
        'Give reasons in context',
        'Model fits: compare predicted',
        '  with observed frequencies',
    ]),
    ('Hypothesis testing', [
        'H0: p = p0 (always =)',
        'H1: p < p0 or p > p0 (1-tail),',
        '  p != p0 (2-tail)',
        'Test statistic X ~ B(n, p0)',
        '  assuming H0 is true',
        'Significance level alpha:',
        '  P(reject H0 | H0 true)',
        'Critical region: values where H0',
        '  is rejected; P(X in CR) <= alpha,',
        '  as close as possible',
        '2-tail: alpha/2 in each tail',
        'Acceptance region: the rest',
        'Actual significance level:',
        '  P(X in CR) when H0 true',
        'p-value: P(observed or more',
        '  extreme); reject H0 if <= alpha',
        '  (2-tail: compare with alpha/2)',
    ]),
    ('Test conclusions', [
        'Reject H0: there is sufficient',
        '  evidence at the 5% level to',
        '  suggest that p > 0.3 (context)',
        'Do not reject H0: insufficient',
        '  evidence to suggest ...',
        'Never "H0 is true" / "proves"',
        'Define p: the proportion of ...',
        '  in the population',
        'Sample used to infer about the',
        '  population; alpha is the chance',
        '  of wrongly rejecting H0',
        'Decide the test before seeing data',
    ]),
    ('Normal mean test', [
        'H0: mu = mu0; H1: mu <, >, != mu0',
        'sigma known (given or assumed),',
        '  population Normal',
        'Under H0: Xbar ~ N(mu0, sigma^2/n)',
        'z = (xbar - mu0)/(sigma/sqrt(n))',
        'Critical z, 1-tail / 2-tail:',
        '  10%: 1.2816 / 1.6449',
        '  5%: 1.6449 / 1.9600',
        '  1%: 2.3263 / 2.5758',
        'Or: p-value = P(Xbar >= xbar)',
        '  (or <=), compare with alpha',
        'Conclude in context, about mu',
    ]),
    ('Correlation test', [
        'rho: population pmcc',
        'H0: rho = 0',
        'H1: rho > 0, rho < 0 (1-tail)',
        '  or rho != 0 (2-tail)',
        'Compare r with the critical value',
        '  for n and alpha (table given)',
        '  1-tail: r beyond cv on the H1',
        '  side (r >= cv for rho > 0);',
        '  2-tail: |r| >= cv; reject H0',
        'Or given p-value <= alpha:',
        '  reject H0',
        'Conclusion: sufficient evidence of',
        '  positive correlation between',
        '  ... and ... in the population',
    ]),
]
