# Notes: MEI H645 Core Pure Y420, part 1 (proof, complex numbers, roots).
NOTES = [
    ('Induction', [
        '1 Basis: show true for n = 1',
        '2 Assume true for n = k',
        '3 Show true for n = k + 1, using',
        '  the assumption',
        '4 Conclude: true for n = 1; if true',
        '  for n = k then true for n = k + 1;',
        '  so true for all n >= 1',
        'Sums: S(k+1) = S(k) + (k+1)th term',
        'Divisibility: f(k+1) - m f(k) is a',
        '  multiple of d, or write f(k) = dA',
        'Matrices: M^(k+1) = M^k M',
        'Sequences: use u_(k+1) = g(u_k)',
        'Also: other proofs by deduction,',
        '  exhaustion, contradiction,',
        '  counter-example',
    ]),
    ('Complex numbers', [
        'i^2 = -1; z = x + yi',
        'Re z = x, Im z = y (both real)',
        'z* = x - yi (conjugate)',
        'z z* = x^2 + y^2 = |z|^2',
        'z + z* = 2 Re z',
        'Divide: times top and bottom by',
        '  the conjugate of the bottom',
        'Equal: real parts equal and',
        '  imaginary parts equal',
        'z = 0 iff x = 0 and y = 0',
        'Square root of a + bi: (x + yi)^2,',
        '  equate parts, solve',
        'Real quadratic, b^2 - 4ac < 0:',
        '  roots p +- qi (conjugates)',
    ]),
    ('Mod-arg form', [
        '|z| = r = sqrt(x^2 + y^2)',
        'arg z = theta, -pi < theta <= pi',
        '  tan theta = y/x: check quadrant',
        '  (sketch the point first)',
        'z = r(cos theta + i sin theta)',
        'z = r e^(i theta)',
        'e^(i theta) = cos theta + i sin theta',
        '|z1 z2| = |z1| |z2|',
        'arg(z1 z2) = arg z1 + arg z2',
        '|z1/z2| = |z1|/|z2|',
        'arg(z1/z2) = arg z1 - arg z2',
        '  add/subtract 2pi to stay in range',
        'Radians throughout',
    ]),
    ('Argand diagram', [
        'z = x + yi at the point (x, y)',
        'z1 + z2: parallelogram (vector) sum',
        'z1 - z2: vector from z2 to z1',
        '|z1 - z2|: distance between them',
        'z*: reflection in the real axis',
        'Times r e^(i theta): enlarge by',
        '  r, rotate theta anticlockwise',
        'Times i: rotate pi/2 anticlockwise',
        'Regular polygon centre c, vertex',
        '  v: next vertex',
        '  c + (v - c) e^(2pi i/n)',
    ]),
    ('Loci', [
        '|z - a| = r: circle, centre a,',
        '  radius r',
        '|z - a| = |z - b|: perpendicular',
        '  bisector of a and b',
        'arg(z - a) = theta: half-line from',
        '  a at angle theta (a excluded)',
        '|z - a| < r: inside the circle',
        '|z - a| < |z - b|: half-plane on',
        '  the side of a',
        'alpha < arg(z - a) < beta: sector',
        'Strict < > : boundary dashed',
        '<= >= : boundary solid',
        'Max / min |z| on a circle:',
        '  line through the origin and',
        '  the centre: max |c| + r,',
        '  min ||c| - r|',
    ]),
    ('Roots and coefficients', [
        'ax^2 + bx + c = 0:',
        '  alpha + beta = -b/a',
        '  alpha beta = c/a',
        'ax^3 + bx^2 + cx + d = 0:',
        '  sum alpha = -b/a',
        '  sum alpha beta = c/a',
        '  alpha beta gamma = -d/a',
        'Quartic ax^4 + ... + e:',
        '  -b/a, c/a, -d/a, e/a',
        'alpha^2 + beta^2 + gamma^2',
        '  = (sum alpha)^2 - 2 sum alpha beta',
        'Sum 1/alpha = (sum alpha beta)',
        '  / (alpha beta gamma)',
        'Real coefficients: non-real roots',
        '  come in conjugate pairs',
        'Cubic: at least one real root',
        'Factor from a root pair p +- qi:',
        '  x^2 - 2px + (p^2 + q^2)',
    ]),
    ('Related roots', [
        'New roots w related to old x:',
        '  write x in terms of w, substitute',
        '  into the old equation, tidy',
        'w = 2 alpha: x = w/2',
        'w = alpha + k: x = w - k',
        'w = 1/alpha: x = 1/w',
        'w = alpha^2: x = sqrt(w), then',
        '  collect odd powers and square',
        'Multiply through to clear',
        '  fractions; integer coefficients',
        'Or: find new sum, pair sum,',
        '  product from the old ones',
    ]),
    ("De Moivre", [
        '(cos theta + i sin theta)^n',
        '  = cos n theta + i sin n theta',
        '(r e^(i theta))^n = r^n e^(i n theta)',
        'z = e^(i theta):',
        '  z + 1/z = 2cos theta',
        '  z - 1/z = 2i sin theta',
        '  z^n + z^-n = 2cos n theta',
        '  z^n - z^-n = 2i sin n theta',
        'cos n theta in powers of cos:',
        '  expand (c + is)^n binomially,',
        '  take the real part,',
        '  replace s^2 = 1 - c^2',
        'sin n theta: imaginary part',
        'tan n theta: Im/Re, divide by cos^n',
        'cos^n theta in multiple angles:',
        '  (z + 1/z)^n = 2^n cos^n theta,',
        '  pair up z^k + z^-k',
    ]),
    ('nth roots', [
        'z^n = r e^(i theta) has n roots:',
        '  r^(1/n) e^(i(theta + 2k pi)/n)',
        '  k = 0, 1, ..., n - 1',
        'Roots lie on a circle radius',
        '  r^(1/n), equally spaced 2pi/n',
        '  (regular n-gon)',
        'Roots of unity: z^n = 1,',
        '  z = e^(2k pi i/n)',
        '  1, w, w^2, ..., w^(n-1),',
        '  w = e^(2pi i/n)',
        'Sum of the n roots = 0 (n >= 2):',
        '  1 + w + ... + w^(n-1)',
        '  = (w^n - 1)/(w - 1) = 0',
        'Give args in -pi < theta <= pi',
        '  if asked for principal values',
    ]),
]
