# Notes: AQA 7357 Pure, part 2 (series, trigonometry, exponentials and logs).
NOTES = [
    ('Binomial expansion', [
        '(a + b)^n, n a positive integer:',
        '  n + 1 terms, exact',
        'nCr = n!/(r!(n - r)!), 0! = 1',
        'Term in x^r of (a + bx)^n:',
        '  nCr a^(n-r) (bx)^r',
        'Coefficients: Pascal, or nCr',
        '(1 + x)^n, n negative or fraction:',
        '  infinite series, valid |x| < 1',
        '(1 + bx)^n valid for |bx| < 1,',
        '  so |x| < 1/|b|',
        '(a + bx)^n = a^n (1 + (b/a)x)^n',
        '  valid for |x| < |a/b|',
        'Two expansions multiplied: valid',
        '  where both are (narrower range)',
        'Approximation: substitute a small x',
        '  that is inside the valid range',
        'Partial fractions first, then',
        '  expand each fraction',
        'Link: B(n, p) probabilities are',
        '  terms of (q + p)^n',
    ]),
    ('Sequences', [
        'nth term u_n = f(n)',
        'Recurrence u_(n+1) = f(u_n), u_1 given',
        'Increasing: u_(n+1) > u_n for all n',
        'Decreasing: u_(n+1) < u_n for all n',
        'Periodic: u_(n+k) = u_n, order k',
        '  (smallest such k)',
        'Converges: terms approach a limit L',
        '  limit of u_(n+1) = f(u_n):',
        '  solve L = f(L)',
        'Sigma: sum of f(r), r = 1 to n',
        '  has n terms',
        '  sum of 1 for r = 1 to n is n',
        '  r = k to n has n - k + 1 terms',
        'Sequence: list of terms',
        'Series: sum of terms',
    ]),
    ('Arithmetic series', [
        'Common difference d',
        'u_n = a + (n - 1)d',
        'S_n = n/2 (2a + (n - 1)d)',
        'S_n = n/2 (a + l), l = last term',
        '1 + 2 + ... + n = n(n + 1)/2',
        'Three terms in AP: b - a = c - b',
        'Unknowns a, d: two equations,',
        '  solve simultaneously',
        'n must be a positive integer',
    ]),
    ('Geometric series', [
        'Common ratio r = u_(n+1)/u_n',
        'u_n = a r^(n - 1)',
        'S_n = a(1 - r^n)/(1 - r)',
        '  (r != 1)',
        'Converges iff |r| < 1:',
        'S_inf = a/(1 - r)',
        'Three terms in GP: b/a = c/b',
        'Least n with S_n > k etc:',
        '  take logs; dividing by ln r < 0',
        '  (0 < r < 1) flips the inequality',
        'Compound growth: P r^n',
        '  r = 1 + rate, e.g. 1.05 for 5%',
        'n is an integer: round correctly',
        '  (up for least n)',
    ]),
    ('Radians and triangles', [
        'pi rad = 180 deg, 1 rad = 57.3 deg',
        'Arc length s = r theta',
        'Sector area = (1/2)r^2 theta',
        'Segment = (1/2)r^2(theta - sin(theta))',
        '  theta in radians',
        'Sine rule: a/sin A = b/sin B',
        '  = c/sin C',
        'Ambiguous case (given two sides and',
        '  a non-included angle): angle',
        '  B or 180 deg - B, check both',
        'Cosine rule:',
        '  a^2 = b^2 + c^2 - 2bc cos A',
        '  cos A = (b^2 + c^2 - a^2)/(2bc)',
        'Area = (1/2)ab sin C',
        'Bearings: clockwise from north,',
        '  three figures',
    ]),
    ('Exact values', [
        'Angles 0, 30, 45, 60, 90 deg:',
        'sin: 0, 1/2, sqrt 2/2, sqrt 3/2, 1',
        'cos: 1, sqrt 3/2, sqrt 2/2, 1/2, 0',
        'tan: 0, sqrt 3/3, 1, sqrt 3, undefined',
        '1/sqrt 2 = sqrt 2/2',
        '1/sqrt 3 = sqrt 3/3',
        'rad: 30 = pi/6, 45 = pi/4,',
        '  60 = pi/3, 90 = pi/2',
        '  120 = 2pi/3, 135 = 3pi/4',
        '  150 = 5pi/6, 180 = pi',
        '  270 = 3pi/2, 360 = 2pi',
        'tan 90 undefined (asymptote)',
        'sin 180 = 0, cos 180 = -1',
        'sin 270 = -1, cos 270 = 0',
    ]),
    ('Trig graphs', [
        'Unit circle: point at angle theta',
        '  is (cos theta, sin theta); defines',
        '  sin, cos for any angle',
        'sin, cos period 2pi (360 deg)',
        'tan period pi, asymptotes at',
        '  x = pi/2 + k pi',
        '-1 <= sin x <= 1, -1 <= cos x <= 1',
        'sin(pi - x) = sin x',
        'cos(-x) = cos x (even)',
        'sin(-x) = -sin x (odd)',
        'cos(2pi - x) = cos x',
        'tan(pi + x) = tan x',
        'sin(x + pi/2) = cos x',
        'cos(x - pi/2) = sin x',
        'CAST: positive in quadrant',
        '  1 all, 2 sin, 3 tan, 4 cos',
        'Small angles (radians):',
        '  sin x ~ x, tan x ~ x',
        '  cos x ~ 1 - x^2/2',
    ]),
    ('Sec, cosec, cot', [
        'sec x = 1/cos x',
        'cosec x = 1/sin x',
        'cot x = 1/tan x = cos x/sin x',
        'sec: period 2pi, |y| >= 1,',
        '  asymptotes x = pi/2 + k pi',
        'cosec: period 2pi, |y| >= 1,',
        '  asymptotes x = k pi',
        'cot: period pi,',
        '  asymptotes x = k pi',
        'sec^2 x = 1 + tan^2 x',
        'cosec^2 x = 1 + cot^2 x',
        'sec x is even, cosec and cot odd',
    ]),
    ('Inverse trig', [
        'arcsin: domain -1 <= x <= 1',
        '  range -pi/2 <= y <= pi/2',
        'arccos: domain -1 <= x <= 1',
        '  range 0 <= y <= pi',
        'arctan: domain all real x',
        '  range -pi/2 < y < pi/2',
        '  asymptotes y = +-pi/2',
        'Graph: reflect the restricted',
        '  trig graph in y = x',
        'sin(arcsin x) = x for |x| <= 1',
        'arcsin(sin x) = x only for',
        '  -pi/2 <= x <= pi/2',
        'Calculator gives only the',
        '  principal value',
    ]),
    ('Trig identities', [
        'tan x = sin x/cos x',
        'sin^2 x + cos^2 x = 1',
        'sec^2 x = 1 + tan^2 x',
        'cosec^2 x = 1 + cot^2 x',
        'sin 2A = 2 sin A cos A',
        'cos 2A = cos^2 A - sin^2 A',
        '  = 2cos^2 A - 1 = 1 - 2sin^2 A',
        'tan 2A = (2tan A)/(1 - tan^2 A)',
        'cos^2 A = (1 + cos 2A)/2',
        'sin^2 A = (1 - cos 2A)/2',
        'sin(A +- B), cos(A +- B),',
        '  tan(A +- B): in the booklet',
        'Proving A = B: start with one side',
        '  (the messier one), reach the other',
        '  write LHS = ... = RHS',
        'Do not work on both sides at once',
        'Tactics: write in sin and cos,',
        '  common denominator, factorise,',
        '  use sin^2 + cos^2 = 1',
    ]),
    ('R cos / R sin form', [
        'a sin x + b cos x = R sin(x + alpha)',
        'a sin x - b cos x = R sin(x - alpha)',
        'a cos x + b sin x = R cos(x - alpha)',
        'a cos x - b sin x = R cos(x + alpha)',
        '  (a, b > 0)',
        'R = sqrt(a^2 + b^2)',
        'tan alpha = b/a, 0 < alpha < pi/2',
        'Method: expand R sin(x + alpha),',
        '  match: R cos alpha = a,',
        '  R sin alpha = b',
        'Max R, min -R; find x where',
        '  the bracket = pi/2 (sin max) etc',
        'Solve = k: sin(x + alpha) = k/R,',
        '  shift the interval by alpha',
    ]),
    ('Solving trig eqns', [
        '1 rearrange to sin(...) = k etc',
        '2 principal value (calculator)',
        '3 second value by symmetry:',
        '  sin: pi - x, cos: 2pi - x (or -x),',
        '  tan: x + pi',
        '4 add/subtract periods to fill',
        '  the interval',
        'sin 2x in 0 <= x < 2pi:',
        '  solve 2x in 0 <= 2x < 4pi,',
        '  then halve',
        'sin(x + a): shift the interval by a',
        'Do not divide by sin x or cos x:',
        '  factorise, or lose solutions',
        'Quadratic in sin: factorise,',
        '  reject |sin x| > 1',
        'Mixed: use identities to get',
        '  one function only',
        'Squared both sides: check answers',
        'Degrees or radians: as the',
        '  interval is given',
    ]),
    ('Exponentials and logs', [
        'a^x > 0 for all x (a > 0)',
        'y = a^x through (0, 1)',
        'd/dx e^(kx) = k e^(kx): gradient',
        '  proportional to the value',
        'log_a x = y <=> a^y = x',
        'log_a 1 = 0, log_a a = 1',
        'log x + log y = log(xy)',
        'log x - log y = log(x/y)',
        'k log x = log(x^k)',
        'log(1/x) = -log x',
        'ln x = log_e x, needs x > 0',
        'e^(ln x) = x, ln(e^x) = x',
        'a^x = b: x = ln b/ln a',
        'a^x = e^(x ln a)',
        'log_a b = ln b/ln a',
        'ln(x + y) != ln x + ln y',
        'Check solutions: log of a',
        '  negative or zero is undefined',
    ]),
    ('Log graphs, models', [
        'y = ax^n: log y = log a + n log x',
        '  plot log y against log x:',
        '  gradient n, intercept log a',
        'y = kb^x: log y = log k + x log b',
        '  plot log y against x:',
        '  gradient log b, intercept log k',
        'Read a and k: a = 10^intercept',
        '  (or e^intercept for ln)',
        'Growth/decay: N = N0 e^(kt)',
        '  k > 0 growth, k < 0 decay',
        '  N0 = value at t = 0',
        'Half-life T: e^(kT) = 1/2,',
        '  T = ln 2/|k|',
        'Continuous compound interest:',
        '  A = P e^(rt), r the rate',
        'Limits: unbounded growth is',
        '  unrealistic; long-term value,',
        '  refine the model (add a limit)',
    ]),
]
