# Cases for ffpt (MEI H645 Further Pure with Technology, Y436). Every tool has
# at least one case; branchy tools have one per branch. Numbers checked by
# hand (textbook results where there is one).
CASES = [
    # ---- C curves: plots and limits -------------------------------------------
    ('C', 'Plot y = f(x)', 'x^2-4', ['roots: -2, 2', 'f(0) = -4', 'turning point (0, -4)']),
    ('C', 'Plot y = f(x)', 'x^3-3x,-3,3', ['roots: -sqrt(3), 0, sqrt(3)',
                                           'turning point (-1, 2)', 'turning point (1, -2)']),
    ('C', 'Plot y = f(x)', 'x^2+1,2', ['give both a and b']),
    ('C', 'Family y = f(x, a)', 'x^2+a,-3,3,-4,-1,0', ['a=-4 roots: -2, 2', 'a=-4 y in [-4, 5]',
                                                       'a=-1 roots: -1, 1', 'a=0 roots: 0',
                                                       'members: 3']),
    ('C', 'Family y = f(x, a)', 'a/x,1,4,1,2', ['a=1 roots: none in range', 'a=2 y in [1/2, 2]']),
    ('C', 'Family y = f(x, a)', 'x^2,-1,1,2', ['does not use a']),
    ('C', 'Family polar r(t, a)', '1+a*cos(t),0.5,1,2', ['a=1/2 r in [1/2, 3/2]',
                                                          'a=1 r touches 0: meets pole',
                                                          'a=2 r in [-1, 3]',
                                                          'a=2 r changes sign: loop']),
    ('C', 'Family parametric', 'a*cos(t),sin(t),0,2pi,1,2', ['a=2 x in [-2, 2]', 'a=2 y in [-1, 1]',
                                                             'closed: ends meet']),
    ('C', 'Envelope of family', '2*a*x-a^2,-2,2,-3,3', ['envelope y = x^2', 'x=-2 a=-2 y=4',
                                                         'x=1 a=1 y=1', 'df/da = 2*x-2*a']),
    ('C', 'Envelope of family', 'a*x+1/a,0.25,4,0.1,3', ['x=1/4 a=2 y=1', 'x=4 a=1/2 y=4',
                                                          'x=49/16 a=4/7 y=7/2']),
    ('C', 'Envelope of family', 'x+a,-2,2,-3,3', ['no envelope', 'df/da = 1']),
    ('C', 'Limit x -> a', 'sin(x)/x,0', ['limit = 1', 'from below: 1', 'from above: 1',
                                         'undefined: a hole']),
    ('C', 'Limit x -> a', '(1-cos(x))/x^2,0', ['limit = 1/2', "l'Hopital"]),
    ('C', 'Limit x -> a', 'abs(x)/x,0', ['no limit: sides differ', 'from below: -1',
                                         'from above: 1']),
    ('C', 'Limit x -> a', '1/x^2,0', ['limit = +infinity', 'x = 0 is a vertical asymptote']),
    ('C', 'Limit x -> a', '1/x,0', ['no limit: sides differ', 'from below: -infinity']),
    ('C', 'Limit x -> a', 'sqrt(x),0', ['one-sided limit only', 'from above: 0']),
    ('C', 'Limit x -> a', 'x^2,3', ['limit = 9', 'continuous at x = 3']),
    ('C', 'Limit x -> +infinity', '(2x+1)/(x-3)', ['limit = 2', 'horizontal asymptote y = 2',
                                                   'x=1000  f = 2.00702']),
    ('C', 'Limit x -> +infinity', 'x^3', ['limit = +infinity']),
    ('C', 'Limit x -> +infinity', '(1+1/x)^x', ['limit = 2.72', 'found numerically']),
    ('C', 'Limit x -> +infinity', 'sin(x)', ['no limit found']),
    ('C', 'Limit x -> -infinity', '(3x^2+1)/(x^2-5)', ['limit = 3']),
    ('C', 'Limit x -> -infinity', 'exp(-x)', ['limit = +infinity']),
    ('C', 'Asymptotes', '(x^2+1)/x', ['vertical: x = 0', 'from below f -> -infinity',
                                      'from above f -> +infinity', 'oblique: y = x (exact)',
                                      'r = 1']),
    ('C', 'Asymptotes', '(2x+1)/(x-3)', ['vertical: x = 3', 'horizontal: y = 2 (exact)']),
    ('C', 'Asymptotes', '(x^2-1)/(x-1)', ['no vertical asymptote', 'oblique: y = x + 1 (exact)',
                                          'r = 0']),
    ('C', 'Asymptotes', '(x^3+1)/(x-1)', ['vertical: x = 1', 'no horizontal or oblique',
                                          'deg num - deg den = 2']),
    ('C', 'Asymptotes', 'sqrt(x^2+1)', ['no vertical asymptote', 'as x->+inf: y = x',
                                        'as x->-inf: y = -x', 'found numerically']),
    ('C', 'Asymptotes', 'tan(x)', ['vertical: x = pi/2', 'vertical: x = -pi/2']),
    ('C', 'Graph (ax+b)/(cx+d)', '2,3,1,-1', ['vertical asymptote x = 1',
                                              'horizontal asymptote y = 2',
                                              'crosses x-axis at -3/2', 'crosses y-axis at -3']),
    ('C', 'Graph quad / linear', '1,0,1,1,0', ['oblique asymptote y = x',
                                               'range: y <= -2 or y >= 2',
                                               'stationary point (1, 2)']),
    ('C', 'Graph quad / linear', '1,-1,-6,1,-2', ['oblique asymptote y = x + 1',
                                                  'crosses x-axis at -2, 3',
                                                  'y = x + 1 - 4/(x-2)']),
    ('C', 'Graph quad / quad', '1,1,1,1,-1,1', ['range: 1/3 <= y <= 3',
                                                'stationary point (-1, 1/3)']),
    ('C', 'Graph quad / quad', '1,0,-4,1,0,-1', ['vertical asymptotes x = -1, 1',
                                                 'horizontal asymptote y = 1']),
    ('C', 'Stationary points', 'x^3-3x', ['maximum (-1, 2)', 'minimum (1, -2)', "f'' = -6"]),
    ('C', 'Stationary points', 'x^3', ['inflection (0, 0)', "f'' = 0"]),
    ('C', 'Stationary points', '(x^2-1)^2', ['minimum (-1, 0)', 'maximum (0, 1)', 'minimum (1, 0)']),
    ('C', 'Stationary points', '1/x', ['no stationary point']),
    ('C', 'Cusps (gradient limit)', '(x^2)^(1/3)', ['cusp at (0, 0)', "f' from below -> -infinity",
                                                    "f' from above -> +infinity"]),
    ('C', 'Cusps (gradient limit)', 'abs(x-2)+1', ['corner at (2, 1)', "f' from below -> -1",
                                                   "f' from above -> 1"]),
    ('C', 'Cusps (gradient limit)', 'x^3-3x', ['no cusp or corner found']),
    ('C', 'Cusps (gradient limit)', '1/x', ['no cusp or corner found']),
    # ---- T curves: tangents, conversion, arcs ------------------------------------
    ('T', 'Tangent, normal y=f(x)', 'x^2,1', ['point (1, 1)', 'gradient dy/dx = 2',
                                              'tangent y = 2x - 1', 'normal y = -(1/2)x + 3/2']),
    ('T', 'Tangent, normal y=f(x)', 'sin(x),pi/3', ['point (pi/3, sqrt(3)/2)',
                                                    'gradient dy/dx = 1/2']),
    ('T', 'Tangent, normal y=f(x)', 'x^(1/3),0', ['gradient undefined', 'tangent x = 0',
                                                  'normal y = 0']),
    ('T', 'Tangent, normal y=f(x)', 'ln(x),0', ['f is undefined at x = 0']),
    ('T', 'Tangent at variable p', 'x^3,1,2', ['y = 3*p^2*x-2*p^3', 'p=1: y = 3x - 2',
                                               'p=2: y = 12x - 16']),
    ('T', 'Tangent parametric', 't^2,2t,1', ['point (1, 2)', 'gradient dy/dx = 1',
                                             'tangent y = x + 1', 'normal y = -x + 3']),
    ('T', 'Tangent parametric', 'cos(t),sin(t),0', ['tangent x = 1', 'normal y = 0']),
    ('T', 'Tangent parametric', 't^2,t^3,0', ['singular point']),
    ('T', 'Tangent polar', '1+cos(t),pi/2', ['point (0, 1)', 'gradient dy/dx = 1',
                                             'tangent y = x + 1', 'normal y = -x + 1']),
    ('T', 'Tangent polar', '2,pi/4', ['point (sqrt(2), sqrt(2))', 'tangent y = -x + 2sqrt(2)']),
    ('T', 'Tangent implicit', 'x^2+y^2-25,3,4', ['gradient dy/dx = -3/4',
                                                 'tangent y = -(3/4)x + 25/4',
                                                 'normal y = (4/3)x']),
    ('T', 'Tangent implicit', 'x^3+y^3-3x*y,1.5,1.5', ['gradient dy/dx = -1', 'tangent y = -x + 3']),
    ('T', 'Tangent implicit', 'x^2+y^2-25,1,1', ['not on the curve: F = -23']),
    ('T', 'Chord of y = f(x)', 'x^2,1,3', ['chord gradient = 4', 'chord y = 4x - 3', "f'(1) = 2",
                                           'b = a+0.001: gradient 2.001']),
    ('T', 'Cartesian to polar', 'x^2+y^2-2x', ['r = 2*cos(theta)', 'divided by r']),
    ('T', 'Cartesian to polar', 'x^2+y^2-4', ['r^2 = 4', 'r = 2']),
    ('T', 'Cartesian to polar', 'x*y-1', ['r^2 = 2*cosec(2*theta)']),
    ('T', 'Cartesian to polar', '(x^2+y^2)^2-2(x^2-y^2)', ['r^2 = 2*cos(2*theta)']),
    ('T', 'Cartesian to polar', 'y-x', ['-cos(theta)+sin(theta) = 0', 'lines through the pole']),
    ('T', 'Polar to cartesian', '2cos(t)', ['x^2 + y^2 - 2x = 0']),
    ('T', 'Polar to cartesian', '1/(1+cos(t))', ['y^2 + 2x - 1 = 0', 'from r = -x + 1']),
    ('T', 'Polar to cartesian', '4sin(t)', ['x^2 + y^2 - 4y = 0']),
    ('T', 'Polar to cartesian', 't', ['cos, sin, tan of k*theta']),
    ('T', 'Arc length y=f(x)', 'x^2,0,1', ['s = 1.48', 'dy/dx = 2*x']),
    ('T', 'Arc length y=f(x)', 'x^(3/2),0,4', ['s = 9.07', 'dy/dx = 3*sqrt(x)/2']),
    ('T', 'Arc length y=f(x)', 'x^2,1,1', ['the two limits are equal']),
    ('T', 'Arc length parametric', 'cos(t),sin(t),0,pi', ['s = 3.14', 'numerically matches pi',
                                                          'dx/dt = -sin(t)']),
    ('T', 'Arc length parametric', 't^2,t^3,0,1', ['s = 1.44']),
    ('T', 'Arc length polar', '1+cos(t),0,2pi', ['s = 8', 'dr/dtheta = -sin(t)']),
    ('T', 'Arc length polar', 'exp(t),0,1', ['s = 2.43']),
    # ---- D differential equations -----------------------------------------------
    ('D', 'Tangent field', 'y,-1,1,-3,3,0,1', ['y(1) = 2.71828', 'y(-1) = 0.367879',
                                                'dashes drawn: 117 of 117']),
    ('D', 'Tangent field', '-x/y,-1,1,-3,3,0,2', ['y(1) = 1.73205', 'y(-1) = 1.73205',
                                                   'dashes drawn: 104 of 117']),
    ('D', 'Tangent field', 'y*(1-y),-2,2,-0.5,1.5,0,0.5', ['y(2) = 0.880797', 'y(-2) = 0.119203']),
    ('D', 'Tangent field', 'x*y,-3,3,-3,3', ['dashes drawn: 117 of 117']),
    ('D', 'Tangent field', 'x*y,-3,3,-3,3,1', ['give both x0 and y0']),
    ('D', 'Verify a DE solution', 'e^(2x),q-3p+2y', ['verified: y is a solution',
                                                     'd2y/dx2 = 4*e^(2*x)']),
    ('D', 'Verify a DE solution', 'e^(3x),q-3p+2y', ['not a solution', '2*e^(3*x)']),
    ('D', 'Verify a DE solution', 'sin(2x),q+4y', ['verified']),
    ('D', 'Verify a DE solution', 'x^2+3,p-2x', ['verified', 'dy/dx = 2*x']),
    ('D', 'Particular solution', 'c*e^(2x),0,3', ['c = 3', 'y = 3*e^(2*x)']),
    ('D', 'Particular solution', 'x^2+c,1,5', ['c = 4', 'y = x^2+4']),
    ('D', 'Particular solution', '1/(c-x),0,1', ['c = 1', 'found numerically']),
    ('D', 'Solution family', 'c*e^(-x),0,3,1,2,3', ['c=1 y in [0.0498, 1]', 'c=3 y in [0.149, 3]']),
    ('D', 'Euler step by step', 'y,0,1,0.1,10', ['y(1) = 2.59', 'x=1  y=2.59374']),
    ('D', 'Euler step by step', 'y,0,1,0,10', ['h must not be zero']),
    ('D', 'Euler: halving h', 'y,0,1,1,4', ['h=1/4: y(X) = 2.44141', 'h=1/8: y(X) = 2.56578',
                                            'h=1/16: y(X) = 2.63793', 'h=1/32: y(X) = 2.67699',
                                            'RK4 with h/8: 2.71828']),
    ('D', 'RK2 (modified Euler)', 'y,0,1,0.1,10', ['y(1) = 2.71', 'x=1  y=2.7140808']),
    ('D', 'RK2 (modified Euler)', 'x^2,0,0,1,1', ['y(1) = 0.5']),
    ('D', 'RK2 (midpoint)', 'x^2,0,0,1,1', ['y(1) = 0.25']),
    ('D', 'RK2 (midpoint)', 'y,0,1,0.1,10', ['x=1  y=2.7140808']),
    ('D', 'RK4', 'y,0,1,0.1,1', ['y(0.1) = 1.10517', 'x=0.1  y=1.1051708']),
    ('D', 'RK4', 'x^2,0,0,1,1', ['y(1) = 0.333333']),
    ('D', 'Euler, RK2, RK4', 'y,0,1,0.1,10', ['Euler y = 2.59374', 'RK2 y = 2.71408',
                                              'RK4 y = 2.71828']),
    # ---- N number theory -------------------------------------------------------
    ('N', 'gcd and lcm', '12,18', ['gcd = 6', 'lcm = 36', '12 = 2^2 * 3']),
    ('N', 'gcd and lcm', '0,0', ['cannot both be 0']),
    ('N', 'Euclid and Bezout', '240,46', ['gcd(240, 46) = 2', '2 = 240(-9) + 46(47)',
                                          '240 = 5 x 46 + 10']),
    ('N', 'Prime test', '97', ['97 is prime']),
    ('N', 'Prime test', '91', ['91 is not prime', 'smallest factor 7', '91 = 7 * 13']),
    ('N', 'Prime factorise', '60', ['60 = 2^2 * 3 * 5', 'number of divisors 12',
                                    'sum of divisors 168']),
    ('N', 'Prime factorise', '7', ['7 = 7', 'n is prime']),
    ('N', 'Prime factorise', '1e11', ['n must be 2 to']),
    ('N', 'Euler totient phi(n)', '36', ['phi(36) = 12', '36(1-1/2)(1-1/3)']),
    ('N', 'Euler totient phi(n)', '13', ['phi(13) = 12', 'n prime']),
    ('N', 'a^b mod m', '2,10,1000', ['2^10 mod 1000 = 24', 'b in binary: 1010']),
    ('N', 'a^b mod m', '3,200,7', ['3^200 mod 7 = 2']),
    ('N', 'Modular inverse', '3,7', ['inverse = 5', '3 x 5 = 15 = 1 (mod 7)']),
    ('N', 'Modular inverse', '4,8', ['no inverse', 'gcd(a, m) = 4']),
    ('N', 'Solve ax = b (mod m)', '6,4,10', ['x = 4 (mod 5)', '4, 9']),
    ('N', 'Solve ax = b (mod m)', '2,3,4', ['no solution']),
    ('N', 'Chinese remainder', '2,3,3,5', ['x = 8 (mod 15)']),
    ('N', 'Chinese remainder', '1,4,2,6', ['no solution']),
    ('N', "Fermat's little thm", '3,7', ['a^(p-1) mod p = 1', 'p prime']),
    ('N', "Fermat's little thm", '2,15', ['a^(p-1) mod p = 4', 'composite']),
    ('N', "Fermat's little thm", '2,341', ['pseudoprime base 2']),
    ('N', "Fermat's little thm", '7,7', ['Fermat does not apply']),
    ('N', "Wilson's theorem", '13', ['(p-1)! mod p = 12', 'p is prime']),
    ('N', "Wilson's theorem", '12', ['(p-1)! mod p = 0', 'not prime']),
    ('N', "Wilson's theorem", '1e9', ['p must be 2 to 100000']),
    ('N', 'Pythagorean triples', '30', ['primitive triples: 5', '20, 21, 29', '7, 24, 25']),
    ('N', 'Triple from m, n', '2,1', ['(3, 4, 5)', 'primitive']),
    ('N', 'Triple from m, n', '3,1', ['(8, 6, 10)', 'not primitive', '2 x (4, 3, 5)']),
    ('N', "Pell x^2-ny^2=1", '2', ['x = 3', 'y = 2', 'j=2 x = 17']),
    ('N', "Pell x^2-ny^2=1", '61', ['x = 1766319049', 'y = 226153980']),
    ('N', "Pell x^2-ny^2=1", '4', ['perfect square']),
    ('N', 'Linear ax+by=c', '6,15,12', ['x = -8 + 5t', 'y = 4 - 2t', 'least x >= 0: (2, 0)']),
    ('N', 'Linear ax+by=c', '6,15,7', ['no integer solutions', 'does not divide 7']),
    ('N', 'Linear ax+by=c', '17,5,1', ['particular x0 = -2, y0 = 7']),
    ('N', 'Linear ax+by=c', '0,0,5', ['no solutions']),
    ('N', 'Integer solutions', 'x^2-y^2-15,10', ['solutions found: 8', '(4, 1)', '(8, 7)']),
    ('N', 'Integer solutions', 'x^2+y^2-25,6', ['solutions found: 12', '(3, 4)']),
    ('N', 'Decimal to base b', '255,16', ['FF (base 16)']),
    ('N', 'Decimal to base b', '10,2', ['1010 (base 2)']),
    ('N', 'Base b to decimal', '1011,2', ['1011 (base 2) = 11']),
    ('N', 'Base b to decimal', '129,8', ['digit 9 is not allowed']),
]
