# Cases for mcalc (AQA 7357 G-J). Every number here was checked by hand or
# against an independent calculation.
CASES = [
    # ---- G differentiation ----
    ('G', "Derivative f' and f''", 'x^3-2x+1', ['3*x^2-2', '6*x']),
    ('G', "Derivative f' and f''", 'sin(2x)', ['2*cos(2*x)', '-4*sin(2*x)']),
    ('G', 'Tangent and normal', 'x^2,3', ['6*x-9', '19/2', 'point (3, 9)']),
    ('G', 'Tangent and normal', 'x^2,0', ['normal x = 0', 'point (0, 0)']),
    ('G', 'Stationary points', 'x^3-3x', ['max at (-1, 2)', 'min at (1, -2)']),
    ('G', 'Stationary points', 'x^4', ['min at (0, 0)']),
    ('G', 'Inflection points', 'x^3-3x',
     ['inflection at (0, 0)', 'concave for x < 0', 'convex for x > 0']),
    ('G', 'Inflection points', 'x^4', ['no inflection point', 'convex for all x']),
    ('G', 'Increasing/decreasing', 'x^3-3x',
     ['increasing for x < -1', 'decreasing for -1 < x < 1', 'increasing for x > 1']),
    ('G', 'First principles', 'x^2,3',
     ["f'(3) = 6", 'grad = 6.1', 'grad = 6.01', 'grad = 6.001']),
    ('G', 'Parametric dy/dx', 't^2,t^3,2',
     ['3*t/2', 'dy/dx = 3', 'point (4, 8)']),
    ('G', 'Parametric dy/dx', 'cos(t),sin(t),?', ['dx/dt = -sin(t)']),
    ('G', 'Implicit dy/dx', 'x^2+y^2-25,3,4', ['-x/y', 'dy/dx = -3/4']),
    ('G', 'Implicit dy/dx', 'x^2+y^2-25,1,1', ['not on the curve']),
    ('G', 'Connected rates', 'x^2,3,2', ['dy/dt = 12', '6 * 2 = 12']),
    ('G', 'Inverse derivative', 'x^3,2', ["(f^-1)'(8) = 1/12", "f'(2) = 12"]),
    ('G', "f, f' and f'' at a", 'x^3,2', ['f(2) = 8', "f'(2) = 12", "f''(2) = 12"]),

    # ---- H integration ----
    ('H', 'Indefinite integral', 'x^2', ['x^3/3+c', 'agrees']),
    ('H', 'Indefinite integral', '1/(x^2-1)',
     ['ln(|x-1|)/2', 'ln(|x+1|)/2']),
    ('H', 'Definite integral', 'x^2,0,3', ['integral = 9', 'F(x) = x^3/3']),
    ('H', 'Definite integral', 'sin(x),0,pi', ['integral = 2']),
    ('H', 'Definite integral', '1/x,-1,1', ['f breaks inside a..b']),
    ('H', 'Area under curve', 'x^3,-1,1',
     ['area = 1/2', 'signed integral = 0', '-1 to 0: -1/4']),
    ('H', 'Area between curves', 'x^2,x', ['area = 1/6', 'f = g at 0 and 1']),
    ('H', 'Area between curves', 'x^2,x,0,2', ['area = 1', '1 to 2: 5/6']),
    ('H', 'Substitution u=g(x)', '2x*(x^2+1)^3,x^2+1',
     ['(x^2+1)^4/4+c', 'int u^3 du = u^4/4']),
    ('H', 'Substitution u=g(x)', 'x*(x+1)^5,x+1', ['x remains: try another u']),
    ('H', 'Integration by parts', 'x,e^x',
     ['e^(x)*x-e^(x)+c', 'v = int dv dx = e^(x)']),
    ('H', 'Riemann sum table', 'x^2,0,3',
     ['integral = 9', 'sum = 7.695', 'sum = 8.86545', 'sum = 8.9865045']),
    ('H', 'Separable DE', 'x,y', ['ln(|y|) = x^2/2 + c']),
    ('H', 'Separable DE at point', 'x,y,0,1', ['e^(x^2/2)', 'ln(|y|) = x^2/2']),
    ('H', 'Separable DE at point', '1,y^2,0,1', ['-1/(x-1)', '-1/y = x - 1']),
    ('H', 'd/dx of an integral', 'x^2,1', ['x^3/3-1/3', "A'(x) ="]),

    # ---- I numerical methods ----
    ('I', 'Sign change table', 'x^3-2x-5,2,3',
     ['sign change 2 to 2.1', 'x = 2.1   f = 0.061']),
    ('I', 'Sign change table', '1/x,-1,1,4',
     ['sign change -0.5 to 0.5', 'f breaks between: not a root']),
    ('I', 'Newton-Raphson', 'x^3-2x-5,2,4',
     ['x = 2.0945515', 'x1 = 2.1', 'x2 = 2.0945681']),
    ('I', 'Newton-Raphson', 'x^2+1,0,3', ['Newton-Raphson failed']),
    ('I', 'Fixed point x=g(x)', 'sqrt(x+2),1,6',
     ['x1 = 1.7320508', 'x2 = 1.9318517', 'x = 1.9997323', 'converges']),
    ('I', 'Fixed point x=g(x)', 'x^2+1,1,5', ['the iteration diverges']),
    ('I', 'Bisection', 'x^2-2,1,2,4',
     ['x = 1.40625', 'm = 1.5', 'm = 1.25', 'm = 1.375', 'm = 1.4375']),
    ('I', 'Bisection', 'x^2-2,3,4', ['no sign change in [a, b]']),
    ('I', 'Trapezium rule', 'x^2,0,1,4',
     ['T = 11/32', 'T = 0.34375', 'over-estimate']),
    ('I', 'Trapezium rule', 'sqrt(x),0,1,4', ['T = 0.643', 'under-estimate']),
    ('I', 'Iterate to n dp', '(2x+5)^(1/3),2,3',
     ['x = 2.095 to 3 dp', 'x1 = 2.0800838']),

    # ---- J vectors ----
    ('J', 'Magnitude and angle', '3,4,0', ['|v| = 5', 'angle from i = 53.1 deg']),
    ('J', 'Magnitude and angle', '2,3,6', ['|v| = 7', 'i: 73.4']),
    ('J', 'Components from r,th', '10,30', ['v = (5sqrt(3), 5)']),
    ('J', 'Sum and difference', '1,2,3,4,5,6',
     ['a + b = (5, 7, 9)', 'a - b = (-3, -3, -3)', '|a + b| = sqrt(155)']),
    ('J', 'Scalar multiple k a', '3,1,-2,2', ['k a = (3, -6, 6)', '|k a| = 9']),
    ('J', 'Unit vector', '3,4,0', ['unit = (3/5, 4/5, 0)']),
    ('J', 'Distance A to B', '1,2,3,4,6,3', ['|AB| = 5', 'AB = (3, 4, 0)']),
    ('J', 'Midpoint and ratio', '1,2,3,3,6,9', ['midpoint = (2, 4, 6)']),
    ('J', 'Midpoint and ratio', '1,2,3,3,6,9,1,2',
     ['m:n point = (5/3, 10/3, 5)']),
    ('J', 'Parallel test', '1,2,3,2,4,6', ['parallel: b = 2 a', 'same direction']),
    ('J', 'Parallel test', '1,0,0,1,1,0', ['not parallel', 'angle = 45 deg']),
    ('J', 'Resultant of forces', '3,4,-1,2',
     ['R = (2, 6)', '|R| = 2sqrt(10)', 'angle = 71.6 deg']),
    ('J', 'Position r0 + v t', '1,0,2,3,-1,0,2', ['r = (7, -2, 2)', '|r| = sqrt(57)']),
    ('J', 'Angle between vectors', '1,0,0,1,1,0',
     ['angle = 45 deg', 'pi/4 rad', 'a.b = 1']),
]
