# Cases for fcore.py (AQA 7367 sections A-D). Every tool has at least one
# case; the numbers in the needles are checked by hand.
CASES = [
    # ---- A  Proof ----------------------------------------------------------
    ('A', 'Induction: sum', 'r, n(n+1)/2', ['Proved for all n >= 1',
                                            'S(1) = 1 = u(1)']),
    ('A', 'Induction: sum', 'r^3, n^2(n+1)^2/4', ['Proved for all n >= 1']),
    ('A', 'Induction: sum', 'r^2, n^2', ['Inductive step fails']),
    ('A', 'Induction: sum', 'r, n(n+2)/2', ['Base case fails at n = 1',
                                            'S(1) = 3/2,  u(1) = 1']),
    ('A', 'Induction: divisor', '5^n+3, 4', ['4 divides f(n): proved',
                                             'f(1..4) = 8, 28, 128, 628']),
    ('A', 'Induction: divisor', '5^n+3, 4, 5', ['d at k=1..4: -12, -12, -12, -12']),
    ('A', 'Induction: divisor', '2^n+1, 4', ['Not divisible: n = 1',
                                             'f(1) = 3, remainder 3']),
    ('A', 'Induction: M^n', '1,1,0,1, 1, n, 0, 1', ['Proved for all n >= 1',
                                                    'M^3 = [1 3]']),
    ('A', 'Induction: M^n', '2,0,0,3, 2^n, 0, 0, 3^n', ['Proved for all n >= 1',
                                                        'M^2 = [4 0]']),
    ('A', 'Induction: M^n', '1,1,0,1, 1, n+1, 0, 1', ['Base case fails at n = 1']),

    # ---- B  Complex numbers -------------------------------------------------
    ('B', 'Arithmetic z, w', '2+3i, 1-i', ['z+w = 3+2i', 'z-w = 1+4i',
                                           'zw = 5+i', 'z/w = -1/2+5/2i']),
    ('B', 'Arithmetic z, w', '2+3i, 0', ['z/w undefined: w = 0']),
    ('B', 'Modulus-argument', '1+i', ['|z| = sqrt(2)', 'arg z = pi/4 rad',
                                      'arg z = 45 deg', 'conj z = 1-i']),
    ('B', 'Modulus-argument', '-3', ['|z| = 3', 'arg z = pi rad']),
    ('B', 'From mod-arg form', '2, pi/3', ['z = 1+sqrt(3)i']),
    ('B', 'Multiply in mod-arg', '2,pi/6,3,pi/3', ['zw: r = 6, arg = pi/2',
                                                   'zw = 6i',
                                                   'z/w: r = 2/3, arg = -pi/6']),
    ('B', 'De Moivre z^n', '1+i, 8', ['z^8 = 16', '|z^n| = 16']),
    ('B', 'De Moivre z^n', '2i, -2', ['z^-2 = -1/4']),
    ('B', 'nth roots of z', '8i, 3', ['w0 = sqrt(3)+i', 'w2 = -2i',
                                      'regular 3-gon']),
    ('B', 'Roots of unity', '3', ['w^1 = -1/2+sqrt(3)/2i',
                                  'w^2 = -1/2-sqrt(3)/2i']),
    ('B', 'Quadratic roots', '1,2,5', ['z1 = -1+2i', 'z2 = -1-2i',
                                       'disc = b^2-4ac = -16']),
    ('B', 'Quadratic roots', '2,-5,2', ['z1 = 1/2', 'z2 = 2']),
    ('B', 'Cubic real coeffs', '1,-6,13,-10,2', ['z1 = 2', 'z2 = 2+i', 'z3 = 2-i',
                                                 '2 is a root: divide by (z-2)']),
    ('B', 'Cubic real coeffs', '1,-1,4,6', ['z1 = -1', 'z2 = 1+sqrt(5)i']),
    ('B', 'Cubic real coeffs', '1,-1,4,6,5', ['5 is not a root']),
    ('B', 'Quartic real coeffs', '1,-4,12,4,-13,2+3i',
     ['z3 = 2+3i', 'z4 = 2-3i', 'with its conjugate: factor z^2-4z+13']),
    ('B', 'Quartic real coeffs', '1,0,0,0,-16', ['z1 = -2', 'z2 = 2', 'z3 = 2i']),
    ('B', 'Argand plot', '1,2,-3,1', ['z1 = 1+2i, |z| = sqrt(5)',
                                      'z2 = -3+i, |z| = sqrt(10)']),
    ('B', 'Locus |z-z1| = r', '2+i, 3', ['circle centre 2+i radius 3',
                                         '(x-2)^2+(y-1)^2 = 9',
                                         'greatest |z| = 5.24']),
    ('B', 'Locus arg(z-z1) = t', '1+i, pi/4', ['half-line from 1+i',
                                               'y-1 = (x-1)', 'only x > 1']),
    ('B', 'Locus |z-z1|=|z-z2|', '0, 4+2i', ['midpoint (2, 1)', 'y = -2x + 5']),
    ('B', 'cos nt, sin nt powers', '3', ['cos 3t = c^3-3cs^2',
                                         'sin 3t = 3c^2s-s^3']),
    ('B', 'cos nt, sin nt powers', '4', ['cos 4t = c^4-6c^2s^2+s^4',
                                         'sin 4t = 4c^3s-4cs^3']),
    ('B', 'cos^n t, sin^n t', '3', ['cos^3 t = (cos3t+3cos t)/4',
                                    'sin^3 t = (3sin t-sin3t)/4']),
    ('B', 'cos^n t, sin^n t', '4', ['cos^4 t = (cos4t+4cos2t+3)/8',
                                    'sin^4 t = (cos4t-4cos2t+3)/8']),
    ('B', 'Complex geometric sum', '1+i, 0.5i, 5', ['S = 7/16+19/16i',
                                                    'S(infinity) = 2/5+6/5i']),
    ('B', 'Complex geometric sum', '2, 1, 5', ['S = 10', 'no sum to infinity']),

    # ---- C  Matrices --------------------------------------------------------
    ('C', 'pA + qB (2x2)', '1,-1,1,2,3,4,0,1,1,0', ['pA+qB = [1 1]', '[2 4]']),
    ('C', 'pA + qB (3x3)', '2,0,1,2,3,4,5,6,7,8,9,0,0,0,0,0,0,0,0,0',
     ['pA+qB = [2 4 6]', '[8 10 12]', '[14 16 18]']),
    ('C', 'AB and BA (2x2)', '1,2,3,4,0,1,1,0', ['AB = [2 1]', 'BA = [3 4]',
                                                 'AB is not BA: order matters']),
    ('C', 'AB and BA (3x3)', '1,2,0,0,1,0,0,0,1,1,0,0,3,1,0,0,0,1',
     ['AB = [7 2 0]', '[3 1 0]']),
    ('C', 'Determinant 2x2', '3,1,2,4', ['det A = 10', 'area scale factor = 10']),
    ('C', 'Determinant 2x2', '1,2,3,4', ['det A = -2',
                                         'det < 0: orientation is reversed']),
    ('C', 'Determinant 3x3', '1,2,3,0,1,4,5,6,0', ['det A = 1',
                                                   'volume scale factor = 1']),
    ('C', 'Determinant 3x3', '1,2,3,2,4,6,1,0,1', ['det A = 0', 'singular']),
    ('C', 'Inverse 2x2', '3,1,2,4', ['A^-1 = [2/5 -1/10]', '[-1/5 3/10]']),
    ('C', 'Inverse 2x2', '1,2,2,4', ['no inverse: det A = 0']),
    ('C', 'Inverse 3x3', '1,2,3,0,1,4,5,6,0', ['A^-1 = [-24 18 5]',
                                               '[20 -15 -4]', '[-5 4 1]']),
    ('C', 'Inverse 3x3', '1,2,3,2,4,6,1,0,1', ['no inverse: det A = 0']),
    ('C', 'Solve 3 eqns by A^-1', '1,1,1,2,-1,1,1,2,-1,6,3,2',
     ['x = 1', 'y = 2', 'z = 3', 'unique point']),
    ('C', 'Solve 3 eqns by A^-1', '1,1,1,1,2,3,2,3,4,1,2,3',
     ['planes meet in a line (sheaf)', 'direction (1, -2, 1)']),
    ('C', 'Solve 3 eqns by A^-1', '1,1,1,1,2,3,2,3,4,1,2,5',
     ['triangular prism: no solution']),
    ('C', 'Solve 3 eqns by A^-1', '1,1,1,2,2,2,1,2,-1,6,13,2',
     ['two planes are parallel', 'no solution']),
    ('C', 'Rotation 2D (deg)', '90', ['R = [0 -1]', '[1 0]',
                                      'rotation 90 deg about O']),
    ('C', 'Reflect in y=x tan t', '45', ['M = [0 1]', '[1 0]',
                                         'reflect in y = x tan 45 deg']),
    ('C', 'Stretch or enlarge 2D', '3,3', ['enlargement scale factor 3',
                                           'det = 9 = area scale factor']),
    ('C', 'Stretch or enlarge 2D', '2,1', ['stretch x by 2, y by 1']),
    ('C', 'Describe a 2x2', '0,-1,1,0', ['rotation 90 deg about O', 'det = 1']),
    ('C', 'Describe a 2x2', '0,1,1,0', ['reflection in y = x tan 45 deg']),
    ('C', 'Describe a 2x2', '1,2,3,4', ['not a standard transformation']),
    ('C', 'Rotation 3D (axis)', '3,90', ['R = [0 -1 0]', 'rotate 90 deg about z']),
    ('C', 'Reflect 3D in plane', '2', ['M = [1 0 0]', '[0 -1 0]',
                                       'reflect in the plane y = 0']),
    ('C', 'Invariant points/lines', '3,-1,-1,3', ['only invariant point is (0, 0)',
                                                  'invariant line y = x',
                                                  'invariant line y = -x']),
    ('C', 'Invariant points/lines', '1,2,0,1', ['line of invariant points y = 0']),
    ('C', 'Eigen 2x2', '4,1,2,3', ['char eq: L^2-7L+10 = 0', 'L1 = 5, v1 = (1, 1)',
                                   'L2 = 2, v2 = (1, -2)']),
    ('C', 'Eigen 2x2', '0,-1,1,0', ['char eq: L^2+1 = 0', 'no real eigenvalues']),
    ('C', 'Eigen 2x2', '2,1,0,2', ['repeated eigenvalue L = 2',
                                   'only one eigenvector: not diagonalisable']),
    ('C', 'Eigen 3x3', '2,0,1,0,2,0,1,0,2', ['char eq: L^3-6L^2+11L-6 = 0',
                                             'L = 1, v = (1, 0, -1)',
                                             'L = 3, v = (1, 0, 1)']),
    ('C', 'Diagonalise 2x2 M^n', '4,1,2,3,3', ['D = diag(5, 2)', 'U = [1 1]',
                                               'M^3 = [86 39]', '[78 47]']),
    ('C', 'Diagonalise 2x2 M^n', '2,1,0,2,3', ['not diagonalisable']),
    ('C', 'Diagonalise 3x3 M^n', '2,0,1,0,2,0,1,0,2,2', ['D = diag(1, 2, 3)',
                                                         'M^2 = [5 0 4]']),
    ('C', 'Diagonalise 3x3 M^n', '1,1,0,0,1,0,0,0,2,2',
     ['not diagonalisable over the reals']),

    # ---- D  Further algebra and functions -----------------------------------
    ('D', 'Vieta root sums', '1,-6,11,-6', ['sum of roots = 6',
                                            'sum of pairs = 11',
                                            'product of all = 6']),
    ('D', 'Vieta root sums', '2,-5,2', ['sum of roots = 5/2',
                                        'product of all = 1']),
    ('D', 'Power sums of roots', '4,1,-3,2', ['S1 = sum a^1 = 3',
                                              'S2 = sum a^2 = 5',
                                              'S3 = sum a^3 = 9',
                                              'S4 = sum a^4 = 17']),
    ('D', 'Roots p a + q', '2,1,1,-3,2', ['x^2-8*x+15']),
    ('D', 'Roots 1/a', '1,-3,2', ['2*x^2-3*x+1']),
    ('D', 'Roots a^2', '1,-3,2', ['x^2-5*x+4']),
    ('D', 'Sum r, r^2, r^3', '10', ['sum r = n(n+1)/2 = 55',
                                    'sum r^2 = n(n+1)(2n+1)/6 = 385',
                                    'sum r^3 = (n(n+1)/2)^2 = 3025']),
    ('D', 'Sum f(r), r = a..b', 'r^2+r,1,10', ['sum = 440']),
    ('D', 'Sum f(r), r = a..b', 'r^3,3,8', ['sum = 1287']),
    ('D', 'Method of differences', '1/(r(r+1)),10', ['g(r) = 1/r',
                                                     'S(10) = 10/11']),
    ('D', 'Method of differences', '2/((2r-1)(2r+1))', ['g(r) = 1/(2*r-1)',
                                                        'S(n) = 1 - (1/(2*n+1))']),
    ('D', 'Method of differences', '1/(r(r+1)(r+2)),4', ['S(4) = 7/30']),
    ('D', 'Maclaurin series', 'e^x,4', ['x^4/24+x^3/6+x^2/2+x+1',
                                        'term r: x^r/r!']),
    ('D', 'Maclaurin series', 'ln(1+x),4', ['valid for -1 < x <= 1']),
    ('D', 'Binomial (1+x)^p', '1/2,3', ['x^3/16-x^2/8+x/2+1',
                                        'valid only for |x| < 1']),
    ('D', 'Binomial (1+x)^p', '3,4', ['x^3+3*x^2+3*x+1',
                                      'p is a whole number: the series stops']),
    ('D', 'Limit as x -> a', '(x^2-1)/(x-1),1', ['limit = 2']),
    ('D', 'Limit as x -> a', '(1-cos(x))/x^2,0', ['limit = 1/2']),
    ('D', 'Limit as x -> a', 'abs(x)/x,0', ['no limit: the two sides differ']),
    ('D', 'Solve f(x) > g(x)', 'x^3-2x^2-5x+6, 0', ['-2 < x < 1', 'x > 3']),
    ('D', 'Solve f(x) > g(x)', '1/x, x', ['x < -1', '0 < x < 1']),
    ('D', 'Solve f(x) < g(x)', '(x+1)/(x-2), 3', ['x < 2', 'x > 7/2']),
    ('D', 'Solve f(x) < g(x)', 'abs(x-1), 2x', ['x > 1/3']),
    ('D', 'Graph (ax+b)/(cx+d)', '2,3,1,-1', ['vertical asymptote x = 1',
                                              'horizontal asymptote y = 2',
                                              'crosses x-axis at -3/2',
                                              'crosses y-axis at -3']),
    ('D', 'Graph quad / linear', '1,0,1,1,0', ['oblique asymptote y = x',
                                               'range: y <= -2 or y >= 2',
                                               'stationary point (1, 2)']),
    ('D', 'Graph quad / linear', '1,-1,-6,1,-2', ['oblique asymptote y = x + 1',
                                                  'crosses x-axis at -2, 3']),
    ('D', 'Graph quad / quad', '1,1,1,1,-1,1', ['range: 1/3 <= y <= 3',
                                                'stationary point (-1, 1/3)']),
    ('D', 'Graph quad / quad', '1,0,-4,1,0,-1', ['vertical asymptotes x = -1, 1',
                                                 'horizontal asymptote y = 1']),
    ('D', 'Graph f, |f|, f(|x|)', 'x^2-4', ['zeros of f: -2, 2', 'f(0) = -4']),
    ('D', 'Parabola y^2 = 4ax', '2', ['y^2 = 8x', 'focus (2, 0)',
                                      'directrix x = -2',
                                      'parametric (2t^2, 4t)']),
    ('D', 'Ellipse x2/a2+y2/b2', '5,3', ['x-intercepts (+/-5, 0)',
                                         'eccentricity e = 4/5',
                                         'foci (+/-4, 0)']),
    ('D', 'Hyperbola x2/a2-y2/b2', '3,4', ['vertices (+/-3, 0)',
                                           'asymptotes y = +/-4/3x',
                                           'eccentricity e = 5/3',
                                           'foci (+/-5, 0)']),
    ('D', 'Rect hyperbola xy=c^2', '2', ['xy = 4, asymptotes x = 0, y = 0',
                                         'vertices (2, 2) and (-2, -2)']),
    ('D', 'Transform y = f(x)', 'x^2,?,?,2', ['(x-2)^2']),
    ('D', 'Transform y = f(x)', 'sin(x),2,3,0,1', ['3*sin(x/2)+1']),
]
