# Cases for fcalc (AQA 7367 sections E-J). Every tool has at least one case;
# branchy tools (convergence, line pairs, damping, auxiliary roots) have one
# case per branch. Numbers checked by hand.
CASES = [
    # ---- E further calculus -------------------------------------------------
    ('E', 'Integral to infinity', '1/x^2,1', ['integral = 1', 'up to 1000001']),
    ('E', 'Integral to infinity', '1/x,1', ['diverges']),
    ('E', 'Integral to infinity', 'e^(-x),0', ['integral = 1']),
    ('E', 'Singular endpoint int', '1/sqrt(x),0,1', ['integral = 2',
                                                     'f is undefined at x = 0']),
    ('E', 'Singular endpoint int', '1/sqrt(1-x),0,1', ['integral = 2',
                                                       'f is undefined at x = 1']),
    ('E', 'Singular endpoint int', '1/x,0,1', ['diverges']),
    ('E', 'Volume about x-axis', 'x,0,1', ['V = pi/3', '= 1.05']),
    ('E', 'Volume about x-axis', 'x^2,0,2', ['V = 32pi/5', 'int y^2 dx = 6.4']),
    ('E', 'Volume about y-axis', 'y^2,0,1', ['V = pi/5']),
    ('E', 'Mean value of f', 'x^2,0,3', ['mean = 3', 'f = mean at x = 1.73']),
    ('E', 'Mean value of f', 'sin(x),0,pi', ['mean = 0.637', 'int f dx = 2']),
    ('E', 'Integrate by partials', '3x+1,(x-1)(x^2+1)',
     ['atan(x)+2*ln(abs(x-1))-ln(x^2+1)', '2/(x-1)+(1-2*x)/(x^2+1)']),
    ('E', 'Integrate by partials', '5x-2,x^2-4', ['2/(x-2)+3/(x+2)']),
    ('E', 'd/dx inverse trig', 'asin(x/3),1', ['1/(3*sqrt(1-(x/3)^2))',
                                               "f'(1) = sqrt(2)/4"]),
    ('E', 'd/dx inverse trig', 'atan(2x),?', ['2/(1+(2*x)^2)']),
    ('E', 'Int 1/sqrt(a2-x2)', '2,0,1', ['integral = pi/6', 'asin(x/2)']),
    ('E', 'Int 1/(a2+x2)', '3,0,3', ['integral = pi/12', 'atan(x/3)/3']),
    ('E', 'Arc length y=f(x)', 'x^2,0,1', ['s = 1.48', 'dy/dx = 2*x']),
    ('E', 'Arc length parametric', 'cos(t),sin(t),0,pi', ['s = 3.14',
                                                          'dx/dt = -sin(t)']),
    ('E', 'Surface area x-axis', 'x,0,1', ['S = 4.44']),
    ('E', 'Surface area param', 'cos(t),sin(t),0,pi', ['S = 4pi']),
    ('E', 'Reduction x^n e^x', '4', ['I_4 = 9e - 24', '0.465', 'I_1 = 1 = 1']),
    ('E', 'Reduction sin^n', '4', ['I_4 = 3pi/16', 'I_2 = pi/4 = 0.785398']),
    ('E', 'Reduction sin^n', '5', ['I_5 = 8/15', 'I_3 = 2/3']),
    ('E', 'Reduction cos^n', '6', ['I_6 = 5pi/32', '0.491']),
    ('E', 'Reduction tan^n', '4', ['I_4 = pi/4 - 2/3', 'I_2 = 1 - pi/4']),
    ('E', 'Reduction tan^n', '3', ['I_3 = 1/2 - ln2/2', 'I_1 = ln2/2']),
    ('E', 'Reduction (ln x)^n', '3', ['I_3 = 6 - 2e', '0.563']),
    ('E', 'Limit x^k e^-x', '2', ['limit = 0', 'x = 10:  0.00454']),
    ('E', 'Limit x^k ln x', '1', ['limit = 0', 'x = 0.1:  -0.2303']),

    # ---- F further vectors --------------------------------------------------
    ('F', 'Line from two points', '1,2,3,3,5,7',
     ['r = (1, 2, 3) + t(2, 3, 4)', '(x - 1)/2 = (y - 2)/3 = (z - 3)/4']),
    ('F', 'Line to cartesian', '1,0,2,2,-1,0',
     ['(x - 1)/2 = y/(-1)', 'z = 2']),
    ('F', 'Plane from 3 points', '1,0,0,0,1,0,0,0,1',
     ['r.(1, 1, 1) = 1', 'x + y + z = 1']),
    ('F', 'Plane point + normal', '1,2,3,2,-1,2',
     ['r.(2, -1, 2) = 6', '2x - y + 2z = 6']),
    ('F', 'Angle between lines', '1,0,0,1,1,0', ['angle = pi/4 rad', '45 deg']),
    ('F', 'Angle line and plane', '1,1,1,0,0,1',
     ['angle = 0.615 rad', '35.3 deg', 'sqrt(3)/3']),
    ('F', 'Angle between planes', '1,0,0,1,1,0', ['angle = pi/4 rad']),
    ('F', 'Perpendicular check', '1,2,3,2,-1,0', ['perpendicular', 'not parallel']),
    ('F', 'Perpendicular check', '1,2,3,2,4,6', ['not perpendicular', 'a.b = 28']),
    ('F', 'Vector product', '1,2,3,4,5,6',
     ['a x b = (-3, 6, -3)', '|a x b| = 3sqrt(6)']),
    ('F', 'Area of triangle', '0,0,0,1,0,0,0,1,0', ['area = 1/2']),
    ('F', 'Is p on (r-a)xb=0', '1,1,1,1,2,3,3,5,7', ['p is on the line', 't = 2']),
    ('F', 'Is p on (r-a)xb=0', '1,1,1,1,2,3,0,0,0', ['p is not on the line']),
    ('F', 'Intersect two lines', '1,1,1,1,0,0,0,1,1,0,1,0',
     ['they meet at (0, 1, 1)', 't = -1,  s = 0']),
    ('F', 'Intersect two lines', '0,0,0,1,0,0,0,1,1,0,0,1',
     ['skew lines', 'distance = 1']),
    ('F', 'Intersect two lines', '0,0,0,1,0,0,0,1,0,2,0,0',
     ['parallel, no intersection', 'distance = 1']),
    ('F', 'Distance two lines', '0,0,0,1,0,0,0,1,1,0,0,1',
     ['skew lines', 'distance = 1']),
    ('F', 'Distance two lines', '0,0,0,1,0,0,0,1,0,2,0,0',
     ['parallel lines', 'distance = 1']),
    ('F', 'Line meets plane', '1,1,1,1,1,1,1,0,0,4',
     ['meets at (4, 4, 4)', 'angle = 0.615 rad']),
    ('F', 'Line meets plane', '0,0,0,1,0,0,0,0,1,5',
     ['parallel, never meets', 'distance = 5']),
    ('F', 'Point to line dist', '1,2,3,0,0,0,1,0,0',
     ['distance = sqrt(13)', 'foot = (1, 0, 0)']),
    ('F', 'Point to plane dist', '1,1,1,1,2,2,0',
     ['distance = 5/3', 'foot = (4/9, -1/9, -1/9)']),

    # ---- G polar coordinates ------------------------------------------------
    ('G', 'Polar to cartesian', '2,pi/3', ['x = 1', 'y = sqrt(3)']),
    ('G', 'Cartesian to polar', '1,1', ['r = sqrt(2)', 'theta = pi/4 rad']),
    ('G', 'Plot r = f(theta)', '1+cos(x)', ['r(0) = 2', 'r(pi) = 0']),
    ('G', 'Polar area', '2,0,2pi', ['area = 4pi', '12.6']),
    ('G', 'Polar area', '1+cos(x),0,pi', ['area = 3pi/4']),
    ('G', 'Tangent para to axis', '1+cos(x),0,pi',
     ['theta = 1.05, r = 1.5', 'theta = pi, r = 0']),
    ('G', 'Tangent perp to axis', '2cos(x),0,pi/2',
     ['theta = 0, r = 2', 'theta = pi/2, r = 0']),

    # ---- H hyperbolic functions ---------------------------------------------
    ('H', 'Six hyperbolics at x', '1',
     ['sinh x = 1.18', 'cosh x = 1.54', 'tanh x = 0.762', 'coth x = 1.31']),
    ('H', 'Six hyperbolics at x', '0',
     ['sinh x = 0', 'cosh x = 1', 'cosech and coth undefined at 0']),
    ('H', 'Inverse hyperbolics', '2',
     ['arsinh x = 1.44', 'ln(2 + sqrt(5))', 'arcosh x = 1.32',
      'artanh needs |x| < 1']),
    ('H', 'Inverse hyperbolics', '0.5',
     ['artanh x = 0.549', 'arcosh needs x >= 1']),
    ('H', 'Solve a cosh+b sinh=c', '1,0,2',
     ['x = ln(2 + sqrt(3))', 'x = ln(2 - sqrt(3))', '= 1.32']),
    ('H', 'Solve a cosh+b sinh=c', '5,3,4', ['x = ln(1/2)', '= -0.693']),
    ('H', 'Solve a cosh+b sinh=c', '1,0,0.5', ['no real solutions']),
    ('H', 'Identity check at x', '1',
     ['cosh^2-sinh^2 = 1', 'sinh2x = 3.63, 2sc = 3.63']),
    ('H', 'Plot sinh cosh tanh', '3', ['cosh x: all x, y >= 1, even',
                                       'tanh = 0.995']),
    ('H', 'd/dx hyperbolic', 'cosh(2x),0', ['2*sinh(2*x)', "f'(0) = 0"]),
    ('H', 'Integrate hyperbolic', 'sinh(x),0,1',
     ['cosh(x)', 'int from 0 to 1 = 0.543']),
    ('H', 'Integrate hyperbolic', 'x*cosh(x),?,?', ['sinh(x)*x-cosh(x)']),
    ('H', 'Int 1/sqrt(x2+a2)', '2,0,2', ['integral = 0.881', 'asinh(x/2)']),
    ('H', 'Int 1/sqrt(x2-a2)', '3,3,6', ['integral = 1.32', 'acosh(x/3)']),

    # ---- I differential equations -------------------------------------------
    ('I', 'Integrating factor', '2/x,x^2,?,?',
     ['x^2', '(x^5/5+C)/x^2', 'int IF*Q dx = x^5/5']),
    ('I', 'Integrating factor', '1,e^(2x),0,1',
     ['(e^(3*x)/3+C)/e^(x)', 'C = 2/3']),
    ('I', 'Integrating factor', 'tan(x),1,?,?',
     ['1/cos(x)', 'int (IF)Q dx is not elementary']),
    ('I', 'Second order homogen', '1,-3,2',
     ['m = 2 and 1', 'A*e^(2*x)+B*e^(x)', 'aux: m^2 - 3m + 2 = 0']),
    ('I', 'Second order homogen', '1,4,4',
     ['m = -2 (repeated)', '(A+B*x)*e^(-2*x)', 'disc = b^2 - 4ac = 0']),
    ('I', 'Second order homogen', '1,2,5',
     ['m = -1 +/- 2 i', 'e^(-x)*(A*cos(2*x)+B*sin(2*x))']),
    ('I', 'Second order with IVs', '1,-3,2,1,0',
     ['2*e^(x)-e^(2*x)', 'A = -1,  B = 2']),
    ('I', 'Second order with IVs', '1,4,4,1,0', ['(1+2*x)*e^(-2*x)']),
    ('I', 'Second order with IVs', '1,0,4,3,0', ['3*cos(2*x)', 'A = 3,  B = 0']),
    ('I', 'PI polynomial RHS', '1,0,-2,x^2',
     ['PI: -x^2/2-1/2', 'A*e^(sqrt(2)*x)+B*e^(-sqrt(2)*x)-x^2/2-1/2']),
    ('I', 'PI polynomial RHS', '1,3,0,6x',
     ['PI: x^2-2*x/3', 'B*e^(-3*x)+x^2+A-2*x/3',
      'c = 0, so the trial is raised a degree']),
    ('I', 'PI for k e^(px)', '1,-3,2,1,3', ['PI: e^(3*x)/2', 'ap^2+bp+c = 2']),
    ('I', 'PI for k e^(px)', '1,-3,2,1,1',
     ['PI: -(e^(x)*x)', 'p is a root, so trial C x e^(px)']),
    ('I', 'PI for k e^(px)', '1,-2,1,1,1',
     ['PI: e^(x)*x^2/2', 'p is a repeated root: trial C x^2 e^(px)']),
    ('I', 'PI for m cos + n sin', '1,0,4,0,1,1',
     ['PI: sin(x)/3', 'P = 0, Q = 1/3']),
    ('I', 'PI for m cos + n sin', '1,0,4,0,1,2',
     ['PI: -(cos(2*x)*x)/4', 'wi is a root, so trial x(P cos + Q sin)']),
    ('I', 'SHM from omega', '2,3,0',
     ['amplitude R = 3', 'period T = pi', '3*cos(2*t)', 'max speed = 6']),
    ('I', 'SHM from omega', '2,?,?',
     ['period T = pi', 'C*cos(2*t)+D*sin(2*t)']),
    ('I', 'Hooke law SHM', '8,2', ['w = 2', 'period T = pi', 'k/m = 4']),
    ('I', 'Damping classify', '1,3,2',
     ['heavy damping', 'm = -1 and -2', 'disc = c^2 - 4mk = 1']),
    ('I', 'Damping classify', '1,2,1', ['critical damping', '(A+B*t)*e^(-t)']),
    ('I', 'Damping classify', '1,1,4',
     ['light damping', 'oscillates, amplitude decays']),
    ('I', 'Damping classify', '1,0,4',
     ['no damping (SHM)', 'oscillates, amplitude constant']),
    ('I', 'Coupled equations', '1,1,4,1,?,?',
     ['A*e^(3*t)+B*e^(-t)', '2*A*e^(3*t)-2*B*e^(-t)', 'a+d = 2,  ad-bc = -3']),
    ('I', 'Coupled equations', '1,1,4,1,1,0',
     ['e^(-t)/2+e^(3*t)/2', 'e^(3*t)-e^(-t)']),
    ('I', 'Coupled equations', '0,1,-1,0,1,0', ['cos(t)', '-sin(t)']),

    # ---- J numerical methods -------------------------------------------------
    ('J', 'Mid-ordinate rule', 'x^2,0,1,4',
     ['M = 0.328', 'x = 0.875:  0.765625', 'exact = 0.333333']),
    ("J", "Simpson's rule", 'x^2,0,1,4', ['S = 0.333', 'y3 = 0.5625']),
    ("J", "Simpson's rule", '1/x,1,2,4',
     ['S = 0.693', 'exact = 0.693147, error = -0.000107']),
    ('J', 'Compare rules', 'x^2,0,1,4',
     ['mid-ordinate = 0.328', 'trapezium = 0.344', 'Simpson = 0.333',
      'exact = 1/3']),
    ('J', 'Compare rules', 'x^2,0,1,5', ["Simpson's rule needs an even n"]),
    ('J', 'Euler step by step', 'x+y,0,1,0.1,3',
     ['r=2  x = 0.2  y = 1.22', 'r=3  x = 0.3  y = 1.362']),
    ('J', 'Improved Euler', 'x+y,0,1,0.1,3',
     ['r=2  x = 0.2  y = 1.24', 'r=3  x = 0.3  y = 1.388']),
]
