# Cases for mpure.py (AQA 7357 sections A-F).
# (section code, tool label, typed input, needles that must appear)
CASES = [
    # ---- A  Proof ----------------------------------------------------------
    ('A', 'Counterexample f>0', 'n^2-5n+3,1,10',
     ['counterexample n = 1', 'f(1) = -1']),
    ('A', 'Counterexample f>0', 'n^2+1,1,20',
     ['no counterexample found', 'not a proof']),
    ('A', 'Counterexample prime', 'n^2+n+41,1,50',
     ['counterexample n = 40', 'f(40) = 41 x 41']),
    ('A', 'Counterexample prime', 'n^2+n+17,1,10',
     ['no counterexample found']),
    ('A', 'Counterexample d|f(n)', 'n^3-n,3,1,20',
     ['no counterexample found']),
    ('A', 'Counterexample d|f(n)', 'n^2+1,3,1,5',
     ['counterexample n = 1', 'rem 2']),
    ('A', 'Counterexample f=g', '(n+1)^2,n^2+2n+1,1,10',
     ['no counterexample found']),
    ('A', 'Counterexample f=g', 'n^2,2n,1,5',
     ['counterexample n = 1', 'f = 1, g = 2']),

    # ---- B  Algebra and functions -----------------------------------------
    ('B', 'Index a^(p/q)', '8,2,3', ['= 4', 'root 3 of 8 = 2']),
    ('B', 'Index a^(p/q)', '16,-3,4', ['= 1/8', 'decimal = 0.125']),
    ('B', 'Index a^(p/q)', '-4,1,2', ['not real']),
    ('B', 'Simplify sqrt(n)', '12', ['sqrt(12) = 2*sqrt(3)', 'decimal = 3.46']),
    ('B', 'Simplify sqrt(n)', '49', ['sqrt(49) = 7']),
    ('B', 'Simplify surd expr', 'sqrt(8)+sqrt(18)', ['= 5sqrt(2)', '7.07']),
    ('B', 'Rationalise', '1,0,1,1,1,2', ['= sqrt(2)-1', 'decimal = 0.414']),
    ('B', 'Rationalise', '3,2,5,1,-1,5', ['(-13-5*sqrt(5))/4', '-6.05']),
    ('B', 'Quadratic', '1,-3,2', ['x = 1', 'x = 2', 'disc = 1',
                                  'vertex (3/2, -1/4)']),
    ('B', 'Quadratic', '1,2,5', ['-1+2i', '-1-2i', 'no real roots']),
    ('B', 'Quadratic', '1,-2,-1', ['x = 1-sqrt(2)', 'x = 1+sqrt(2)',
                                   'disc = 8']),
    ('B', 'Quadratic', '1,-4,4', ['x = 2 (repeated)', 'disc = 0']),
    ('B', 'Quadratic', '2,3,1', ['x = -1', 'x = -1/2', 'vertex (-3/4, -1/8)']),
    ('B', 'Quadratic', '0,2,-6', ['x = 3', 'this is linear']),
    ('B', 'Quadratic in f(x)', '1,-5,4,x^2',
     ['u = f(x) = 1', 'u = f(x) = 4', 'x = -2', 'x = 2']),
    ('B', 'Simultaneous 2 linear', '2,3,8,1,-1,1', ['x = 11/5', 'y = 6/5']),
    ('B', 'Simultaneous 2 linear', '1,1,2,2,2,5',
     ['no solution', 'parallel']),
    ('B', 'Line meets quadratic', '1,1,1,0,-1', ['(-1, 0)', '(2, 3)']),
    ('B', 'Solve f(x)=g(x)', 'x^2,x+2', ['(-1, 1)', '(2, 4)']),
    ('B', 'Linear inequality', '2,-6', ['> 0: x > 3', '< 0: x < 3']),
    ('B', 'Linear inequality', '-2,6', ['> 0: x < 3', '< 0: x > 3']),
    ('B', 'Quadratic inequality', '1,-3,2',
     ['f > 0: x < 1 or x > 2', 'f < 0: 1 < x < 2']),
    ('B', 'Quadratic inequality', '1,0,1',
     ['f > 0: every x', 'f < 0: no x', 'no real roots']),
    ('B', 'Expand', '(2x-1)(x+3)', ['2*x^2+5*x-3']),
    ('B', 'Factorise', 'x^2-5x+6', ['(x-2)*(x-3)']),
    ('B', 'Factorise', 'x^2+1', ['no rational factorisation']),
    ('B', 'Divide p(x) by d(x)', 'x^3-2x^2-5x+6,x-1',
     ['quotient = x^2-x-6', 'remainder = 0', '(x-1) is a factor']),
    ('B', 'Divide p(x) by d(x)', 'x^2+1,x-2',
     ['quotient = x+2', 'remainder = 5']),
    ('B', 'Factor theorem', 'x^3-2x^2-5x+6,1',
     ['p(1) = 0', '(x - 1) is a factor']),
    ('B', 'Factor theorem', 'x^3-2x^2-5x+6,2',
     ['p(2) = -4', 'is not a factor']),
    ('B', 'Simplify f(x)/g(x)', 'x^2-1,x^2+2x+1',
     ['(x-1)/(x+1)', 'x != -1']),
    ('B', 'Partial fractions', '3x+2,(x+1)(x+2)',
     ['-1/(x+1)+4/(x+2)', '-1 / (x+1)', '4 / (x+2)']),
    ('B', 'Composite fg and gf', '2x+1,x^2,3',
     ['2*x^2+1', '4*x^2+4*x+1', 'fg(3) = 19', 'gf(3) = 49']),
    ('B', 'Inverse function', '2x+3', ['f-1(x) = (x-3)/2']),
    ('B', 'Inverse function', 'x^2+x', ['no inverse formula found']),
    ('B', 'Transform af(bx+c)+d', 'x^2,2,1,0,3', ['2*x^2+3']),
    ('B', 'Solve |ax+b|=cx+d', '1,-2,0,4', ['x = -2', 'x = 6']),
    ('B', 'Solve |ax+b|=cx+d', '1,0,0,-1', ['no solution']),
    ('B', 'Proportion y=kx^n', '2,3,18', ['k = 2', '2*x^2']),
    ('B', 'Plot f(x)', 'x^2-4,-3,3',
     ['y(0) = -4', 'root x = -2', 'root x = 2']),

    # ---- C  Coordinate geometry -------------------------------------------
    ('C', 'Line through 2 points', '1,2,3,8',
     ['y = 3x - 1', '3x - y - 1 = 0', 'midpoint (2, 5)',
      'length = 2sqrt(10)']),
    ('C', 'Line through 2 points', '2,1,2,5', ['x = 2', 'length = 4']),
    ('C', 'Perpendicular bisect', '1,2,5,4',
     ['y = -2x + 9', 'midpoint (3, 3)']),
    ('C', 'Parallel through pt', '3,1,2', ['y = 3x - 1']),
    ('C', 'Perpendicular thru pt', '2,4,1',
     ['y = -(1/2)x + 3', 'x + 2y - 6 = 0']),
    ('C', 'Intersect y=mx+c', '2,1,-1,4', ['(1, 3)']),
    ('C', 'Intersect y=mx+c', '2,1,2,4', ['no intersection', 'parallel']),
    ('C', 'Circle from general', '-2,4,-4',
     ['centre (1, -2)', 'radius = 3', '(x - 1)^2 + (y + 2)^2 = 9']),
    ('C', 'Circle from general', '0,0,4', ['not a real circle']),
    ('C', 'Circle centre+radius', '1,-2,3',
     ['(x - 1)^2 + (y + 2)^2 = 9', 'x^2 + y^2 - 2x + 4y - 4 = 0']),
    ('C', 'Circle through 3 pts', '0,0,4,0,0,3',
     ['centre (2, 3/2)', 'radius = 5/2', 'one chord is a diameter']),
    ('C', 'Circle through 3 pts', '0,0,1,1,2,2', ['no circle', 'collinear']),
    ('C', 'Line meets circle', '1,0,0,0,2',
     ['(-sqrt(2), -sqrt(2))', '(sqrt(2), sqrt(2))']),
    ('C', 'Line meets circle', '0,5,0,0,2', ['no intersection']),
    ('C', 'Tangent to circle', '0,0,3,4',
     ['3x + 4y - 25 = 0', 'radius = 5']),
    ('C', 'Param to Cartesian', '2t,t^2', ['y = x^2/4']),
    ('C', 'Param to Cartesian', '3cos(t),3sin(t)', ['x^2 + y^2 = 9']),
    ('C', 'Param point at t', 't^2,t^3,2',
     ['(4, 8)', 'dy/dx = 3', 'y = 3x - 4']),
    ('C', 'Plot parametric', 'cos(t),sin(t),0,6.28318530718',
     ['start (1, 0)', 'end (1, 0)']),

    # ---- D  Sequences and series ------------------------------------------
    ('D', 'Arithmetic a,d,n', '3,5,10', ['u(10) = 48', 'S(10) = 255']),
    ('D', 'Geometric a,r,n', '2,3,5',
     ['u(5) = 162', 'S(5) = 242', 'no sum to infinity']),
    ('D', 'Geometric a,r,n', '4,1/2,6',
     ['u(6) = 1/8', 'S(6) = 63/8', 'S(inf) = 8']),
    ('D', 'AP: n for Sn > k', '3,5,100', ['n = 7', 'S(7) = 126']),
    ('D', 'GP: n for Sn > k', '2,3,100', ['n = 5', 'S(5) = 242']),
    ('D', 'GP: n for Sn > k', '4,1/2,20', ['no such n', 'S(inf) = 8']),
    ('D', 'Binomial (a+bx)^n', '2,3,4',
     ['x^0: 16', 'x^1: 96', 'x^2: 216', 'x^4: 81']),
    ('D', 'Binomial (a+bx)^n', '1,-1,3', ['x^1: -3', 'x^3: -1']),
    ('D', 'Binomial rational n', '1,1,1/2',
     ['x^1: 1/2', 'x^2: -1/8', 'x^3: 1/16', 'valid for |x| < 1']),
    ('D', 'Binomial rational n', '4,-1,-1',
     ['x^0: 1/4', 'x^1: 1/16', 'valid for |x| < 4']),
    ('D', 'Sigma sum f(r) a..b', 'r^2,1,10', ['sum = 385', '10 terms']),
    ('D', 'Recurrence u(n+1)', 'u^2-1,2,5',
     ['u(2) = 3', 'u(4) = 63', 'increasing']),
    ('D', 'Recurrence u(n+1)', '1/u,2,6', ['periodic, period 2']),
    ('D', 'Terms of u(n)', '3n-1,1,5',
     ['u(1) = 2', 'u(5) = 14', 'increasing']),
    ('D', 'nCr and nPr', '5,2', ['nCr = 10', 'nPr = 20', 'n! = 120']),

    # ---- E  Trigonometry ---------------------------------------------------
    ('E', 'Exact trig at x deg', '30',
     ['sin 30 = 1/2', 'cos 30 = sqrt(3)/2', 'tan 30 = sqrt(3)/3']),
    ('E', 'Exact trig at x deg', '15',
     ['sin 15 = (sqrt(6)-sqrt(2))/4', 'tan 15 = 2-sqrt(3)']),
    ('E', 'Exact trig at x deg', '90', ['cos 90 = 0', 'tan 90 is undefined']),
    ('E', 'Triangle SSS', '3,4,5',
     ['A = 36.9 deg', 'C = 90 deg', 'area = 6']),
    ('E', 'Triangle SSS', '1,2,9', ['cannot make a triangle']),
    ('E', 'Triangle SAS', '5,7,60', ['a = sqrt(39)', 'area = 35sqrt(3)/4']),
    ('E', 'Triangle ASA', '30,60,5', ['b = 5sqrt(3)', 'c = 10']),
    ('E', 'Triangle SSA', '4,5,30', ['B = 38.7 deg', 'ambiguous']),
    ('E', 'Triangle SSA', '1,5,30', ['no triangle']),
    ('E', 'Area (1/2)ab sinC', '4,5,30', ['area = 5']),
    ('E', 'Arc and sector (rad)', '5,1.2',
     ['arc = 6', 'sector area = 15', 'chord = 5.65']),
    ('E', 'Arc and sector (deg)', '6,60',
     ['arc = 2pi', 'sector area = 6pi', 'chord = 6']),
    ('E', 'Degrees to radians', '60', ['60 deg = pi/3 rad']),
    ('E', 'Radians to degrees', 'pi/3', ['rad = 60 deg']),
    ('E', 'Solve trig eqn (deg)', 'sin(x)-1/2,0,360',
     ['x = 30 deg', 'x = 150 deg']),
    ('E', 'Solve trig eqn (rad)', '2cos(x)+1,0,6.2831853',
     ['x = 2pi/3', 'x = 4pi/3']),
    ('E', 'Quad in sin x (deg)', '2,-1,-1,0,360',
     ['sin x = -1/2', 'x = 210 deg', 'x = 330 deg', 'sin x = 1']),
    ('E', 'Quad in cos x (deg)', '1,0,-1,0,360',
     ['cos x = -1', 'x = 180 deg', 'x = 0 deg']),
    ('E', 'Quad in tan x (deg)', '1,-1,0,0,360',
     ['tan x = 1', 'x = 45 deg', 'x = 225 deg']),
    ('E', 'Quad in sin x (deg)', '1,0,4,0,360', ['no solution']),
    ('E', 'R form a sin + b cos', '3,4',
     ['R = 5', 'al = 53.1 deg', 'max 5 at x = 36.9 deg']),
    ('E', 'Small angle (rad)', '0.1',
     ['sin: approx 0.1, exact 0.0998', 'cos: approx 0.995']),
    ('E', 'Compound angle (deg)', '45,30',
     ['sin(45+30) = (sqrt(2)+sqrt(6))/4', 'cos(45+30) = (sqrt(6)-sqrt(2))/4',
      'tan(45+30) = sqrt(3)+2']),
    ('E', 'Double angle (deg)', '30',
     ['sin 60 = sqrt(3)/2', 'cos 60 = 1/2', 'tan 60 = sqrt(3)']),
    ('E', 'sec cosec cot (deg)', '60',
     ['sec = 1/cos = 2', 'cosec = 1/sin = 2sqrt(3)/3']),
    ('E', 'sec cosec cot (deg)', '90', ['sec is undefined']),
    ('E', 'arcsin arccos arctan', '0.5',
     ['arcsin = 30 deg', 'arccos = 60 deg', 'arctan = 26.6 deg']),
    ('E', 'arcsin arccos arctan', '2', ['|v| > 1']),
    ('E', 'Identity check (rad)', 'sin(x)^2+cos(x)^2,1',
     ['holds at every x tested']),
    ('E', 'Identity check (rad)', 'sin(2x),2sin(x)', ['not an identity']),

    # ---- F  Exponentials and logarithms -----------------------------------
    ('F', 'Solve a^x = b', '2,8', ['x = 3']),
    ('F', 'Solve a^x = b', '2,5', ['x = 2.32']),
    ('F', 'Solve a^x = b', '2,-1', ['no real solution']),
    ('F', 'Solve log_a x = c', '3,4', ['x = 81']),
    ('F', 'log base a of x', '2,32', ['log_2 32 = 5']),
    ('F', 'Evaluate log expr', 'ln(e^3)', ['= 3']),
    ('F', 'y = a x^n from 2 pts', '2,12,4,48', ['n = 2', 'a = 3', '3*x^2']),
    ('F', 'y = k b^x from 2 pts', '0,3,2,12', ['b = 2', 'k = 3', '3*2^x']),
    ('F', 'Log-log fit y=ax^n', '1,3,2,12,3,27,4,48',
     ['n = 2', 'a = 3', '4 points']),
    ('F', 'Log-lin fit y=kb^x', '0,3,1,6,2,12,3,24',
     ['b = 2', 'k = 3', '4 points']),
    ('F', 'N = A e^(kt) 2 pts', '0,100,10,50',
     ['A = 100', 'k = -0.0693', 'half-life = 10']),
    ('F', 'Evaluate A e^(kt)', '100,-0.0693147,10',
     ['N = 50', 'half-life = 10']),
    ('F', 'Compound interest', '1000,5,5',
     ['A = 1276.28', 'interest = 276.282', 'continuous = 1284.03']),
]
