# Checks for the Notes screens (casui.NOTE_PAPERS, notes_*.py, notes_ix.py,
# and the typeset pages tn_*.py that mknotes.py builds from them).
#   python3 tests_notes.py         run the checks
#   python3 tests_notes.py write   regenerate notes_ix.py and tn_*.py
# tests.py-style entry point: run(check).
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__)) or '.'
sys.path.insert(0, HERE)

import casui
import notesui
import casrender
import devlint
import font
import mknotes

LINE = 368      # usable width of a result line ('a' kind, x = 8)
DETAIL = 360    # indented detail line ('w' kind, x = 16)
TILE = 116      # word tile text width, three columns with a scroll bar
MAXLINES = 24   # lines per page

# key results that must stay in the notes
SPOT = [
    'b^2 = 2k^2', 'valid |x| < 1', 'S_inf = a/(1 - r)', 'T = ln 2/|k|',
    "fails if f'(x_n) = 0", 'int 1/x dx = ln|x| + c', 'P(X >= r) = 1 - P(X <= r - 1)',
    'P(X <= 6) -> P(Y < 6.5)', '5%: 1.6449 / 1.9600', 'F <= mu R', 'v^2 = u^2 + 2as',
    'alpha beta gamma = -d/a', 'r^(1/n) e^(i(theta + 2k pi)/n)', '(AB)^-1 = B^-1 A^-1',
    '|(a2 - a1).n|/|n|', 'sum r^2 = n(n + 1)(2n + 1)/6', '2 I = e^(int P dx), no + c',
    'y = (A + Bx) e^(mx)', 'Var(X) = (n^2 - 1)/12', 'Var(X) = (1 - p)/p^2',
    'rs = 1 - 6 sum d^2/(n(n^2 - 1))', 'df = (rows - 1)(columns - 1)',
    'H1 median > m0: T = W-', 'Lagrange: subgroup order', 'M^n = P D^n P^-1',
    '2x2: M^2 - (tr M)M + (det M)I = O', 'u_n = (A + Bn) p^n',
]


def index_source():
    out = ['# Generated by tests_notes.py (python3 tests_notes.py write): topic names',
           '# per paper and module, so a topic menu shows without loading the notes.',
           'T = (']
    for name, mods in casui.NOTE_PAPERS:
        if not mods:
            continue
        out.append('    (%r, (' % name)
        for m in mods:
            out.append('        (%r, (' % m)
            for topic, lines in __import__(m).NOTES:
                out.append('            %r,' % topic)
            out.append('        )),')
        out.append('    )),')
    out.append(')')
    return '\n'.join(out) + '\n'


def page_ok(check, where, page):
    # every display line of a typeset page stays on the screen
    for kind, blk in notesui.lines(page):
        notesui.unpack(blk)
        k, strs, runs, h, ops, src = blk
        right = 0
        for x, y, text, size in strs:
            right = max(right, x + font.strw(text, size))
            check('notes: text inside its line: ' + where, 0 <= y and y + 13 <= h + 3, (y, h, text))
        for x, y in mknotes.runs_of(ops):
            right = max(right, x + 1)
            check('notes: pixels inside their line: ' + where, 0 <= y <= h + 1, (y, h))
        check('notes: line fits ' + str(LINE) + ' px: ' + where + ': ' + repr([s[2] for s in strs])[:60],
              right <= LINE + 8, right)


def page_of(m, i):
    return __import__(mknotes.module_name(m)).N[i]


def run(check):
    papers = casui.NOTE_PAPERS
    names = [p[0] for p in papers]
    check('notes: paper names unique', len(set(names)) == len(names))
    check('notes: booklet first', papers[0][0] == 'Formula booklet' and papers[0][1] == ())
    for nm in names:
        lines = casui.wrap(nm, TILE, 'medium')
        check('notes: paper tile fits: ' + nm, len(lines) <= 2)
    mods = []
    for name, ms in papers:
        check('notes: paper has modules or is the booklet: ' + name, ms != () or name == 'Formula booklet')
        for m in ms:
            check('notes: module listed once: ' + m, m not in mods)
            mods.append(m)
    for m in mods:
        check('notes: ' + m + ' source not shipped', m + '.py' not in devlint.DEVICE_FILES)
        tn = mknotes.module_name(m)
        check('notes: ' + tn + ' shipped (devlint.DEVICE_FILES)', tn + '.py' in devlint.DEVICE_FILES)
    for m in ['notes_ix', 'notesui', 'tex', 'texg', mknotes.BOOK]:
        check('notes: ' + m + ' shipped (devlint.DEVICE_FILES)', m + '.py' in devlint.DEVICE_FILES)
    try:
        cur = open(os.path.join(HERE, 'notes_ix.py')).read()
    except IOError:
        cur = ''
    check('notes: notes_ix.py is current (python3 tests_notes.py write)', cur == index_source())
    src = mknotes.sources()
    for m in sorted(src):
        try:
            cur = open(os.path.join(HERE, m + '.py')).read()
        except IOError:
            cur = ''
        check('notes: ' + m + '.py is current (python3 tests_notes.py write)', cur == src[m])
    import notes_ix
    check('notes: index papers match casui',
          [p for p, t in notes_ix.T] == [n for n, ms in papers if ms])
    total = 0
    blob = []
    for name, ms in papers:
        if not ms:
            continue
        titles = []
        for m in ms:
            try:
                notes = __import__(m).NOTES
            except Exception as e:
                check('notes: ' + m + ' imports', False, repr(e))
                continue
            check('notes: ' + m + ' has topics', len(notes) > 0)
            for ti in range(len(notes)):
                topic, lines = notes[ti]
                where = name + ' / ' + topic
                titles.append(topic)
                check('notes: topic name short: ' + where, 0 < len(topic) <= 24)
                tl = casui.wrap(topic, TILE, 'medium')
                long_word = [w for w in topic.split(' ') if font.strw(w, 'medium') > TILE]
                check('notes: topic tile fits: ' + where, len(tl) <= 2 and not long_word, tl)
                check('notes: page not empty: ' + where, len(lines) > 0)
                check('notes: page short enough: ' + where, len(lines) <= MAXLINES, len(lines))
                blob.extend(lines)
                for k in range(len(lines)):
                    ln = lines[k]
                    total += 1
                    tag = where + ': ' + repr(ln)
                    check('notes: line is a string: ' + tag, isinstance(ln, str))
                    bad = [c for c in ln if ord(c) > 126 or ord(c) < 32]
                    check('notes: ASCII only: ' + tag, not bad)
                    check('notes: no trailing space: ' + tag, ln == ln.rstrip() and ln.strip() != '')
                page_ok(check, where, page_of(m, ti))
        check('notes: topic names unique in ' + name, len(set(titles)) == len(titles))
        check('notes: index lists every topic of ' + name,
              [x[0] for x in notesui.topics(name)] == titles)
    import tn_fb
    import formulae
    check('notes: booklet titles', list(tn_fb.T) == [t for t, ls in formulae.SHEETS])
    for i in range(len(tn_fb.N)):
        page_ok(check, 'booklet / ' + tn_fb.T[i], tn_fb.N[i])
    check('notes: some content', total > 500, total)
    blob = '\n'.join(blob)
    for nd in SPOT:
        check('notes: has ' + repr(nd), nd in blob)
    return total


if __name__ == '__main__':
    if sys.argv[1:] == ['write']:
        open(os.path.join(HERE, 'notes_ix.py'), 'w').write(index_source())
        src = mknotes.sources()
        for m in sorted(src):
            open(os.path.join(HERE, m + '.py'), 'w').write(src[m])
        print('wrote notes_ix.py and ' + ', '.join(sorted(src)))
        sys.exit(0)
    fails = []
    count = [0]

    def check(label, cond, detail=''):
        count[0] += 1
        if not cond:
            fails.append(label + ('  [' + str(detail) + ']' if detail != '' else ''))
    n = run(check)
    for f in fails:
        print('FAIL  ' + f)
    print('tests_notes: ' + str(count[0]) + ' checks, ' + str(len(fails)) + ' failures, ' +
          str(n) + ' lines')
    sys.exit(1 if fails else 0)
