# Cases for fcore.py (MEI H645 Core Pure: proof, complex numbers, matrices,
# vectors, roots of polynomials, series). Every tool has at least one case;
# the numbers in the needles are checked by hand.
CASES = [
    # ---- P  Proof ------------------------------------------------------
    ('P', 'Induction: sum', 'r, n(n+1)/2', ['Proved for all n >= 1',
                                            'S(1) = 1 = u(1)']),
    ('P', 'Induction: sum', 'r^3, n^2(n+1)^2/4', ['Proved for all n >= 1']),
    ('P', 'Induction: sum', 'r^2, n^2', ['Inductive step fails']),
    ('P', 'Induction: sum', 'r, n(n+2)/2', ['Base case fails at n = 1',
                                            'S(1) = 3/2,  u(1) = 1']),
    ('P', 'Induction: divisor', '5^n+3, 4', ['4 divides f(n): proved',
                                             'f(1..4) = 8, 28, 128, 628']),
    ('P', 'Induction: divisor', '5^n+3, 4, 5', ['d at k=1..4: -12, -12, -12, -12']),
    ('P', 'Induction: divisor', '2^n+1, 4', ['Not divisible: n = 1',
                                             'f(1) = 3, remainder 3']),
    ('P', 'Induction: M^n', '1,1,0,1, 1, n, 0, 1', ['Proved for all n >= 1',
                                                    'M^3 = [1 3]']),
    ('P', 'Induction: M^n', '2,0,0,3, 2^n, 0, 0, 3^n', ['Proved for all n >= 1',
                                                        'M^2 = [4 0]']),
    ('P', 'Induction: M^n', '1,1,0,1, 1, n+1, 0, 1', ['Base case fails at n = 1']),
    ('P', 'Induction: recurrence', 'u+2n+1, 1, n^2', ['Proved for all n >= 1',
                                                      'u1..u6 = 1, 4, 9, 16, 25, 36']),
    ('P', 'Induction: recurrence', '2u+1, 1, 2^n-1', ['Step holds at k = 1..10',
                                                     'u1..u6 = 1, 3, 7, 15, 31, 63']),
    ('P', 'Induction: recurrence', 'u+n, 1, n^2', ['Inductive step fails',
                                                  'g(2) = 4 but u2 = 2']),
    ('P', 'Induction: recurrence', '3u, 2, 3^n', ['Base case fails at n = 1',
                                                 'g(1) = 3,  u1 = 2']),
    ('P', 'Induction: de Moivre', 'pi/6, 3', ['z^3 = i',
                                             'agrees with cos nt + i sin nt',
                                             'n = 2: 1/2+sqrt(3)i/2']),
    ('P', 'Induction: de Moivre', 'pi/3, -2', ['z^-2 = -1/2-sqrt(3)i/2',
                                              'z^-m = 1/(cos mt + i sin mt)']),
    ('P', 'Counterexample: prime', 'n^2+n+41, 0, 50', ['Counterexample: n = 40',
                                                      'f(40) = 1681 = 41 x 41']),
    ('P', 'Counterexample: prime', 'n^2+n+41, 0, 39', ['No counterexample, n = 0..39',
                                                      'checking cases is not a proof']),
    ('P', 'Counterexample: f > g', '2^n, n^2, 1, 10', ['Counterexample: n = 2',
                                                      'f = 4, g = 4']),
    ('P', 'Counterexample: f > g', '2^n, n, 1, 20', ['No counterexample, n = 1..20']),

    # ---- J  Complex numbers --------------------------------------------
    ('J', 'Arithmetic z, w', '2+3i, 1-i', ['z+w = 3+2i', 'z-w = 1+4i',
                                           'zw = 5+i', 'z/w = -1/2+5i/2']),
    ('J', 'Arithmetic z, w', '2+3i, 0', ['z/w undefined: w = 0']),
    ('J', 'Modulus-argument', '1+i', ['|z| = sqrt(2)', 'arg z = pi/4 rad',
                                      'arg z = 45 deg', 'conj z = 1-i']),
    ('J', 'Modulus-argument', '-3', ['|z| = 3', 'arg z = pi rad']),
    ('J', 'From mod-arg form', '2, pi/3', ['z = 1+sqrt(3)i']),
    ('J', 'Multiply in mod-arg', '2,pi/6,3,pi/3', ['zw: r = 6, arg = pi/2',
                                                   'zw = 6i',
                                                   'z/w: r = 2/3, arg = -pi/6']),
    ('J', 'De Moivre z^n', '1+i, 8', ['z^8 = 16', '|z^n| = 16']),
    ('J', 'De Moivre z^n', '2i, -2', ['z^-2 = -1/4']),
    ('J', 'nth roots of z', '8i, 3', ['w0 = sqrt(3)+i', 'w2 = -2i',
                                      'regular 3-gon']),
    ('J', 'Roots of unity', '3', ['w^1 = -1/2+sqrt(3)i/2',
                                  'w^2 = -1/2-sqrt(3)i/2']),
    ('J', 'Quadratic roots', '1,2,5', ['z1 = -1+2i', 'z2 = -1-2i',
                                       'disc = b^2-4ac = -16']),
    ('J', 'Quadratic roots', '2,-5,2', ['z1 = 1/2', 'z2 = 2']),
    ('J', 'Cubic real coeffs', '1,-6,13,-10,2', ['z1 = 2', 'z2 = 2+i', 'z3 = 2-i',
                                                 '2 is a root: divide by (z-2)']),
    ('J', 'Cubic real coeffs', '1,-1,4,6', ['z1 = -1', 'z2 = 1+sqrt(5)i']),
    ('J', 'Cubic real coeffs', '1,-1,4,6,5', ['5 is not a root']),
    ('J', 'Quartic real coeffs', '1,-4,12,4,-13,2+3i',
     ['z3 = 2+3i', 'z4 = 2-3i', 'with its conjugate: factor z^2-4z+13']),
    ('J', 'Quartic real coeffs', '1,0,0,0,-16', ['z1 = -2', 'z2 = 2', 'z3 = 2i']),
    ('J', 'Argand plot', '1,2,-3,1', ['z1 = 1+2i, |z| = sqrt(5)',
                                      'z2 = -3+i, |z| = sqrt(10)']),
    ('J', 'Locus |z-z1| = r', '2+i, 3', ['circle centre 2+i radius 3',
                                         '(x-2)^2+(y-1)^2 = 9',
                                         'greatest |z| = 5.24']),
    ('J', 'Locus arg(z-z1) = t', '1+i, pi/4', ['half-line from 1+i',
                                               'y-1 = (x-1)', 'only x > 1']),
    ('J', 'Locus |z-z1|=|z-z2|', '0, 4+2i', ['midpoint (2, 1)', 'y = -2x + 5']),
    ('J', 'cos nt, sin nt powers', '3', ['cos 3t = c^3-3cs^2',
                                         'sin 3t = 3c^2s-s^3']),
    ('J', 'cos nt, sin nt powers', '4', ['cos 4t = c^4-6c^2s^2+s^4',
                                         'sin 4t = 4c^3s-4cs^3']),
    ('J', 'cos^n t, sin^n t', '3', ['cos^3 t = (cos3t+3cos t)/4',
                                    'sin^3 t = (3sin t-sin3t)/4']),
    ('J', 'cos^n t, sin^n t', '4', ['cos^4 t = (cos4t+4cos2t+3)/8',
                                    'sin^4 t = (cos4t-4cos2t+3)/8']),
    ('J', 'Argand sum/product', '1+2i, 3-i', ['z+w = 4+i', 'z-w = -2+3i', 'zw = 5+5i',
                                             '|zw| = |z||w| = sqrt(5) x sqrt(10) = 5sqrt(2)',
                                             'arg zw = arg z + arg w = pi/4']),
    ('J', 'Polygon: centre+vertex', '0, 2, 4', ['v2 = 2i', 'v3 = -2', 'v4 = -2i',
                                               'side = 2sqrt(2)', 'area = 8']),
    ('J', 'Polygon: centre+vertex', '1+i, 3+i, 3', ['v2 = 2.73i', 'v3 = -0.732i',
                                                   'side = 2sqrt(3)', 'area = 3sqrt(3)']),
    ('J', 'Polygon: two vertices', '0, 2, 3', ['centre = 1+sqrt(3)i/3',
                                              'v3 = 1+sqrt(3)i', 'area = sqrt(3)']),
    ('J', 'Polygon: two vertices', '0, 1, 4', ['v3 = 1+i', 'v4 = i', 'area = 1']),

    # ---- M  Matrices and transformations -------------------------------
    ('M', 'pA + qB (2x2)', '1,-1,1,2,3,4,0,1,1,0', ['pA+qB = [1 1]', '[2 4]']),
    ('M', 'pA + qB (3x3)', '2,0,1,2,3,4,5,6,7,8,9,0,0,0,0,0,0,0,0,0',
     ['pA+qB = [2 4 6]', '[8 10 12]', '[14 16 18]']),
    ('M', 'AB and BA (2x2)', '1,2,3,4,0,1,1,0', ['AB = [2 1]', 'BA = [3 4]',
                                                 'AB is not BA: order matters']),
    ('M', 'AB and BA (3x3)', '1,2,0,0,1,0,0,0,1,1,0,0,3,1,0,0,0,1',
     ['AB = [7 2 0]', '[3 1 0]']),
    ('M', 'Determinant 2x2', '3,1,2,4', ['det A = 10', 'area scale factor = 10']),
    ('M', 'Determinant 2x2', '1,2,3,4', ['det A = -2',
                                         'det < 0: orientation is reversed']),
    ('M', 'Determinant 3x3', '1,2,3,0,1,4,5,6,0', ['det A = 1',
                                                   'volume scale factor = 1']),
    ('M', 'Determinant 3x3', '1,2,3,2,4,6,1,0,1', ['det A = 0', 'singular']),
    ('M', 'Inverse 2x2', '3,1,2,4', ['A^-1 = [2/5 -1/10]', '[-1/5 3/10]']),
    ('M', 'Inverse 2x2', '1,2,2,4', ['no inverse: det A = 0']),
    ('M', 'Inverse 3x3', '1,2,3,0,1,4,5,6,0', ['A^-1 = [-24 18 5]',
                                               '[20 -15 -4]', '[-5 4 1]']),
    ('M', 'Inverse 3x3', '1,2,3,2,4,6,1,0,1', ['no inverse: det A = 0']),
    ('M', 'Solve 3 eqns by A^-1', '1,1,1,2,-1,1,1,2,-1,6,3,2',
     ['x = 1', 'y = 2', 'z = 3', 'unique point']),
    ('M', 'Solve 3 eqns by A^-1', '1,1,1,1,2,3,2,3,4,1,2,3',
     ['sheaf: the planes share a line', 'direction (1, -2, 1)',
      'point (1/2, 0, 1/2)']),
    ('M', 'Solve 3 eqns by A^-1', '1,1,1,1,2,3,2,3,4,1,2,5',
     ['triangular prism: no solution']),
    ('M', 'Solve 3 eqns by A^-1', '1,1,1,2,2,2,1,2,-1,6,13,2',
     ['two planes are parallel', 'no solution']),
    ('M', 'Rotation 2D (deg)', '90', ['R = [0 -1]', '[1 0]',
                                      'rotation 90 deg about O']),
    ('M', 'Reflect in y=x tan t', '45', ['M = [0 1]', '[1 0]',
                                         'reflect in y = x tan 45 deg']),
    ('M', 'Stretch or enlarge 2D', '3,3', ['enlargement scale factor 3',
                                           'det = 9 = area scale factor']),
    ('M', 'Stretch or enlarge 2D', '2,1', ['stretch x by 2, y by 1']),
    ('M', 'Describe a 2x2', '0,-1,1,0', ['rotation 90 deg about O', 'det = 1']),
    ('M', 'Describe a 2x2', '0,1,1,0', ['reflection in y = x', 'det = -1']),
    ('M', 'Describe a 2x2', '1,2,3,4', ['not a standard transformation']),
    ('M', 'Rotation 3D (axis)', '3,90', ['R = [0 -1 0]', 'rotate 90 deg about z']),
    ('M', 'Reflect 3D in plane', '2', ['M = [1 0 0]', '[0 -1 0]',
                                       'reflect in the plane y = 0']),
    ('M', 'Invariant points/lines', '3,-1,-1,3', ['only invariant point is (0, 0)',
                                                  'invariant line y = x',
                                                  'invariant line y = -x']),
    ('M', 'Invariant points/lines', '1,2,0,1', ['line of invariant points y = 0']),
    ('M', 'Det 3x3 in terms of k', 'k,1,2,0,k,1,1,0,1', ['k^2-2*k+1',
                                                         'singular when k = 1',
                                                         'adj r1: [k, -1, -2*k+1]',
                                                         'adj r3: [-k, 1, k^2]']),
    ('M', 'Det 3x3 in terms of k', '1,2,3,0,1,4,5,6,0', ['never singular',
                                                         'adj r1: [-24, 18, 5]']),
    ('M', 'Det 3x3 in terms of k', 'k,1,0,1,k,0,0,0,1', ['k^2-1',
                                                         'singular when k = -1, 1']),
    ('M', 'Det 3x3 in terms of k', '1,2,3,4,5,6,7,8,k', ['-3*k+27', 'singular when k = 9',
                                                         'ei-fh = 5*k-48']),
    ('M', 'Det 3x3 in terms of k', '1,2,3,2,4,6,1,1,k', ['singular for every k']),
    ('M', 'Shear 2D', '3, 1', ['S = [1 3]', 'shear, x-axis fixed, factor 3']),
    ('M', 'Shear 2D', '2, 2', ['[2 1]', 'shear, y-axis fixed, factor 2']),
    ('M', 'Describe a 2x2', '1,0,0,-1', ['reflection in the x-axis']),
    ('M', 'Describe a 2x2', '1,2,0,1', ['shear, x-axis fixed, factor 2']),
    ('M', 'Describe a 2x2', '2,1,-1,0', ['shear, line y = -x fixed']),
    ('M', 'Describe a 2x2', '1,1,-1,1', ['rotation -45 deg about O',
                                         'and enlargement sf sqrt(2)', 'det = 2']),
    ('M', 'Describe a 2x2', '3,0,0,1', ['stretch parallel to x-axis, sf 3']),
    ('M', 'A then B (2x2)', '1,0,0,-1,0,-1,1,0', ['BA = [0 1]',
                                                  'A: reflection in the x-axis',
                                                  'B: rotation 90 deg about O',
                                                  'BA: reflection in y = x',
                                                  'det BA = det B x det A = -1']),
    ('M', 'Describe a 3x3', '1,0,0,0,0,-1,0,1,0', ['rotate 90 deg about x', 'det = 1']),
    ('M', 'Describe a 3x3', '1,0,0,0,-1,0,0,0,1', ['reflect in the plane y = 0',
                                                   'det = -1']),
    ('M', 'Describe a 3x3', '1,2,3,4,5,6,7,8,10', ['not a single standard map',
                                                   'volume scale factor = 3']),
    ('M', 'A then B (3x3)', '0,-1,0,1,0,0,0,0,1,0,-1,0,1,0,0,0,0,1',
     ['BA = [-1 0 0]', 'A: rotate 90 deg about z', 'BA: rotate 180 deg about z']),

    # ---- V  Vectors and 3-D --------------------------------------------
    ('V', 'Line from two points', '1,2,3,3,5,7',
     ['r = (1, 2, 3) + t(2, 3, 4)', '(x - 1)/2 = (y - 2)/3 = (z - 3)/4']),
    ('V', 'Line to cartesian', '1,0,2,2,-1,0',
     ['(x - 1)/2 = y/(-1)', 'z = 2']),
    ('V', 'Plane from 3 points', '1,0,0,0,1,0,0,0,1',
     ['r.(1, 1, 1) = 1', 'x + y + z = 1']),
    ('V', 'Plane point + normal', '1,2,3,2,-1,2',
     ['r.(2, -1, 2) = 6', '2x - y + 2z = 6']),
    ('V', 'Angle between lines', '1,0,0,1,1,0', ['angle = pi/4 rad', '45 deg']),
    ('V', 'Angle line and plane', '1,1,1,0,0,1',
     ['angle = 0.615 rad', '35.3 deg', 'sqrt(3)/3']),
    ('V', 'Angle between planes', '1,0,0,1,1,0', ['angle = pi/4 rad']),
    ('V', 'Perpendicular check', '1,2,3,2,-1,0', ['perpendicular', 'not parallel']),
    ('V', 'Perpendicular check', '1,2,3,2,4,6', ['not perpendicular', 'a.b = 28']),
    ('V', 'Vector product', '1,2,3,4,5,6',
     ['a x b = (-3, 6, -3)', '|a x b| = 3sqrt(6)']),
    ('V', 'Area of triangle', '0,0,0,1,0,0,0,1,0', ['area = 1/2']),
    ('V', 'Is p on (r-a)xb=0', '1,1,1,1,2,3,3,5,7', ['p is on the line', 't = 2']),
    ('V', 'Is p on (r-a)xb=0', '1,1,1,1,2,3,0,0,0', ['p is not on the line']),
    ('V', 'Intersect two lines', '1,1,1,1,0,0,0,1,1,0,1,0',
     ['they meet at (0, 1, 1)', 't = -1,  s = 0']),
    ('V', 'Intersect two lines', '0,0,0,1,0,0,0,1,1,0,0,1',
     ['skew lines', 'distance = 1']),
    ('V', 'Intersect two lines', '0,0,0,1,0,0,0,1,0,2,0,0',
     ['parallel, no intersection', 'distance = 1']),
    ('V', 'Distance two lines', '0,0,0,1,0,0,0,1,1,0,0,1',
     ['skew lines', 'distance = 1']),
    ('V', 'Distance two lines', '0,0,0,1,0,0,0,1,0,2,0,0',
     ['parallel lines', 'distance = 1']),
    ('V', 'Line meets plane', '1,1,1,1,1,1,1,0,0,4',
     ['meets at (4, 4, 4)', 'angle = 0.615 rad']),
    ('V', 'Line meets plane', '0,0,0,1,0,0,0,0,1,5',
     ['parallel, never meets', 'distance = 5']),
    ('V', 'Point to line dist', '1,2,3,0,0,0,1,0,0',
     ['distance = sqrt(13)', 'foot = (1, 0, 0)']),
    ('V', 'Point to plane dist', '1,1,1,1,2,2,0',
     ['distance = 5/3', 'foot = (4/9, -1/9, -1/9)']),
    ('V', 'Scalar product, angle', '1,2,2,2,-1,2', ['a.b = 4', 'angle = 1.11 rad',
                                                    '63.6 deg', 'cos t = a.b/(|a||b|) = 4/9']),
    ('V', 'Scalar product, angle', '1,0,0,0,1,0', ['a.b = 0', 'angle = pi/2 rad',
                                                   'a and b are perpendicular']),
    ('V', 'Plane pt + 2 dirs', '1,2,3,1,0,1,0,1,1', ['r.(1, 1, -1) = 0', 'x + y - z = 0',
                                                     'n = b x c = (1, 1, -1)']),
    ('V', 'Plane pt + 2 dirs', '0,0,0,1,0,0,2,0,0', ['the directions are parallel']),
    ('V', 'Plane cartesian->vec', '1,1,1,3', ['point (3, 0, 0)',
                                              'directions (1, -1, 0), (1, 0, -1)']),
    ('V', 'Plane cartesian->vec', '2,-1,3,6', ['point (0, 0, 2)',
                                               'directions (1, 2, 0), (3, 0, -2)']),
    ('V', 'Three planes', '1,1,1,6,2,-1,1,3,1,2,-1,2', ['meet at one point', '(1, 2, 3)']),
    ('V', 'Three planes', '1,1,1,1,1,2,3,2,2,3,4,3', ['sheaf: the planes share a line',
                                                      'point (1/2, 0, 1/2)',
                                                      'direction (1, -2, 1)']),
    ('V', 'Three planes', '1,1,1,1,1,2,3,2,2,3,4,5', ['triangular prism: no solution']),
    ('V', 'Three planes', '1,1,1,6,2,2,2,13,1,2,-1,2', ['two planes are parallel']),
    ('V', 'Three planes', '1,1,1,1,2,2,2,5,3,3,3,7', ['parallel planes: no solution']),
    ('V', 'Three planes', '1,1,1,1,2,2,2,2,3,3,3,3', ['the three planes are the same']),
    ('V', 'Vector product', '1,0,0,0,2,0', ['a x b = (0, 0, 2)',
                                            'n-hat = (0, 0, 1)',
                                            'sin t = |a x b|/(|a||b|) = 1']),

    # ---- A  Roots of polynomials ---------------------------------------
    ('A', 'Vieta root sums', '1,-6,11,-6', ['sum of roots = 6',
                                            'sum of pairs = 11',
                                            'product of all = 6']),
    ('A', 'Vieta root sums', '2,-5,2', ['sum of roots = 5/2',
                                        'product of all = 1']),
    ('A', 'Power sums of roots', '4,1,-3,2', ['S1 = sum a^1 = 3',
                                              'S2 = sum a^2 = 5',
                                              'S3 = sum a^3 = 9',
                                              'S4 = sum a^4 = 17']),
    ('A', 'Roots p a + q', '2,1,1,-3,2', ['x^2-8*x+15']),
    ('A', 'Roots 1/a', '1,-3,2', ['2*x^2-3*x+1']),
    ('A', 'Roots a^2', '1,-3,2', ['x^2-5*x+4']),

    # ---- S  Series and Maclaurin ---------------------------------------
    ('S', 'Sum r, r^2, r^3', '10', ['sum r = n(n+1)/2 = 55',
                                    'sum r^2 = n(n+1)(2n+1)/6 = 385',
                                    'sum r^3 = (n(n+1)/2)^2 = 3025']),
    ('S', 'Sum f(r), r = a..b', 'r^2+r,1,10', ['sum = 440']),
    ('S', 'Sum f(r), r = a..b', 'r^3,3,8', ['sum = 1287']),
    ('S', 'Method of differences', '1/(r(r+1)),10', ['g(r) = 1/r',
                                                     'S(10) = 10/11']),
    ('S', 'Method of differences', '2/((2r-1)(2r+1))', ['g(r) = 1/(2*r-1)',
                                                        'S(n) = 1 - (1/(2*n+1))']),
    ('S', 'Method of differences', '1/(r(r+1)(r+2)),4', ['S(4) = 7/30']),
    ('S', 'Maclaurin series', 'e^x,4', ['x^4/24+x^3/6+x^2/2+x+1',
                                        'term r: x^r/r!']),
    ('S', 'Maclaurin series', 'ln(1+x),4', ['valid for -1 < x <= 1']),
    ('S', 'Binomial (1+x)^p', '1/2,3', ['x^3/16-x^2/8+x/2+1',
                                        'valid only for |x| < 1']),
    ('S', 'Binomial (1+x)^p', '3,4', ['x^3+3*x^2+3*x+1',
                                      'p is a whole number: the series stops']),
    ('S', 'Maclaurin series', 'ln(1+2x),3', ['8*x^3/3-2*x^2+2*x',
                                            'valid for -1/2 < x <= 1/2']),
    ('S', 'Maclaurin series', '1/(1-x),3', ['x^3+x^2+x+1', 'valid for -1 < x < 1']),
    ('S', 'Maclaurin series', 'sqrt(4-x),3', ['-x^3/512-x^2/64-x/4+2',
                                             'valid for -4 < x < 4']),
    ('S', 'Maclaurin series', 'e^x*ln(1+x),3', ['x^3/3+x^2/2+x',
                                               'valid for -1 < x <= 1']),
    ('S', 'Maclaurin series', 'atan(x),5', ['x^5/5-x^3/3+x', 'valid for -1 <= x <= 1']),
    ('S', 'Maclaurin series', 'tan(x),5', ['2*x^5/15+x^3/3+x',
                                          'validity: not a standard form']),
    ('S', 'Maclaurin approx', 'e^x,4,0.5', ['series = 1.65', 'error = 0.000284',
                                           'series value 1.64844']),
    ('S', 'Maclaurin approx', 'ln(1+x),4,2', ['series = -1.33',
                                             'x = 2 is outside the interval',
                                             'valid for -1 < x <= 1']),
]
