# Cases for fcalc (MEI H645 Core Pure: calculus, polar, hyperbolic functions,
# differential equations). Every tool has at least one case; branchy tools
# (convergence, damping, auxiliary roots) have one case per branch.
# Numbers checked by hand.
CASES = [
    # ---- C  Calculus ---------------------------------------------------
    ('C', 'Integral to infinity', '1/x^2,1', ['integral = 1', 'up to 1000001']),
    ('C', 'Integral to infinity', '1/x,1', ['diverges']),
    ('C', 'Integral to infinity', 'e^(-x),0', ['integral = 1']),
    ('C', 'Singular endpoint int', '1/sqrt(x),0,1', ['integral = 2',
                                                     'f is undefined at x = 0']),
    ('C', 'Singular endpoint int', '1/sqrt(1-x),0,1', ['integral = 2',
                                                       'f is undefined at x = 1']),
    ('C', 'Singular endpoint int', '1/x,0,1', ['diverges']),
    ('C', 'Volume about x-axis', 'x,0,1', ['V = pi/3', '= 1.05']),
    ('C', 'Volume about x-axis', 'x^2,0,2', ['V = 32pi/5', 'int y^2 dx = 6.4']),
    ('C', 'Volume about y-axis', 'y^2,0,1', ['V = pi/5']),
    ('C', 'Mean value of f', 'x^2,0,3', ['mean = 3', 'f = mean at x = 1.73']),
    ('C', 'Mean value of f', 'sin(x),0,pi', ['mean = 0.637', 'int f dx = 2']),
    ('C', 'Integrate by partials', '3x+1,(x-1)(x^2+1)',
     ['atan(x)+2*ln(|x-1|)-ln(x^2+1)', '2/(x-1)+(-2*x+1)/(x^2+1)']),
    ('C', 'Integrate by partials', '5x-2,x^2-4', ['2/(x-2)+3/(x+2)']),
    ('C', 'd/dx inverse trig', 'asin(x/3),1', ['1/(3*sqrt(-x^2/9+1))',
                                               "f'(1) = sqrt(2)/4"]),
    ('C', 'd/dx inverse trig', 'atan(2x),?', ['2/(4*x^2+1)']),
    ('C', 'Int 1/sqrt(a2-x2)', '2,0,1', ['integral = pi/6', 'asin(x/2)']),
    ('C', 'Int 1/(a2+x2)', '3,0,3', ['integral = pi/12', 'atan(x/3)/3']),

    # ---- PO  Polar coordinates -----------------------------------------
    ('PO', 'Polar to cartesian', '2,pi/3', ['x = 1', 'y = sqrt(3)']),
    ('PO', 'Cartesian to polar', '1,1', ['r = sqrt(2)', 'theta = pi/4 rad']),
    ('PO', 'Plot r = f(theta)', '1+cos(x)', ['r(0) = 2', 'r(pi) = 0']),
    ('PO', 'Polar area', '2,0,2pi', ['area = 4pi', '12.6']),
    ('PO', 'Polar area', '1+cos(x),0,pi', ['area = 3pi/4']),

    # ---- H  Hyperbolic functions ---------------------------------------
    ('H', 'Six hyperbolics at x', '1',
     ['sinh x = 1.18', 'cosh x = 1.54', 'tanh x = 0.762', 'coth x = 1.31']),
    ('H', 'Six hyperbolics at x', '0',
     ['sinh x = 0', 'cosh x = 1', 'cosech and coth undefined at 0']),
    ('H', 'Inverse hyperbolics', '2',
     ['arsinh x = 1.44', 'ln(2 + sqrt(5))', 'arcosh x = 1.32',
      'artanh needs |x| < 1']),
    ('H', 'Inverse hyperbolics', '0.5',
     ['artanh x = 0.549', 'arcosh needs x >= 1']),
    ('H', 'Solve a cosh+b sinh=c', '1,0,2',
     ['x = ln(2 + sqrt(3))', 'x = ln(2 - sqrt(3))', '= 1.32']),
    ('H', 'Solve a cosh+b sinh=c', '5,3,4', ['x = ln(1/2)', '= -0.693']),
    ('H', 'Solve a cosh+b sinh=c', '1,0,0.5', ['no real solutions']),
    ('H', 'Identity check at x', '1',
     ['cosh^2-sinh^2 = 1', 'sinh2x = 3.63, 2sc = 3.63']),
    ('H', 'Plot sinh cosh tanh', '3', ['cosh x: all x, y >= 1, even',
                                       'tanh = 0.995']),
    ('H', 'd/dx hyperbolic', 'cosh(2x),0', ['2*sinh(2*x)', "f'(0) = 0"]),
    ('H', 'Integrate hyperbolic', 'sinh(x),0,1',
     ['cosh(x)', 'int from 0 to 1 = 0.543']),
    ('H', 'Integrate hyperbolic', 'x*cosh(x),?,?', ['sinh(x)*x-cosh(x)']),
    ('H', 'Int 1/sqrt(x2+a2)', '2,0,2', ['integral = 0.881', 'asinh(x/2)']),
    ('H', 'Int 1/sqrt(x2-a2)', '3,3,6', ['integral = 1.32', 'acosh(x/3)']),

    # ---- D  Differential equations -------------------------------------
    ('D', 'Integrating factor', '2/x,x^2,?,?',
     ['x^2', '(x^5/5+C)/x^2', 'int IF*Q dx = x^5/5']),
    ('D', 'Integrating factor', '1,e^(2x),0,1',
     ['(C+e^(3*x)/3)*e^(-x)', 'C = 2/3']),
    ('D', 'Integrating factor', 'tan(x),1,?,?',
     ['sec(x)', 'int IF*Q dx = ln(|sec(x)+tan(x)|)']),
    ('D', 'Second order homogen', '1,-3,2',
     ['m = 2 and 1', 'A*e^(2*x)+B*e^(x)', 'aux: m^2 - 3m + 2 = 0']),
    ('D', 'Second order homogen', '1,4,4',
     ['m = -2 (repeated)', '(B*x+A)*e^(-2*x)', 'disc = b^2 - 4ac = 0']),
    ('D', 'Second order homogen', '1,2,5',
     ['m = -1 +/- 2 i', '(A*cos(2*x)+B*sin(2*x))*e^(-x)']),
    ('D', 'Second order with IVs', '1,-3,2,1,0',
     ['2*e^(x)-e^(2*x)', 'A = -1,  B = 2']),
    ('D', 'Second order with IVs', '1,4,4,1,0', ['(2*x+1)*e^(-2*x)']),
    ('D', 'Second order with IVs', '1,0,4,3,0', ['3*cos(2*x)', 'A = 3,  B = 0']),
    ('D', 'PI polynomial RHS', '1,0,-2,x^2',
     ['PI: -x^2/2-1/2', 'A*e^(sqrt(2)*x)+B*e^(-sqrt(2)*x)-x^2/2-1/2']),
    ('D', 'PI polynomial RHS', '1,3,0,6x',
     ['PI: x^2-2*x/3', 'B*e^(-3*x)+x^2+A-2*x/3',
      'c = 0, so the trial is raised a degree']),
    ('D', 'PI for k e^(px)', '1,-3,2,1,3', ['PI: e^(3*x)/2', 'ap^2+bp+c = 2']),
    ('D', 'PI for k e^(px)', '1,-3,2,1,1',
     ['PI: -e^(x)*x', 'p is a root, so trial C x e^(px)']),
    ('D', 'PI for k e^(px)', '1,-2,1,1,1',
     ['PI: e^(x)*x^2/2', 'p is a repeated root: trial C x^2 e^(px)']),
    ('D', 'PI for m cos + n sin', '1,0,4,0,1,1',
     ['PI: sin(x)/3', 'P = 0, Q = 1/3']),
    ('D', 'PI for m cos + n sin', '1,0,4,0,1,2',
     ['PI: -cos(2*x)*x/4', 'wi is a root, so trial x(P cos + Q sin)']),
    ('D', 'SHM from omega', '2,3,0',
     ['amplitude R = 3', 'period T = pi', '3*cos(2*t)', 'max speed = 6']),
    ('D', 'SHM from omega', '2,?,?',
     ['period T = pi', 'C*cos(2*t)+D*sin(2*t)']),
    ('D', 'Hooke law SHM', '8,2', ['w = 2', 'period T = pi', 'k/m = 4']),
    ('D', 'Damping classify', '1,3,2',
     ['heavy damping', 'm = -1 and -2', 'disc = c^2 - 4mk = 1']),
    ('D', 'Damping classify', '1,2,1', ['critical damping', '(B*t+A)*e^(-t)']),
    ('D', 'Damping classify', '1,1,4',
     ['light damping', 'oscillates, amplitude decays']),
    ('D', 'Damping classify', '1,0,4',
     ['no damping (SHM)', 'oscillates, amplitude constant']),
    ('D', 'Coupled equations', '1,1,4,1,?,?',
     ['A*e^(3*t)+B*e^(-t)', '2*A*e^(3*t)-2*B*e^(-t)', 'a+d = 2,  ad-bc = -3']),
    ('D', 'Coupled equations', '1,1,4,1,1,0',
     ['e^(-t)/2+e^(3*t)/2', 'e^(3*t)-e^(-t)']),
    ('D', 'Coupled equations', '0,1,-1,0,1,0', ['cos(t)', '-sin(t)']),
    ('D', 'Separable DE', 'x,y,?,?', ['ln(|y|) = x^2/2 + c', 'int f(x) dx = x^2/2']),
    ('D', 'Separable DE', 'x,y,0,2', ['e^(x^2/2+ln(2))', 'c = ln(2) from (0, 2)',
                                      'y keeps the sign it has at x0']),
    ('D', 'Separable DE', '2x,y^2+1,0,1', ['tan(x^2+pi/4)', 'atan(y) = x^2 + pi/4']),
    ('D', 'PI polynomial RHS', '1,0,1,x,0,0', ['x-sin(x)', 'A = 0,  B = -1']),
    ('D', 'PI for k e^(px)', '1,-3,2,1,3,1,0', ['A = -2,  B = 5/2',
                                               'e^(3*x)/2+5*e^(x)/2-2*e^(2*x)']),
    ('D', 'PI for m cos + n sin', '1,0,4,0,1,1,0,0', ['sin(x)/3-sin(2*x)/6',
                                                     'A = 0,  B = -1/6']),
    ('D', 'a = v dv/dx = f(x)', '-4x,0,6,2', ['-4*x^2+36', 'at x = 2: v = +/-2sqrt(5)',
                                              'v = 0 at x = -3, 3']),
    ('D', 'a = v dv/dx = f(x)', '-4x,0,6,5', ['x = 5 is never reached']),
    ('D', 'a = f(v): dist, time', '-2v,10,5', ['time = 0.347', 'distance = 5/2']),
    ('D', 'a = f(v): dist, time', '10-v,0,5', ['time = 0.693', 'distance = 1.93']),
    ('D', 'a = f(v): dist, time', '-(1+v^2),1,0', ['time = pi/4', 'distance = 0.347']),
    ('D', 'a = f(v): dist, time', '10-v,0,10', ['v never reaches 10']),
]
